// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/vmd.proto

package vmdpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VMDaemon_DestroyVM_FullMethodName               = "/superserve.vmd.v1.VMDaemon/DestroyVM"
	VMDaemon_PauseVM_FullMethodName                 = "/superserve.vmd.v1.VMDaemon/PauseVM"
	VMDaemon_ResumeVM_FullMethodName                = "/superserve.vmd.v1.VMDaemon/ResumeVM"
	VMDaemon_CreateSnapshot_FullMethodName          = "/superserve.vmd.v1.VMDaemon/CreateSnapshot"
	VMDaemon_RestoreSnapshot_FullMethodName         = "/superserve.vmd.v1.VMDaemon/RestoreSnapshot"
	VMDaemon_DeleteSnapshot_FullMethodName          = "/superserve.vmd.v1.VMDaemon/DeleteSnapshot"
	VMDaemon_DeleteTemplateArtifacts_FullMethodName = "/superserve.vmd.v1.VMDaemon/DeleteTemplateArtifacts"
	VMDaemon_ExecCommand_FullMethodName             = "/superserve.vmd.v1.VMDaemon/ExecCommand"
	VMDaemon_GetVMInfo_FullMethodName               = "/superserve.vmd.v1.VMDaemon/GetVMInfo"
	VMDaemon_SetupNetwork_FullMethodName            = "/superserve.vmd.v1.VMDaemon/SetupNetwork"
	VMDaemon_UpdateSandboxNetwork_FullMethodName    = "/superserve.vmd.v1.VMDaemon/UpdateSandboxNetwork"
	VMDaemon_BuildTemplate_FullMethodName           = "/superserve.vmd.v1.VMDaemon/BuildTemplate"
	VMDaemon_GetBuildStatus_FullMethodName          = "/superserve.vmd.v1.VMDaemon/GetBuildStatus"
	VMDaemon_CancelBuild_FullMethodName             = "/superserve.vmd.v1.VMDaemon/CancelBuild"
	VMDaemon_StreamBuildLogs_FullMethodName         = "/superserve.vmd.v1.VMDaemon/StreamBuildLogs"
)

// VMDaemonClient is the client API for VMDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VMDaemon manages Firecracker microVM lifecycles for the AgentBox platform.
type VMDaemonClient interface {
	// DestroyVM terminates a running microVM and cleans up all associated resources.
	DestroyVM(ctx context.Context, in *DestroyVMRequest, opts ...grpc.CallOption) (*DestroyVMResponse, error)
	// PauseVM snapshots a running VM's state and suspends it (sleep).
	PauseVM(ctx context.Context, in *PauseVMRequest, opts ...grpc.CallOption) (*PauseVMResponse, error)
	// ResumeVM restores a paused VM from its snapshot, optionally into a pre-warmed slot.
	ResumeVM(ctx context.Context, in *ResumeVMRequest, opts ...grpc.CallOption) (*ResumeVMResponse, error)
	// CreateSnapshot captures a point-in-time snapshot of a running VM.
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	// RestoreSnapshot boots a VM from a previously captured snapshot.
	RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*RestoreSnapshotResponse, error)
	// DeleteSnapshot removes a snapshot's on-disk artifacts (vmstate + memory
	// file). Idempotent — missing files are treated as success. Used by the
	// control plane to garbage-collect the previous snapshot when a sandbox is
	// re-paused and only the latest snapshot is reachable.
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	// DeleteTemplateArtifacts removes a template's on-disk snapshot dir and
	// rootfs. Idempotent.
	DeleteTemplateArtifacts(ctx context.Context, in *DeleteTemplateArtifactsRequest, opts ...grpc.CallOption) (*DeleteTemplateArtifactsResponse, error)
	// ExecCommand runs a command inside a VM and streams stdout/stderr back.
	ExecCommand(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecCommandResponse], error)
	// GetVMInfo returns the current status and metadata of a VM.
	GetVMInfo(ctx context.Context, in *GetVMInfoRequest, opts ...grpc.CallOption) (*GetVMInfoResponse, error)
	// SetupNetwork configures networking for a VM (TAP device, NAT, IP allocation).
	SetupNetwork(ctx context.Context, in *SetupNetworkRequest, opts ...grpc.CallOption) (*SetupNetworkResponse, error)
	// UpdateSandboxNetwork atomically replaces the egress allow/deny rules for a running VM.
	UpdateSandboxNetwork(ctx context.Context, in *UpdateSandboxNetworkRequest, opts ...grpc.CallOption) (*UpdateSandboxNetworkResponse, error)
	// BuildTemplate kicks off a template build asynchronously. Returns a
	// build_vm_id immediately; the caller polls GetBuildStatus(build_vm_id)
	// for progress and uses CancelBuild(build_vm_id) to abort.
	BuildTemplate(ctx context.Context, in *BuildTemplateRequest, opts ...grpc.CallOption) (*BuildTemplateResponse, error)
	// GetBuildStatus returns the current state of a build dispatched via
	// BuildTemplate. Used by the control plane's build supervisor to poll
	// until a terminal status is reached.
	GetBuildStatus(ctx context.Context, in *GetBuildStatusRequest, opts ...grpc.CallOption) (*GetBuildStatusResponse, error)
	// CancelBuild aborts an in-flight build and tears down the build VM.
	// Idempotent — no-op for unknown or already-terminal builds.
	CancelBuild(ctx context.Context, in *CancelBuildRequest, opts ...grpc.CallOption) (*CancelBuildResponse, error)
	// StreamBuildLogs returns a server-streaming feed of log events for a
	// build. Replays buffered history in order first, then streams live
	// events as they arrive. Closes when the build reaches a terminal
	// status. Used by the control plane to drive /builds/:id/logs SSE.
	StreamBuildLogs(ctx context.Context, in *StreamBuildLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BuildLogEvent], error)
}

type vMDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewVMDaemonClient(cc grpc.ClientConnInterface) VMDaemonClient {
	return &vMDaemonClient{cc}
}

func (c *vMDaemonClient) DestroyVM(ctx context.Context, in *DestroyVMRequest, opts ...grpc.CallOption) (*DestroyVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyVMResponse)
	err := c.cc.Invoke(ctx, VMDaemon_DestroyVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) PauseVM(ctx context.Context, in *PauseVMRequest, opts ...grpc.CallOption) (*PauseVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseVMResponse)
	err := c.cc.Invoke(ctx, VMDaemon_PauseVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) ResumeVM(ctx context.Context, in *ResumeVMRequest, opts ...grpc.CallOption) (*ResumeVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeVMResponse)
	err := c.cc.Invoke(ctx, VMDaemon_ResumeVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, VMDaemon_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*RestoreSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreSnapshotResponse)
	err := c.cc.Invoke(ctx, VMDaemon_RestoreSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, VMDaemon_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) DeleteTemplateArtifacts(ctx context.Context, in *DeleteTemplateArtifactsRequest, opts ...grpc.CallOption) (*DeleteTemplateArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTemplateArtifactsResponse)
	err := c.cc.Invoke(ctx, VMDaemon_DeleteTemplateArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) ExecCommand(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecCommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VMDaemon_ServiceDesc.Streams[0], VMDaemon_ExecCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecCommandRequest, ExecCommandResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMDaemon_ExecCommandClient = grpc.ServerStreamingClient[ExecCommandResponse]

func (c *vMDaemonClient) GetVMInfo(ctx context.Context, in *GetVMInfoRequest, opts ...grpc.CallOption) (*GetVMInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVMInfoResponse)
	err := c.cc.Invoke(ctx, VMDaemon_GetVMInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) SetupNetwork(ctx context.Context, in *SetupNetworkRequest, opts ...grpc.CallOption) (*SetupNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupNetworkResponse)
	err := c.cc.Invoke(ctx, VMDaemon_SetupNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) UpdateSandboxNetwork(ctx context.Context, in *UpdateSandboxNetworkRequest, opts ...grpc.CallOption) (*UpdateSandboxNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSandboxNetworkResponse)
	err := c.cc.Invoke(ctx, VMDaemon_UpdateSandboxNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) BuildTemplate(ctx context.Context, in *BuildTemplateRequest, opts ...grpc.CallOption) (*BuildTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildTemplateResponse)
	err := c.cc.Invoke(ctx, VMDaemon_BuildTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) GetBuildStatus(ctx context.Context, in *GetBuildStatusRequest, opts ...grpc.CallOption) (*GetBuildStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBuildStatusResponse)
	err := c.cc.Invoke(ctx, VMDaemon_GetBuildStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) CancelBuild(ctx context.Context, in *CancelBuildRequest, opts ...grpc.CallOption) (*CancelBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelBuildResponse)
	err := c.cc.Invoke(ctx, VMDaemon_CancelBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDaemonClient) StreamBuildLogs(ctx context.Context, in *StreamBuildLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BuildLogEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VMDaemon_ServiceDesc.Streams[1], VMDaemon_StreamBuildLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBuildLogsRequest, BuildLogEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMDaemon_StreamBuildLogsClient = grpc.ServerStreamingClient[BuildLogEvent]

// VMDaemonServer is the server API for VMDaemon service.
// All implementations must embed UnimplementedVMDaemonServer
// for forward compatibility.
//
// VMDaemon manages Firecracker microVM lifecycles for the AgentBox platform.
type VMDaemonServer interface {
	// DestroyVM terminates a running microVM and cleans up all associated resources.
	DestroyVM(context.Context, *DestroyVMRequest) (*DestroyVMResponse, error)
	// PauseVM snapshots a running VM's state and suspends it (sleep).
	PauseVM(context.Context, *PauseVMRequest) (*PauseVMResponse, error)
	// ResumeVM restores a paused VM from its snapshot, optionally into a pre-warmed slot.
	ResumeVM(context.Context, *ResumeVMRequest) (*ResumeVMResponse, error)
	// CreateSnapshot captures a point-in-time snapshot of a running VM.
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	// RestoreSnapshot boots a VM from a previously captured snapshot.
	RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error)
	// DeleteSnapshot removes a snapshot's on-disk artifacts (vmstate + memory
	// file). Idempotent — missing files are treated as success. Used by the
	// control plane to garbage-collect the previous snapshot when a sandbox is
	// re-paused and only the latest snapshot is reachable.
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	// DeleteTemplateArtifacts removes a template's on-disk snapshot dir and
	// rootfs. Idempotent.
	DeleteTemplateArtifacts(context.Context, *DeleteTemplateArtifactsRequest) (*DeleteTemplateArtifactsResponse, error)
	// ExecCommand runs a command inside a VM and streams stdout/stderr back.
	ExecCommand(*ExecCommandRequest, grpc.ServerStreamingServer[ExecCommandResponse]) error
	// GetVMInfo returns the current status and metadata of a VM.
	GetVMInfo(context.Context, *GetVMInfoRequest) (*GetVMInfoResponse, error)
	// SetupNetwork configures networking for a VM (TAP device, NAT, IP allocation).
	SetupNetwork(context.Context, *SetupNetworkRequest) (*SetupNetworkResponse, error)
	// UpdateSandboxNetwork atomically replaces the egress allow/deny rules for a running VM.
	UpdateSandboxNetwork(context.Context, *UpdateSandboxNetworkRequest) (*UpdateSandboxNetworkResponse, error)
	// BuildTemplate kicks off a template build asynchronously. Returns a
	// build_vm_id immediately; the caller polls GetBuildStatus(build_vm_id)
	// for progress and uses CancelBuild(build_vm_id) to abort.
	BuildTemplate(context.Context, *BuildTemplateRequest) (*BuildTemplateResponse, error)
	// GetBuildStatus returns the current state of a build dispatched via
	// BuildTemplate. Used by the control plane's build supervisor to poll
	// until a terminal status is reached.
	GetBuildStatus(context.Context, *GetBuildStatusRequest) (*GetBuildStatusResponse, error)
	// CancelBuild aborts an in-flight build and tears down the build VM.
	// Idempotent — no-op for unknown or already-terminal builds.
	CancelBuild(context.Context, *CancelBuildRequest) (*CancelBuildResponse, error)
	// StreamBuildLogs returns a server-streaming feed of log events for a
	// build. Replays buffered history in order first, then streams live
	// events as they arrive. Closes when the build reaches a terminal
	// status. Used by the control plane to drive /builds/:id/logs SSE.
	StreamBuildLogs(*StreamBuildLogsRequest, grpc.ServerStreamingServer[BuildLogEvent]) error
	mustEmbedUnimplementedVMDaemonServer()
}

// UnimplementedVMDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVMDaemonServer struct{}

func (UnimplementedVMDaemonServer) DestroyVM(context.Context, *DestroyVMRequest) (*DestroyVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyVM not implemented")
}
func (UnimplementedVMDaemonServer) PauseVM(context.Context, *PauseVMRequest) (*PauseVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseVM not implemented")
}
func (UnimplementedVMDaemonServer) ResumeVM(context.Context, *ResumeVMRequest) (*ResumeVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeVM not implemented")
}
func (UnimplementedVMDaemonServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedVMDaemonServer) RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreSnapshot not implemented")
}
func (UnimplementedVMDaemonServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedVMDaemonServer) DeleteTemplateArtifacts(context.Context, *DeleteTemplateArtifactsRequest) (*DeleteTemplateArtifactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTemplateArtifacts not implemented")
}
func (UnimplementedVMDaemonServer) ExecCommand(*ExecCommandRequest, grpc.ServerStreamingServer[ExecCommandResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecCommand not implemented")
}
func (UnimplementedVMDaemonServer) GetVMInfo(context.Context, *GetVMInfoRequest) (*GetVMInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVMInfo not implemented")
}
func (UnimplementedVMDaemonServer) SetupNetwork(context.Context, *SetupNetworkRequest) (*SetupNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetupNetwork not implemented")
}
func (UnimplementedVMDaemonServer) UpdateSandboxNetwork(context.Context, *UpdateSandboxNetworkRequest) (*UpdateSandboxNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSandboxNetwork not implemented")
}
func (UnimplementedVMDaemonServer) BuildTemplate(context.Context, *BuildTemplateRequest) (*BuildTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildTemplate not implemented")
}
func (UnimplementedVMDaemonServer) GetBuildStatus(context.Context, *GetBuildStatusRequest) (*GetBuildStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBuildStatus not implemented")
}
func (UnimplementedVMDaemonServer) CancelBuild(context.Context, *CancelBuildRequest) (*CancelBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelBuild not implemented")
}
func (UnimplementedVMDaemonServer) StreamBuildLogs(*StreamBuildLogsRequest, grpc.ServerStreamingServer[BuildLogEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamBuildLogs not implemented")
}
func (UnimplementedVMDaemonServer) mustEmbedUnimplementedVMDaemonServer() {}
func (UnimplementedVMDaemonServer) testEmbeddedByValue()                  {}

// UnsafeVMDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMDaemonServer will
// result in compilation errors.
type UnsafeVMDaemonServer interface {
	mustEmbedUnimplementedVMDaemonServer()
}

func RegisterVMDaemonServer(s grpc.ServiceRegistrar, srv VMDaemonServer) {
	// If the following call panics, it indicates UnimplementedVMDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VMDaemon_ServiceDesc, srv)
}

func _VMDaemon_DestroyVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).DestroyVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_DestroyVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).DestroyVM(ctx, req.(*DestroyVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_PauseVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).PauseVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_PauseVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).PauseVM(ctx, req.(*PauseVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_ResumeVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).ResumeVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_ResumeVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).ResumeVM(ctx, req.(*ResumeVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_RestoreSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).RestoreSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_RestoreSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).RestoreSnapshot(ctx, req.(*RestoreSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_DeleteTemplateArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).DeleteTemplateArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_DeleteTemplateArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).DeleteTemplateArtifacts(ctx, req.(*DeleteTemplateArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_ExecCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VMDaemonServer).ExecCommand(m, &grpc.GenericServerStream[ExecCommandRequest, ExecCommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMDaemon_ExecCommandServer = grpc.ServerStreamingServer[ExecCommandResponse]

func _VMDaemon_GetVMInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).GetVMInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_GetVMInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).GetVMInfo(ctx, req.(*GetVMInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_SetupNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).SetupNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_SetupNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).SetupNetwork(ctx, req.(*SetupNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_UpdateSandboxNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSandboxNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).UpdateSandboxNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_UpdateSandboxNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).UpdateSandboxNetwork(ctx, req.(*UpdateSandboxNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_BuildTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).BuildTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_BuildTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).BuildTemplate(ctx, req.(*BuildTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_GetBuildStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).GetBuildStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_GetBuildStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).GetBuildStatus(ctx, req.(*GetBuildStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_CancelBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDaemonServer).CancelBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDaemon_CancelBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDaemonServer).CancelBuild(ctx, req.(*CancelBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDaemon_StreamBuildLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBuildLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VMDaemonServer).StreamBuildLogs(m, &grpc.GenericServerStream[StreamBuildLogsRequest, BuildLogEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMDaemon_StreamBuildLogsServer = grpc.ServerStreamingServer[BuildLogEvent]

// VMDaemon_ServiceDesc is the grpc.ServiceDesc for VMDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "superserve.vmd.v1.VMDaemon",
	HandlerType: (*VMDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DestroyVM",
			Handler:    _VMDaemon_DestroyVM_Handler,
		},
		{
			MethodName: "PauseVM",
			Handler:    _VMDaemon_PauseVM_Handler,
		},
		{
			MethodName: "ResumeVM",
			Handler:    _VMDaemon_ResumeVM_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _VMDaemon_CreateSnapshot_Handler,
		},
		{
			MethodName: "RestoreSnapshot",
			Handler:    _VMDaemon_RestoreSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _VMDaemon_DeleteSnapshot_Handler,
		},
		{
			MethodName: "DeleteTemplateArtifacts",
			Handler:    _VMDaemon_DeleteTemplateArtifacts_Handler,
		},
		{
			MethodName: "GetVMInfo",
			Handler:    _VMDaemon_GetVMInfo_Handler,
		},
		{
			MethodName: "SetupNetwork",
			Handler:    _VMDaemon_SetupNetwork_Handler,
		},
		{
			MethodName: "UpdateSandboxNetwork",
			Handler:    _VMDaemon_UpdateSandboxNetwork_Handler,
		},
		{
			MethodName: "BuildTemplate",
			Handler:    _VMDaemon_BuildTemplate_Handler,
		},
		{
			MethodName: "GetBuildStatus",
			Handler:    _VMDaemon_GetBuildStatus_Handler,
		},
		{
			MethodName: "CancelBuild",
			Handler:    _VMDaemon_CancelBuild_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecCommand",
			Handler:       _VMDaemon_ExecCommand_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBuildLogs",
			Handler:       _VMDaemon_StreamBuildLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/vmd.proto",
}
