package network

import (
	"context"
	"fmt"
	"slices"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/rs/zerolog"
)

func testSpecParams() (string, uint16, uint16, uint16, string, uint16, []uint16) {
	return "eth0", 3128, 3129, 5353, "169.254.0.21", 9443, []uint16{25, 465}
}

func testSpec(owned bool) hostFWSpec {
	iface, hp, tp, dp, sd, sp, bp := testSpecParams()
	return hostFWSpecFor(iface, hp, tp, dp, sd, sp, bp, owned)
}

// renderDump renders a fake kernel ruleset as iptables-save output, in the
// canonical form iptables-save uses (-m tcp/udp inserted, --to-ports, /32).
func renderDump(rules map[string][][]string, chains []string) string {
	var b strings.Builder
	for _, table := range []string{"filter", "nat"} {
		fmt.Fprintf(&b, "# Generated by test\n*%s\n", table)
		builtins := map[string][]string{
			"filter": {"INPUT", "FORWARD", "OUTPUT"},
			"nat":    {"PREROUTING", "INPUT", "OUTPUT", "POSTROUTING"},
		}[table]
		for _, c := range builtins {
			fmt.Fprintf(&b, ":%s ACCEPT [0:0]\n", c)
		}
		for _, tc := range chains {
			tab, chain, _ := strings.Cut(tc, "/")
			if tab == table {
				fmt.Fprintf(&b, ":%s - [0:0]\n", chain)
			}
		}
		for key, rs := range rules {
			tab, chain, _ := strings.Cut(key, "/")
			if tab != table {
				continue
			}
			for _, r := range rs {
				fmt.Fprintf(&b, "-A %s %s\n", chain, strings.Join(saveForm(r), " "))
			}
		}
		b.WriteString("COMMIT\n")
	}
	return b.String()
}

// saveForm converts installer-arg form into iptables-save output form.
func saveForm(args []string) []string {
	out := make([]string, 0, len(args)+2)
	for i := 0; i < len(args); i++ {
		a := args[i]
		out = append(out, a)
		if a == "-p" && i+1 < len(args) && (args[i+1] == "tcp" || args[i+1] == "udp") {
			out = append(out, args[i+1], "-m", args[i+1])
			i++
			continue
		}
		if a == "--to-port" {
			out[len(out)-1] = "--to-ports"
		}
		if a == "--comment" && i+1 < len(args) {
			out = append(out, "\""+args[i+1]+"\"")
			i++
			continue
		}
		if a == "-d" && i+1 < len(args) && !strings.Contains(args[i+1], "/") {
			out = append(out, args[i+1]+"/32")
			i++
		}
	}
	return out
}

// specKernel builds the fake kernel state exactly matching a spec, plus any
// unrelated host rules passed in.
func specKernel(spec hostFWSpec, extraShared map[string][][]string) (map[string][][]string, []string) {
	rules := map[string][][]string{}
	var chains []string
	for key, want := range spec.sharedOrdered {
		for _, w := range want {
			rules[key] = append(rules[key], append([]string(nil), w.args...))
		}
		for _, e := range extraShared[key] {
			rules[key] = append(rules[key], e)
		}
	}
	for key, want := range spec.ownedChains {
		chains = append(chains, key)
		for _, w := range want {
			rules[key] = append(rules[key], append([]string(nil), w.args...))
		}
	}
	return rules, chains
}

func mustVerify(t *testing.T, dump string, spec hostFWSpec) (bool, string) {
	t.Helper()
	d, err := parseIPTablesSave(dump)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	ok, class, _ := verifyHostFirewall(d, spec)
	return ok, class
}

func TestVerifyIntactAndIgnoresUnrelatedRules(t *testing.T) {
	spec := testSpec(true)
	rules, chains := specKernel(spec, map[string][][]string{
		"filter/FORWARD": {{"-i", "docker0", "-j", "ACCEPT"}},
	})
	// Unrelated rule interleaved: still intact.
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
		t.Fatalf("intact ruleset read as %s", class)
	}
}

func TestVerifyDetectsEveryMismatchClass(t *testing.T) {
	spec := testSpec(true)

	t.Run("missing-rule", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		rules["filter/FORWARD"] = rules["filter/FORWARD"][1:] // drop the port jump
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "missing-rule" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("duplicate-rule", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append(fw, fw[1]) // duplicate the udp drop at the end
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "duplicate-rule" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("misordered", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		// Move the clamp after the broad ACCEPT — the legacy AppendUnique hazard.
		fw[2], fw[3] = fw[3], fw[2]
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "misordered" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("mutated-rule", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		fw[1] = []string{"-i", "veth+", "-p", "udp", "--dport", "444", "-j", "DROP"} // wrong port
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "missing-rule" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("owned-chain-extra-rule", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		key := "filter/" + portDropChain
		rules[key] = append(rules[key], []string{"-p", "tcp", "--dport", "9999", "-j", "DROP"})
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "owned-chain-drift" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("owned-chain-reordered", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		key := "filter/" + portDropChain
		rs := rules[key]
		rs[0], rs[1] = rs[1], rs[0]
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "owned-chain-drift" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("missing-owned-chain", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		if ok, class := mustVerify(t, renderDump(rules, chains[:1]), spec); ok || class != "missing-chain" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
}

func TestVerifyWithoutOwnedChainsIgnoresThem(t *testing.T) {
	// Template-builder shape: manageOwnedChains=false must neither require nor
	// inspect the daemon-owned chains or their jumps.
	spec := testSpec(false)
	if len(spec.ownedChains) != 0 {
		t.Fatalf("unowned spec has owned chains: %v", spec.ownedChains)
	}
	for _, r := range spec.sharedOrdered["filter/FORWARD"] {
		if r.args[len(r.args)-1] == portDropChain {
			t.Fatal("unowned spec includes the port-drop jump")
		}
	}
	rules, chains := specKernel(spec, nil)
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
		t.Fatalf("unowned intact read as %s", class)
	}
}

func TestParseToleratesIncompatibleTableComments(t *testing.T) {
	// iptables-nft-save flags foreign native-nft tables (our host egress-block
	// table) as comment lines; they must parse cleanly, not force a slow path.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	dump := "# Table `sandbox_egress_block' is incompatible, use 'nft' tool.\n" + renderDump(rules, chains)
	if ok, class := mustVerify(t, dump, spec); !ok {
		t.Fatalf("incompatible-table comment broke verification: %s", class)
	}
}

func TestParseRejectsUnknownSyntax(t *testing.T) {
	for _, bad := range []string{
		"*filter\ngarbage line\nCOMMIT\n",
		"-A FORWARD -j ACCEPT\n", // rule before table
		"*filter\n-A\nCOMMIT\n",  // malformed rule
		":FORWARD ACCEPT [0:0]\n",
	} {
		if _, err := parseIPTablesSave(bad); err == nil {
			t.Fatalf("parser accepted %q", bad)
		}
	}
}

// fakeKernel backs the dump/restore seams so the repair path can be
// exercised without iptables; its restore handler implements the -F/-A
// subset atomic repair emits.
type fakeKernel struct {
	rules    map[string][][]string
	chains   []string
	restores int
	inputs   []string
}

func (k *fakeKernel) install(t *testing.T) func() {
	t.Helper()
	origDump, origRestore := dumpIPTables, restoreIPTables
	dumpIPTables = func(context.Context) (string, error) { return renderDump(k.rules, k.chains), nil }
	restoreIPTables = func(_ context.Context, input string) error {
		k.restores++
		k.inputs = append(k.inputs, input)
		table := ""
		for _, line := range strings.Split(input, "\n") {
			line = strings.TrimSpace(line)
			switch {
			case line == "" || line == "COMMIT":
			case strings.HasPrefix(line, "*"):
				table = line[1:]
			case strings.HasPrefix(line, "-F "):
				k.rules[table+"/"+strings.TrimPrefix(line, "-F ")] = nil
			case strings.HasPrefix(line, "-D "):
				fields := strings.Fields(line)
				key := table + "/" + fields[1]
				spec := fields[2:]
				found := false
				for i, r := range k.rules[key] {
					if ruleEqual(spec, r) {
						k.rules[key] = append(k.rules[key][:i:i], k.rules[key][i+1:]...)
						found = true
						break
					}
				}
				if !found {
					return fmt.Errorf("fake kernel: -D no match: %q", line)
				}
			case strings.HasPrefix(line, "-I "):
				fields := strings.Fields(line)
				key := table + "/" + fields[1]
				n, err := strconv.Atoi(fields[2])
				if err != nil || n < 1 || n > len(k.rules[key])+1 {
					return fmt.Errorf("fake kernel: bad -I position: %q", line)
				}
				rule := append([]string(nil), fields[3:]...)
				rs := k.rules[key]
				k.rules[key] = append(rs[:n-1:n-1], append([][]string{rule}, rs[n-1:]...)...)
			case strings.HasPrefix(line, "-A "):
				fields := strings.Fields(line)
				key := table + "/" + fields[1]
				k.rules[key] = append(k.rules[key], fields[2:])
			default:
				return fmt.Errorf("fake kernel: unsupported restore line %q", line)
			}
		}
		return nil
	}
	return func() { dumpIPTables, restoreIPTables = origDump, origRestore }
}

func TestRepairCanonicalizesMisorderAndDuplicates(t *testing.T) {
	spec := testSpec(true)
	rules, chains := specKernel(spec, map[string][][]string{
		"filter/FORWARD": {{"-i", "docker0", "-j", "ACCEPT"}},
	})
	// Sabotage FORWARD: move clamp after ACCEPTs and duplicate the udp drop.
	fw := rules["filter/FORWARD"]
	clamp := fw[2]
	fw = append(fw[:2], fw[3:]...)
	fw = append(fw, clamp, append([]string(nil), fw[1]...))
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()

	d, err := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if ok, _, _ := verifyHostFirewall(d, spec); ok {
		t.Fatal("sabotaged ruleset verified — test broken")
	}
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	nd, err := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err != nil {
		t.Fatalf("reparse: %v", err)
	}
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
	// The unrelated host rule must have survived.
	found := false
	for _, r := range k.rules["filter/FORWARD"] {
		if len(r) >= 2 && r[1] == "docker0" {
			found = true
		}
	}
	if !found {
		t.Fatal("repair deleted an unrelated host rule")
	}
}

func TestRepairIsOneAtomicTransactionPerTable(t *testing.T) {
	// The old repair inserted/deleted rule-by-rule (a bypass window and a
	// line-number race); the rebuilt chain must now land in a single restore
	// commit per table, with the final state verified.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	fw := rules["filter/FORWARD"]
	drop := fw[1]
	fw = append(append(fw[:1:1], fw[2:]...), drop) // misorder: drop at the end
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	if k.restores != 1 {
		t.Fatalf("want exactly one restore transaction, got %d", k.restores)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestRepairPreservesStricterForeignRulesAbove(t *testing.T) {
	// An operator's stricter veth DROP above the block must stay ABOVE vmd's
	// broad ACCEPT through a repair — demoting it would shadow it into a no-op.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	strict := []string{"-i", "veth+", "-p", "tcp", "--dport", "22", "-j", "DROP"}
	fw := rules["filter/FORWARD"]
	fw[2], fw[3] = fw[3], fw[2] // force a repair via misordered clamp
	rules["filter/FORWARD"] = append([][]string{strict}, fw...)

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	got := k.rules["filter/FORWARD"]
	strictIdx, acceptIdx := -1, -1
	for i, r := range got {
		if ruleEqual(r, strict) {
			strictIdx = i
		}
		if acceptIdx == -1 && ruleEqual(r, marked("-i", "veth+", "-o", "eth0", "-j", "ACCEPT")) {
			acceptIdx = i
		}
	}
	if strictIdx == -1 {
		t.Fatal("stricter foreign DROP deleted by repair")
	}
	if strictIdx > acceptIdx {
		t.Fatalf("stricter foreign DROP demoted below the ACCEPT (%d > %d)", strictIdx, acceptIdx)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestRepairRefusesAmbiguousForeignRuleAbove(t *testing.T) {
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	fw := rules["filter/FORWARD"]
	fw[2], fw[3] = fw[3], fw[2] // needs repair
	rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "OPERATOR_CHAIN"}}, fw...)

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err == nil {
		t.Fatal("repair must refuse to reorder past an ambiguous foreign jump")
	}
	if k.restores != 0 {
		t.Fatalf("refusal must not mutate, got %d restores", k.restores)
	}
}

func TestVerifyHeadGuard(t *testing.T) {
	spec := testSpec(true)

	t.Run("foreign veth accept above the block", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "ACCEPT"}}, fw...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("foreign catch-all between jump and drop", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		withGap := append([][]string{fw[0], {"-j", "ACCEPT"}}, fw[1:]...)
		rules["filter/FORWARD"] = withGap
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("stricter veth DROP above the block is fine", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-p", "tcp", "--dport", "22", "-j", "DROP"}}, fw...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
			t.Fatalf("stricter foreign DROP flagged: %s", class)
		}
	})
	t.Run("ambiguous veth jump above the block fails distinctly", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "OPERATOR_CHAIN"}}, fw...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded-ambiguous" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("observer rule above the block is fine", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "LOG", "--log-prefix", "fw:"}}, fw...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
			t.Fatalf("non-terminal observer above the block flagged: %s", class)
		}
	})
	t.Run("foreign docker rule above the block is fine", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "docker0", "-j", "ACCEPT"}}, fw...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
			t.Fatalf("explicit non-veth interface flagged: %s", class)
		}
	})
	t.Run("repair converges a preceded chain", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "ACCEPT"}}, fw...)
		k := &fakeKernel{rules: rules, chains: chains}
		defer k.install(t)()
		d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
		if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
			t.Fatalf("repair: %v", err)
		}
		nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
		if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
			t.Fatalf("post-repair verify failed: %s %s", class, detail)
		}
	})
	t.Run("non-owner has no head guard", func(t *testing.T) {
		unowned := testSpec(false)
		rules, chains := specKernel(unowned, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "SOME_DAEMON_CHAIN"}}, fw...)
		d, err := parseIPTablesSave(renderDump(rules, chains))
		if err != nil {
			t.Fatalf("parse: %v", err)
		}
		if ok, class, _ := verifyHostFirewall(d, unowned); !ok {
			t.Fatalf("non-owner flagged a daemon rule above its block: %s", class)
		}
	})
}

func TestSpecDeduplicatesBlockedPorts(t *testing.T) {
	// 853 configured AND implied by the DNS redirect must yield one rule pair;
	// the installer's AppendUnique collapses duplicates, so a spec keeping
	// them could never verify post-install.
	spec := hostFWSpecFor("eth0", 0, 0, 5353, "", 0, []uint16{853, 25, 25}, true)
	drops := spec.ownedChains["filter/"+portDropChain]
	if len(drops) != 4 { // {853,25} × {tcp,udp}
		t.Fatalf("want 4 deduped drops, got %d: %v", len(drops), drops)
	}
	if !ruleEqual(drops[0].args, []string{"-p", "tcp", "--dport", "853", "-j", "DROP"}) {
		t.Fatalf("first-occurrence order not preserved: %v", drops[0].args)
	}
}

func TestCanonicalRuleMissingOperandIsMismatchNotPanic(t *testing.T) {
	for _, args := range [][]string{{"-i"}, {"--dport"}, {"--tcp-flags", "SYN,RST"}, {"-d"}} {
		if _, ok := canonicalRule(args); ok {
			t.Fatalf("truncated rule %v canonicalized", args)
		}
	}
}

func TestNonOwnerNeverRunsRepair(t *testing.T) {
	// Template-builder shape: post-install verification failure must not
	// mutate shared-chain ordering (its partial spec omits the daemon's
	// jumps) — it logs and proceeds.
	origLock := hostFirewallLockPath
	hostFirewallLockPath = t.TempDir() + "/hostfw.lock" // unprivileged runners cannot open /run
	defer func() { hostFirewallLockPath = origLock }()
	unowned := testSpec(false)
	rules, chains := specKernel(unowned, nil)
	fw := rules["filter/FORWARD"]
	fw[0], fw[1] = fw[1], fw[0] // misorder its own rules
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	origInstall := installHostFirewallFn
	installHostFirewallFn = func(string, uint16, uint16, uint16, string, uint16, []uint16, bool, zerolog.Logger) error { return nil }
	defer func() { installHostFirewallFn = origInstall }()
	origRestore := restoreIPTables
	restoreIPTables = func(context.Context, string) error {
		t.Fatal("non-owner mutated shared-chain ordering")
		return nil
	}
	defer func() { restoreIPTables = origRestore }()

	iface, hp, tp, dp, sd, sp, bp := testSpecParams()
	if err := ensureHostFirewall(context.Background(), iface, hp, tp, dp, sd, sp, bp, false, zerolog.Nop()); err != nil {
		t.Fatalf("non-owner ensure must proceed without repair: %v", err)
	}
}

func TestNormalizeRoundTripShapes(t *testing.T) {
	spec := testSpec(true)
	roundTrip := func(key string, w fwRule) {
		line := "-A X " + strings.Join(saveForm(w.args), " ")
		tokens, err := splitRuleTokens(line)
		if err != nil {
			t.Fatalf("%s rule line unparseable: %v", key, err)
		}
		if !ruleEqual(w.args, tokens[2:]) {
			t.Fatalf("%s rule does not round-trip: %v vs %v", key, w.args, tokens[2:])
		}
	}
	for key, want := range spec.sharedOrdered {
		for _, w := range want {
			roundTrip(key, w)
		}
	}
	for key, want := range spec.ownedChains {
		for _, w := range want {
			roundTrip(key, w)
		}
	}
}

func FuzzParseIPTablesSave(f *testing.F) {
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	f.Add(renderDump(rules, chains))
	f.Add("*filter\n:FORWARD ACCEPT [0:0]\n-A FORWARD -i veth+ -j DROP\nCOMMIT\n")
	f.Add("")
	f.Add("*filter\n-A FORWARD -i\nCOMMIT\n") // truncated operand — must not panic
	f.Add("*filter\n:FORWARD ACCEPT [0:0]\n-A FORWARD -i veth+ -m comment --comment \"a -j DROP b\" -j ACCEPT\nCOMMIT\n")
	f.Fuzz(func(t *testing.T, in string) {
		d, err := parseIPTablesSave(in)
		if err != nil {
			return
		}
		// Whatever parsed must never verify as intact unless it genuinely
		// contains every spec rule — spot-check with the strictest chain.
		ok, _, _ := verifyHostFirewall(d, spec)
		if ok {
			// The fuzzer found an input that verifies: it must actually
			// contain the udp drop in FORWARD.
			found := false
			for _, r := range d.rules["filter/FORWARD"] {
				if ruleEqual(r, marked("-i", "veth+", "-p", "udp", "--dport", "443", "-j", "DROP")) {
					found = true
				}
			}
			if !found {
				t.Fatalf("verified-intact input lacks the udp drop: %q", in)
			}
		}
	})
}

var _ = zerolog.Nop

func TestForeignGotoIsAmbiguous(t *testing.T) {
	// -g/--goto is control flow without -j; it must never read as inert.
	for _, tokens := range [][]string{
		{"-i", "veth+", "-g", "OPERATOR_CHAIN"},
		{"-i", "veth+", "--goto", "OPERATOR_CHAIN"},
	} {
		if got := foreignDisposition(tokens); got != "ambiguous" {
			t.Fatalf("%v disposition = %s, want ambiguous", tokens, got)
		}
	}
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	fw := rules["filter/FORWARD"]
	rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-g", "OPERATOR_CHAIN"}}, fw...)
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded-ambiguous" {
		t.Fatalf("ok=%v class=%s", ok, class)
	}
}

func TestRepairPreservesInterleavedStrictRule(t *testing.T) {
	// A restrictive DROP interleaved BETWEEN vmd rules (not just above the
	// block) must stay above the rebuilt ACCEPT — demoting it would silently
	// disable an operator rule.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	strict := []string{"-i", "veth+", "-p", "tcp", "--dport", "22", "-j", "DROP"}
	fw := rules["filter/FORWARD"]
	// Interleave the strict rule between clamp and the accepts, and misorder
	// the clamp to force a repair.
	interleaved := append([][]string{}, fw[0], fw[1], strict, fw[3], fw[4], fw[2])
	rules["filter/FORWARD"] = interleaved

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	got := k.rules["filter/FORWARD"]
	strictIdx, acceptIdx := -1, -1
	for i, r := range got {
		if ruleEqual(r, strict) {
			strictIdx = i
		}
		if acceptIdx == -1 && ruleEqual(r, marked("-i", "veth+", "-o", "eth0", "-j", "ACCEPT")) {
			acceptIdx = i
		}
	}
	if strictIdx == -1 || strictIdx > acceptIdx {
		t.Fatalf("interleaved strict DROP not preserved above the ACCEPT (strict=%d accept=%d)", strictIdx, acceptIdx)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestLockHostFirewallSerializes(t *testing.T) {
	orig := hostFirewallLockPath
	hostFirewallLockPath = t.TempDir() + "/hostfw.lock"
	defer func() { hostFirewallLockPath = orig }()

	unlock, waited, err := lockHostFirewall(context.Background())
	if err != nil {
		t.Fatalf("lock: %v", err)
	}
	if waited {
		t.Fatal("uncontended acquire reported waited")
	}
	acquired := make(chan struct{})
	go func() {
		u2, waited2, err := lockHostFirewall(context.Background())
		if err != nil {
			t.Errorf("second lock: %v", err)
			close(acquired)
			return
		}
		if !waited2 {
			t.Errorf("contended acquire did not report waited")
		}
		close(acquired)
		u2()
	}()
	select {
	case <-acquired:
		t.Fatal("second lock acquired while held")
	case <-time.After(100 * time.Millisecond):
	}
	unlock()
	select {
	case <-acquired:
	case <-time.After(2 * time.Second):
		t.Fatal("second lock never acquired after release")
	}
}

func TestLockHostFirewallHonorsContext(t *testing.T) {
	orig := hostFirewallLockPath
	hostFirewallLockPath = t.TempDir() + "/hostfw.lock"
	defer func() { hostFirewallLockPath = orig }()

	unlock, _, err := lockHostFirewall(context.Background())
	if err != nil {
		t.Fatalf("lock: %v", err)
	}
	defer unlock()

	ctx, cancel := context.WithTimeout(context.Background(), 200*time.Millisecond)
	defer cancel()
	if _, _, err := lockHostFirewall(ctx); err == nil {
		t.Fatal("contended lock with cancelled context must fail, not block")
	}
}

func TestRepairNeverNamesForeignRules(t *testing.T) {
	// The transaction may only reference vmd's own rules: no flushes, and
	// every -D/-I/-A rulespec must match the spec — so a foreign rule added
	// at ANY moment (even between dump and restore) cannot be deleted.
	spec := testSpec(true)
	rules, chains := specKernel(spec, map[string][][]string{
		"filter/FORWARD": {{"-i", "docker0", "-j", "ACCEPT"}},
	})
	fw := rules["filter/FORWARD"]
	fw[2], fw[3] = fw[3], fw[2] // force repair
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	specRules := map[string]bool{}
	for _, want := range spec.sharedOrdered {
		for _, w := range want {
			c, _ := canonicalRule(w.args)
			specRules[strings.Join(c, "|")] = true
		}
	}
	for _, input := range k.inputs {
		for _, line := range strings.Split(input, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || line == "COMMIT" || strings.HasPrefix(line, "*") {
				continue
			}
			if strings.HasPrefix(line, "-F ") {
				t.Fatalf("repair flushed a shared chain: %q", line)
			}
			fields := strings.Fields(line)
			args := fields[2:]
			if fields[0] == "-I" {
				args = fields[3:]
			}
			c, ok := canonicalRule(args)
			if !ok || !specRules[strings.Join(c, "|")] {
				t.Fatalf("repair referenced a non-vmd rule: %q", line)
			}
		}
	}
	// And the foreign rule is still present.
	found := false
	for _, r := range k.rules["filter/FORWARD"] {
		if len(r) >= 2 && r[1] == "docker0" {
			found = true
		}
	}
	if !found {
		t.Fatal("foreign rule lost")
	}
}

func TestRepairRefusesStrictForeignAbovePreroutingRedirect(t *testing.T) {
	// PREROUTING redirects are terminal: head-inserting ours would demote a
	// foreign DROP that ran before a redirect to below it, silently disabling
	// the operator rule. Repair must refuse without mutation.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	pre := rules["nat/PREROUTING"]
	strict := []string{"-i", "veth+", "-p", "tcp", "--dport", "80", "-j", "DROP"}
	// Strict foreign above the redirects, plus a misorder to force repair.
	pre[1], pre[2] = pre[2], pre[1]
	rules["nat/PREROUTING"] = append([][]string{strict}, pre...)

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err == nil {
		t.Fatal("repair must refuse to demote a stricter foreign rule below a terminal redirect")
	}
	if k.restores != 0 {
		t.Fatalf("refusal must not mutate, got %d restores", k.restores)
	}
}

func TestStaleManagedRedirectIsReconciledNotFatal(t *testing.T) {
	// A supported config change (secretsproxy address, proxy port) leaves the
	// previous generation's redirect installed. It must classify as a
	// repairable stale-managed mismatch — not preceded-ambiguous — and repair
	// must delete it while foreign redirects stay untouched.
	spec := testSpec(true)
	oldSecrets := marked("-i", "veth+", "-p", "tcp", "-d", "169.254.0.99", "--dport", "9443", "-j", "REDIRECT", "--to-port", "9443")
	oldTLS := marked("-i", "veth+", "-p", "tcp", "--dport", "443", "-j", "REDIRECT", "--to-port", "9999")
	rules, chains := specKernel(spec, nil)
	rules["nat/PREROUTING"] = append([][]string{oldSecrets, oldTLS}, rules["nat/PREROUTING"]...)

	if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "stale-managed" {
		t.Fatalf("ok=%v class=%s, want stale-managed", ok, class)
	}

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
	for _, r := range k.rules["nat/PREROUTING"] {
		if ruleEqual(r, oldSecrets) || ruleEqual(r, oldTLS) {
			t.Fatalf("stale managed redirect survived reconciliation: %v", r)
		}
	}
}

func TestOperatorRulesNeverReadAsStale(t *testing.T) {
	// staleManagedRule is keyed on the explicit ownership marker, never on
	// shape. Shape-based retirement exists only for the exact pre-marker vmd
	// redirect templates (staleVMDRule → legacyManagedRedirect below).
	want := testSpec(true).sharedOrdered["nat/PREROUTING"]
	for _, tokens := range [][]string{
		{"-i", "veth+", "-p", "tcp", "--dport", "80", "-j", "REDIRECT", "--to-port", "8888"},
		{"-i", "veth+", "-p", "tcp", "--dport", "443", "-j", "REDIRECT", "--to-port", "8443"},
		{"-i", "veth+", "-p", "tcp", "-d", "10.0.0.5", "--dport", "9443", "-j", "REDIRECT", "--to-port", "9443"},
		{"-i", "veth+", "-p", "tcp", "--dport", "8080", "-j", "REDIRECT", "--to-port", "999", "-m", "comment", "--comment", "operator rule"},
		// an operator rule identical to a current vmd rule, minus the marker
		{"-i", "veth+", "-p", "tcp", "--dport", "443", "-j", "REDIRECT", "--to-port", "3129"},
	} {
		if staleManagedRule(tokens, want) {
			t.Fatalf("unmarked redirect misread as marked-stale: %v", tokens)
		}
	}
	// Rules that carry a comment, use another dport, or twin a current rule
	// are NEVER retired by shape — only the bare historical templates are.
	for _, tokens := range [][]string{
		{"-i", "veth+", "-p", "tcp", "--dport", "8080", "-j", "REDIRECT", "--to-port", "999", "-m", "comment", "--comment", "operator rule"},
		{"-i", "veth+", "-p", "tcp", "--dport", "80", "-j", "REDIRECT", "--to-port", "8888", "-m", "comment", "--comment", "operator rule"},
		{"-i", "veth+", "-p", "tcp", "--dport", "8080", "-j", "REDIRECT", "--to-port", "9090"},
		{"-i", "veth+", "-p", "tcp", "-d", "10.0.0.5", "--dport", "9443", "-j", "REDIRECT", "--to-port", "8443"},
		{"-i", "eth0", "-p", "tcp", "--dport", "80", "-j", "REDIRECT", "--to-port", "8888"},
		// twin of the current TLS redirect: tolerated shadow, not stale
		{"-i", "veth+", "-p", "tcp", "--dport", "443", "-j", "REDIRECT", "--to-port", "3129"},
	} {
		if staleVMDRule("nat/PREROUTING", tokens, want) {
			t.Fatalf("non-template redirect retired by shape: %v", tokens)
		}
	}
}

func TestLegacyPreMarkerRedirectsReconciled(t *testing.T) {
	// A host upgraded from the pre-marker installer keeps its old unmarked
	// redirects as tolerated twins — until the config changes. Then the
	// legacy rule would keep redirecting live sandbox traffic to a dead port,
	// so the exact historical templates are retired like marked stale rules.
	spec := testSpec(true)
	legacyHTTP := []string{"-i", "veth+", "-p", "tcp", "--dport", "80", "-j", "REDIRECT", "--to-port", "9999"}
	legacySecrets := []string{"-i", "veth+", "-p", "tcp", "-d", "169.254.9.9", "--dport", "8443", "-j", "REDIRECT", "--to-port", "8443"}

	rules, chains := specKernel(spec, nil)
	rules["nat/PREROUTING"] = append([][]string{legacyHTTP, legacySecrets}, rules["nat/PREROUTING"]...)
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "stale-managed" {
		t.Fatalf("ok=%v class=%s, want stale-managed", ok, class)
	}

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
	for _, r := range k.rules["nat/PREROUTING"] {
		if ruleEqual(r, legacyHTTP) || ruleEqual(r, legacySecrets) {
			t.Fatalf("legacy pre-marker redirect survived reconciliation: %v", r)
		}
	}

	// While the config still matches, the legacy rule is a twin: tolerated,
	// verification intact, nothing to repair.
	twin := []string{"-i", "veth+", "-p", "tcp", "--dport", "80", "-j", "REDIRECT", "--to-port", "3128"}
	rules, chains = specKernel(spec, nil)
	rules["nat/PREROUTING"] = append([][]string{twin}, rules["nat/PREROUTING"]...)
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
		t.Fatalf("current-config legacy twin flagged: %s", class)
	}
}

func TestUnmarkedTwinsToleratedNeverDeleted(t *testing.T) {
	// A rule equal to a current vmd rule modulo the marker is either the
	// pre-marker generation or an operator rule that is semantically
	// identical — ownership is unknowable, so it is tolerated as a shadow and
	// NEVER deleted.
	spec := testSpec(true)
	want := spec.sharedOrdered["filter/FORWARD"]
	unmarkedDrop := []string{"-i", "veth+", "-p", "udp", "--dport", "443", "-j", "DROP"}
	if staleManagedRule(unmarkedDrop, want) {
		t.Fatal("unmarked rule must never read as stale (marker-only staleness)")
	}
	if !unmarkedTwin(unmarkedDrop, want) {
		t.Fatal("unmarked exact twin not recognized as tolerated shadow")
	}

	// Twins above the block (incl. a PREROUTING redirect twin) verify intact.
	rules, chains := specKernel(spec, nil)
	rules["filter/FORWARD"] = append([][]string{unmarkedDrop}, rules["filter/FORWARD"]...)
	unmarkedTLS := []string{"-i", "veth+", "-p", "tcp", "--dport", "443", "-j", "REDIRECT", "--to-port", "3129"}
	rules["nat/PREROUTING"] = append([][]string{unmarkedTLS}, rules["nat/PREROUTING"]...)
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
		t.Fatalf("tolerated twins flagged: %s", class)
	}

	// A repair forced by an unrelated mismatch must not delete the twins.
	fw := rules["filter/FORWARD"]
	fw[3], fw[4] = fw[4], fw[3] // misorder clamp vs accept
	rules["filter/FORWARD"] = fw
	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	foundDrop, foundTLS := false, false
	for _, r := range k.rules["filter/FORWARD"] {
		if ruleEqual(r, unmarkedDrop) {
			foundDrop = true
		}
	}
	for _, r := range k.rules["nat/PREROUTING"] {
		if ruleEqual(r, unmarkedTLS) {
			foundTLS = true
		}
	}
	if !foundDrop || !foundTLS {
		t.Fatalf("repair deleted a tolerated twin (drop=%v tls=%v)", foundDrop, foundTLS)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestRepairRefusesToStarveObserverAbovePreroutingRedirect(t *testing.T) {
	// An observer above a vmd redirect is tolerated by verification, but
	// head-inserting the terminal redirects during a repair would starve it
	// of the traffic it currently sees — refuse, like the strict case.
	spec := testSpec(true)
	stale := marked("-i", "veth+", "-p", "tcp", "--dport", "443", "-j", "REDIRECT", "--to-port", "9999")
	observer := []string{"-i", "veth+", "-p", "tcp", "--dport", "80", "-j", "LOG", "--log-prefix", "http:"}

	rules, chains := specKernel(spec, nil)
	rules["nat/PREROUTING"] = append([][]string{observer, stale}, rules["nat/PREROUTING"]...)
	d, _ := parseIPTablesSave(renderDump(rules, chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err == nil {
		t.Fatal("repair reordered past an observer above a vmd redirect")
	}

	// The same observer BELOW every vmd redirect loses nothing: repair runs.
	rules, chains = specKernel(spec, nil)
	rules["nat/PREROUTING"] = append(rules["nat/PREROUTING"], stale, observer)
	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ = parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair refused with observer below the redirects: %v", err)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestRepairRefusesToStarveObserverAboveForwardDrops(t *testing.T) {
	// Same starvation rule in filter/FORWARD: an observer above the terminal
	// drops loses the blocked traffic it currently logs if the drops are
	// head-inserted above it. Below the drops it loses nothing.
	spec := testSpec(true)
	observer := []string{"-i", "veth+", "-j", "NFLOG", "--nflog-group", "7"}

	rules, chains := specKernel(spec, nil)
	fw := rules["filter/FORWARD"]
	fw[3], fw[4] = fw[4], fw[3] // misorder clamp vs accept to force repair
	rules["filter/FORWARD"] = append([][]string{observer}, fw...)
	d, _ := parseIPTablesSave(renderDump(rules, chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err == nil {
		t.Fatal("repair reordered past an observer above the FORWARD drops")
	}

	// Between the last drop and the clamp: nothing terminal crosses it.
	rules, chains = specKernel(spec, nil)
	fw = rules["filter/FORWARD"]
	fw[3], fw[4] = fw[4], fw[3]
	rules["filter/FORWARD"] = append(fw[:2:2], append([][]string{observer}, fw[2:]...)...)
	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ = parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair refused with observer below the drops: %v", err)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestRepairRefusesToDemoteRejectBelowForwardDrops(t *testing.T) {
	// A foreign REJECT above the drops answers traffic a vmd DROP would
	// silence: demoting it changes client-visible behavior, so repair
	// refuses. A foreign DROP is silent either way and may move (covered by
	// TestRepairPreservesStricterForeignRulesAbove).
	spec := testSpec(true)
	reject := []string{"-i", "veth+", "-p", "udp", "--dport", "443", "-j", "REJECT"}

	rules, chains := specKernel(spec, nil)
	fw := rules["filter/FORWARD"]
	fw[3], fw[4] = fw[4], fw[3] // misorder clamp vs accept to force repair
	rules["filter/FORWARD"] = append([][]string{reject}, fw...)
	d, _ := parseIPTablesSave(renderDump(rules, chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err == nil {
		t.Fatal("repair demoted a foreign REJECT below the FORWARD drops")
	}

	// Below the terminal drops it already answers nothing ours silences:
	// repair proceeds.
	rules, chains = specKernel(spec, nil)
	fw = rules["filter/FORWARD"]
	fw[3], fw[4] = fw[4], fw[3]
	rules["filter/FORWARD"] = append(fw[:2:2], append([][]string{reject}, fw[2:]...)...)
	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ = parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair refused with REJECT below the drops: %v", err)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestRepairRefusesToPromoteTerminalNATBelowMasquerade(t *testing.T) {
	spec := testSpec(true)
	masq := marked("-s", "10.11.0.0/16", "-o", "eth0", "-j", "MASQUERADE")
	snat := []string{"-s", "10.11.0.0/16", "-o", "eth0", "-j", "SNAT", "--to-source", "192.0.2.7"}

	// Foreign terminal NAT below our effective MASQUERADE: re-appending ours
	// would promote it into traffic ours handled first — refuse.
	rules, chains := specKernel(spec, nil)
	rules["nat/POSTROUTING"] = append(rules["nat/POSTROUTING"], snat, masq) // dup forces repair
	d, _ := parseIPTablesSave(renderDump(rules, chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err == nil {
		t.Fatal("repair promoted a foreign terminal NAT rule past the MASQUERADE")
	}

	// The same rule ABOVE ours is already effective; repair keeps that
	// relative order and proceeds.
	rules, chains = specKernel(spec, nil)
	rules["nat/POSTROUTING"] = append([][]string{snat}, append(rules["nat/POSTROUTING"], masq)...)
	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ = parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair refused with foreign NAT already above: %v", err)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}

	// An observer below ours cannot change a verdict: repair proceeds.
	rules, chains = specKernel(spec, nil)
	rules["nat/POSTROUTING"] = append(rules["nat/POSTROUTING"], []string{"-s", "10.11.0.0/16", "-j", "LOG"}, masq)
	k2 := &fakeKernel{rules: rules, chains: chains}
	defer k2.install(t)()
	d, _ = parseIPTablesSave(renderDump(k2.rules, k2.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair refused with observer below: %v", err)
	}
}

func TestConcurrentWriterDuringRepairDetected(t *testing.T) {
	// A NON-cooperating writer inserting between the repair's snapshot dump
	// and the next verification dump must fail startup: verification alone
	// tolerates the rule (an observer), but the absolute-head inserts may
	// have changed its effective position — only the prediction compare can
	// tell.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	masq := marked("-s", "10.11.0.0/16", "-o", "eth0", "-j", "MASQUERADE")
	rules["nat/POSTROUTING"] = append(rules["nat/POSTROUTING"], masq) // duplicate forces repair

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	fakeRestore := restoreIPTables
	restoreIPTables = func(ctx context.Context, input string) error {
		if err := fakeRestore(ctx, input); err != nil {
			return err
		}
		if strings.HasPrefix(input, "*nat") {
			k.rules["nat/POSTROUTING"] = append([][]string{{"-s", "10.11.0.0/16", "-j", "LOG"}}, k.rules["nat/POSTROUTING"]...)
		}
		return nil
	}
	defer func() { restoreIPTables = fakeRestore }()
	origInstall := installHostFirewallFn
	installHostFirewallFn = func(string, uint16, uint16, uint16, string, uint16, []uint16, bool, zerolog.Logger) error { return nil }
	defer func() { installHostFirewallFn = origInstall }()
	origLock := hostFirewallLockPath
	hostFirewallLockPath = t.TempDir() + "/hostfw.lock"
	defer func() { hostFirewallLockPath = origLock }()

	iface, hp, tp, dp, sd, sp, bp := testSpecParams()
	err := ensureHostFirewall(context.Background(), iface, hp, tp, dp, sd, sp, bp, true, zerolog.Nop())
	if err == nil || !strings.Contains(err.Error(), "concurrent") {
		t.Fatalf("concurrent writer not detected, got: %v", err)
	}
}

func TestPredictionCompareToleratesUnparseableForeignRules(t *testing.T) {
	// A preserved foreign rule with options outside ruleArity (e.g.
	// -m conntrack) canonicalizes on neither side of the prediction compare —
	// exact token equality must recognize it as unchanged instead of
	// misreporting a non-cooperating writer.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	fw := rules["filter/FORWARD"]
	fw[3], fw[4] = fw[4], fw[3] // misorder clamp vs accept to force repair
	conntrack := []string{"-i", "veth+", "-m", "conntrack", "--ctstate", "INVALID", "-j", "DROP"}
	rules["filter/FORWARD"] = append(fw[:2:2], append([][]string{conntrack}, fw[2:]...)...)

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	origInstall := installHostFirewallFn
	installHostFirewallFn = func(string, uint16, uint16, uint16, string, uint16, []uint16, bool, zerolog.Logger) error { return nil }
	defer func() { installHostFirewallFn = origInstall }()
	origLock := hostFirewallLockPath
	hostFirewallLockPath = t.TempDir() + "/hostfw.lock"
	defer func() { hostFirewallLockPath = origLock }()

	iface, hp, tp, dp, sd, sp, bp := testSpecParams()
	if err := ensureHostFirewall(context.Background(), iface, hp, tp, dp, sd, sp, bp, true, zerolog.Nop()); err != nil {
		t.Fatalf("repair with a preserved unparseable foreign rule failed: %v", err)
	}
	found := false
	for _, r := range k.rules["filter/FORWARD"] {
		if slices.Equal(r, conntrack) {
			found = true
		}
	}
	if !found {
		t.Fatal("unparseable foreign rule not preserved by repair")
	}
}

func TestNonOwnerFastPathOnOwnerConfiguredHost(t *testing.T) {
	// Template-builder alongside a running daemon: the daemon's marked jumps
	// and redirects are absent from the non-owner's partial spec and must
	// read as the owner's rules — NOT stale — so the non-owner fast path
	// succeeds without mutating anything.
	ownerSpec := testSpec(true)
	rules, chains := specKernel(ownerSpec, nil)
	nonOwner := testSpec(false)
	if ok, class := mustVerify(t, renderDump(rules, chains), nonOwner); !ok {
		t.Fatalf("non-owner fast path failed on an owner-configured host: %s", class)
	}
}

func TestQuotedCommentCannotSpoofDisposition(t *testing.T) {
	// A foreign ACCEPT whose comment contains "-j DROP" must still classify
	// as permissive — quote-aware tokenization keeps the comment one token.
	line := `-A FORWARD -i veth+ -m comment --comment "audit -j DROP rule" -j ACCEPT`
	tokens, err := splitRuleTokens(line)
	if err != nil {
		t.Fatalf("split: %v", err)
	}
	if got := foreignDisposition(tokens[2:]); got != "permissive" {
		t.Fatalf("disposition = %s, want permissive", got)
	}
	// And end to end: that rule above the drops must flag, not pass.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	fw := rules["filter/FORWARD"]
	rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-m", "comment", "--comment", "audit -j DROP rule", "-j", "ACCEPT"}}, fw...)
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded" {
		t.Fatalf("ok=%v class=%s, want preceded", ok, class)
	}
	if _, err := splitRuleTokens(`-A FORWARD -m comment --comment "unbalanced`); err == nil {
		t.Fatal("unbalanced quote must error")
	}
}

func TestRepairKeepsClampAheadOfForeignAccept(t *testing.T) {
	// A tolerated foreign veth ACCEPT below the drops must not end up ahead
	// of the MSS clamp after a repair — unclamped sandbox SYNs would leave
	// FORWARD before TCPMSS runs.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	foreignAccept := []string{"-i", "veth+", "-p", "tcp", "--dport", "8443", "-j", "ACCEPT"}
	fw := rules["filter/FORWARD"]
	// Foreign accept after the drops (tolerated), duplicate udp drop at the
	// end to force a repair.
	fw = append(fw[:2:2], append([][]string{foreignAccept}, fw[2:]...)...)
	fw = append(fw, append([]string(nil), fw[1]...))
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	got := k.rules["filter/FORWARD"]
	clampIdx, foreignIdx := -1, -1
	for i, r := range got {
		if ruleEqual(r, marked("-o", "eth0", "-p", "tcp", "--tcp-flags", "SYN,RST", "SYN", "-j", "TCPMSS", "--clamp-mss-to-pmtu")) {
			clampIdx = i
		}
		if ruleEqual(r, foreignAccept) {
			foreignIdx = i
		}
	}
	if clampIdx == -1 || foreignIdx == -1 || clampIdx > foreignIdx {
		t.Fatalf("clamp not ahead of foreign accept after repair (clamp=%d foreign=%d)", clampIdx, foreignIdx)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestVerifyGuardsClampFromPrecedingTerminalAccept(t *testing.T) {
	spec := testSpec(true)

	t.Run("terminal accept between drops and clamp flags", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		foreign := []string{"-i", "veth+", "-p", "tcp", "--dport", "8443", "-j", "ACCEPT"}
		rules["filter/FORWARD"] = append(fw[:2:2], append([][]string{foreign}, fw[2:]...)...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded" {
			t.Fatalf("ok=%v class=%s, want preceded", ok, class)
		}
	})
	t.Run("observer between drops and clamp tolerated", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		logRule := []string{"-i", "veth+", "-j", "LOG"}
		rules["filter/FORWARD"] = append(fw[:2:2], append([][]string{logRule}, fw[2:]...)...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
			t.Fatalf("non-terminal observer past the drops flagged: %s", class)
		}
	})
	// Unknown control flow between the drops and the clamp can reach an
	// ACCEPT (or RETURN into an ACCEPT policy) before the clamp runs, so it
	// must fail exactly like ambiguity above the drops.
	t.Run("ambiguous control flow between drops and clamp fails", func(t *testing.T) {
		for _, tc := range []struct {
			name string
			rule []string
		}{
			{"operator chain jump", []string{"-i", "veth+", "-j", "OPERATOR_CHAIN"}},
			{"return", []string{"-i", "veth+", "-j", "RETURN"}},
			{"goto", []string{"-i", "veth+", "-g", "OPERATOR_CHAIN"}},
		} {
			rules, chains := specKernel(spec, nil)
			fw := rules["filter/FORWARD"]
			rules["filter/FORWARD"] = append(fw[:2:2], append([][]string{tc.rule}, fw[2:]...)...)
			if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded-ambiguous" {
				t.Fatalf("%s: ok=%v class=%s, want preceded-ambiguous", tc.name, ok, class)
			}
		}
	})
	t.Run("repair converges the flagged accept", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		foreign := []string{"-i", "veth+", "-p", "tcp", "--dport", "8443", "-j", "ACCEPT"}
		rules["filter/FORWARD"] = append(fw[:2:2], append([][]string{foreign}, fw[2:]...)...)
		k := &fakeKernel{rules: rules, chains: chains}
		defer k.install(t)()
		d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
		if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
			t.Fatalf("repair: %v", err)
		}
		nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
		if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
			t.Fatalf("post-repair verify failed: %s %s", class, detail)
		}
	})
}

func TestUnmarkedAcceptTwinAboveDropsFlags(t *testing.T) {
	// An ACCEPT twin is terminal: above the drops it is a bypass exactly like
	// a foreign ACCEPT — it must flag, repair must converge by heading the
	// security block above it, and the twin itself must survive.
	spec := testSpec(true)
	twin := []string{"-i", "veth+", "-o", "eth0", "-j", "ACCEPT"} // unmarked
	rules, chains := specKernel(spec, nil)
	rules["filter/FORWARD"] = append([][]string{twin}, rules["filter/FORWARD"]...)

	if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded" {
		t.Fatalf("ok=%v class=%s, want preceded", ok, class)
	}
	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if _, err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
	found := false
	for _, r := range k.rules["filter/FORWARD"] {
		if ruleEqual(r, twin) {
			found = true
		}
	}
	if !found {
		t.Fatal("accept twin deleted — twins must survive repair")
	}
}

func TestPostLockReverifySkipsInstall(t *testing.T) {
	// Writers queued on the lock must re-verify after acquiring it: if the
	// first holder converged the ruleset, the waiters skip the installer.
	origLock := hostFirewallLockPath
	hostFirewallLockPath = t.TempDir() + "/hostfw.lock"
	defer func() { hostFirewallLockPath = origLock }()

	spec := testSpec(true)
	good, chains := specKernel(spec, nil)
	goodDump := renderDump(good, chains)
	bad, _ := specKernel(spec, nil)
	bad["filter/FORWARD"] = bad["filter/FORWARD"][1:] // missing rule
	badDump := renderDump(bad, chains)

	calls := 0
	origDump := dumpIPTables
	dumpIPTables = func(context.Context) (string, error) {
		calls++
		if calls == 1 {
			return badDump, nil // pre-lock fast path: mismatch
		}
		return goodDump, nil // post-lock: another writer converged it
	}
	defer func() { dumpIPTables = origDump }()
	origInstall := installHostFirewallFn
	installHostFirewallFn = func(string, uint16, uint16, uint16, string, uint16, []uint16, bool, zerolog.Logger) error {
		t.Fatal("installer ran despite post-lock convergence")
		return nil
	}
	defer func() { installHostFirewallFn = origInstall }()

	// Contend the lock so ensure actually waits — the re-verify is reserved
	// for waiters; an uncontended acquire goes straight to the installer.
	hold, _, err := lockHostFirewall(context.Background())
	if err != nil {
		t.Fatalf("hold lock: %v", err)
	}
	done := make(chan error, 1)
	go func() {
		iface, hp, tp, dp, sd, sp, bp := testSpecParams()
		done <- ensureHostFirewall(context.Background(), iface, hp, tp, dp, sd, sp, bp, true, zerolog.Nop())
	}()
	time.Sleep(300 * time.Millisecond) // let ensure hit the contended lock
	hold()
	if err := <-done; err != nil {
		t.Fatalf("ensure: %v", err)
	}
}

func TestInvalidSecretsProxyDstFailsBeforeFastPath(t *testing.T) {
	// A requested secrets redirect with an invalid destination must fail
	// startup — never silently drop out of the spec and verify intact.
	origDump := dumpIPTables
	dumpIPTables = func(context.Context) (string, error) {
		t.Fatal("validation must fail before any dump")
		return "", nil
	}
	defer func() { dumpIPTables = origDump }()
	iface, hp, tp, dp, _, _, bp := testSpecParams()
	for _, dst := range []string{"", "not-an-ip", "fe80::1"} {
		if err := ensureHostFirewall(context.Background(), iface, hp, tp, dp, dst, 9443, bp, true, zerolog.Nop()); err == nil {
			t.Fatalf("dst %q accepted", dst)
		}
	}
}
