package network

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/rs/zerolog"
)

func testSpecParams() (string, uint16, uint16, uint16, string, uint16, []uint16) {
	return "eth0", 3128, 3129, 5353, "169.254.0.21", 9443, []uint16{25, 465}
}

func testSpec(owned bool) hostFWSpec {
	iface, hp, tp, dp, sd, sp, bp := testSpecParams()
	return hostFWSpecFor(iface, hp, tp, dp, sd, sp, bp, owned)
}

// renderDump renders a fake kernel ruleset as iptables-save output, in the
// canonical form iptables-save uses (-m tcp/udp inserted, --to-ports, /32).
func renderDump(rules map[string][][]string, chains []string) string {
	var b strings.Builder
	for _, table := range []string{"filter", "nat"} {
		fmt.Fprintf(&b, "# Generated by test\n*%s\n", table)
		builtins := map[string][]string{
			"filter": {"INPUT", "FORWARD", "OUTPUT"},
			"nat":    {"PREROUTING", "INPUT", "OUTPUT", "POSTROUTING"},
		}[table]
		for _, c := range builtins {
			fmt.Fprintf(&b, ":%s ACCEPT [0:0]\n", c)
		}
		for _, tc := range chains {
			tab, chain, _ := strings.Cut(tc, "/")
			if tab == table {
				fmt.Fprintf(&b, ":%s - [0:0]\n", chain)
			}
		}
		for key, rs := range rules {
			tab, chain, _ := strings.Cut(key, "/")
			if tab != table {
				continue
			}
			for _, r := range rs {
				fmt.Fprintf(&b, "-A %s %s\n", chain, strings.Join(saveForm(r), " "))
			}
		}
		b.WriteString("COMMIT\n")
	}
	return b.String()
}

// saveForm converts installer-arg form into iptables-save output form.
func saveForm(args []string) []string {
	out := make([]string, 0, len(args)+2)
	for i := 0; i < len(args); i++ {
		a := args[i]
		out = append(out, a)
		if a == "-p" && i+1 < len(args) && (args[i+1] == "tcp" || args[i+1] == "udp") {
			out = append(out, args[i+1], "-m", args[i+1])
			i++
			continue
		}
		if a == "--to-port" {
			out[len(out)-1] = "--to-ports"
		}
		if a == "--comment" && i+1 < len(args) {
			out = append(out, "\""+args[i+1]+"\"")
			i++
			continue
		}
		if a == "-d" && i+1 < len(args) && !strings.Contains(args[i+1], "/") {
			out = append(out, args[i+1]+"/32")
			i++
		}
	}
	return out
}

// specKernel builds the fake kernel state exactly matching a spec, plus any
// unrelated host rules passed in.
func specKernel(spec hostFWSpec, extraShared map[string][][]string) (map[string][][]string, []string) {
	rules := map[string][][]string{}
	var chains []string
	for key, want := range spec.sharedOrdered {
		for _, w := range want {
			rules[key] = append(rules[key], append([]string(nil), w.args...))
		}
		for _, e := range extraShared[key] {
			rules[key] = append(rules[key], e)
		}
	}
	for key, want := range spec.ownedChains {
		chains = append(chains, key)
		for _, w := range want {
			rules[key] = append(rules[key], append([]string(nil), w.args...))
		}
	}
	return rules, chains
}

func mustVerify(t *testing.T, dump string, spec hostFWSpec) (bool, string) {
	t.Helper()
	d, err := parseIPTablesSave(dump)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	ok, class, _ := verifyHostFirewall(d, spec)
	return ok, class
}

func TestVerifyIntactAndIgnoresUnrelatedRules(t *testing.T) {
	spec := testSpec(true)
	rules, chains := specKernel(spec, map[string][][]string{
		"filter/FORWARD": {{"-i", "docker0", "-j", "ACCEPT"}},
	})
	// Unrelated rule interleaved: still intact.
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
		t.Fatalf("intact ruleset read as %s", class)
	}
}

func TestVerifyDetectsEveryMismatchClass(t *testing.T) {
	spec := testSpec(true)

	t.Run("missing-rule", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		rules["filter/FORWARD"] = rules["filter/FORWARD"][1:] // drop the port jump
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "missing-rule" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("duplicate-rule", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append(fw, fw[1]) // duplicate the udp drop at the end
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "duplicate-rule" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("misordered", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		// Move the clamp after the broad ACCEPT — the legacy AppendUnique hazard.
		fw[2], fw[3] = fw[3], fw[2]
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "misordered" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("mutated-rule", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		fw[1] = []string{"-i", "veth+", "-p", "udp", "--dport", "444", "-j", "DROP"} // wrong port
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "missing-rule" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("owned-chain-extra-rule", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		key := "filter/" + portDropChain
		rules[key] = append(rules[key], []string{"-p", "tcp", "--dport", "9999", "-j", "DROP"})
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "owned-chain-drift" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("owned-chain-reordered", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		key := "filter/" + portDropChain
		rs := rules[key]
		rs[0], rs[1] = rs[1], rs[0]
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "owned-chain-drift" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("missing-owned-chain", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		if ok, class := mustVerify(t, renderDump(rules, chains[:1]), spec); ok || class != "missing-chain" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
}

func TestVerifyWithoutOwnedChainsIgnoresThem(t *testing.T) {
	// Template-builder shape: manageOwnedChains=false must neither require nor
	// inspect the daemon-owned chains or their jumps.
	spec := testSpec(false)
	if len(spec.ownedChains) != 0 {
		t.Fatalf("unowned spec has owned chains: %v", spec.ownedChains)
	}
	for _, r := range spec.sharedOrdered["filter/FORWARD"] {
		if r.args[len(r.args)-1] == portDropChain {
			t.Fatal("unowned spec includes the port-drop jump")
		}
	}
	rules, chains := specKernel(spec, nil)
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
		t.Fatalf("unowned intact read as %s", class)
	}
}

func TestParseToleratesIncompatibleTableComments(t *testing.T) {
	// iptables-nft-save flags foreign native-nft tables (our host egress-block
	// table) as comment lines; they must parse cleanly, not force a slow path.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	dump := "# Table `sandbox_egress_block' is incompatible, use 'nft' tool.\n" + renderDump(rules, chains)
	if ok, class := mustVerify(t, dump, spec); !ok {
		t.Fatalf("incompatible-table comment broke verification: %s", class)
	}
}

func TestParseRejectsUnknownSyntax(t *testing.T) {
	for _, bad := range []string{
		"*filter\ngarbage line\nCOMMIT\n",
		"-A FORWARD -j ACCEPT\n", // rule before table
		"*filter\n-A\nCOMMIT\n",  // malformed rule
		":FORWARD ACCEPT [0:0]\n",
	} {
		if _, err := parseIPTablesSave(bad); err == nil {
			t.Fatalf("parser accepted %q", bad)
		}
	}
}

// fakeKernel backs the dump/restore seams so the repair path can be
// exercised without iptables; its restore handler implements the -F/-A
// subset atomic repair emits.
type fakeKernel struct {
	rules    map[string][][]string
	chains   []string
	restores int
	inputs   []string
}

func (k *fakeKernel) install(t *testing.T) func() {
	t.Helper()
	origDump, origRestore := dumpIPTables, restoreIPTables
	dumpIPTables = func(context.Context) (string, error) { return renderDump(k.rules, k.chains), nil }
	restoreIPTables = func(_ context.Context, input string) error {
		k.restores++
		k.inputs = append(k.inputs, input)
		table := ""
		for _, line := range strings.Split(input, "\n") {
			line = strings.TrimSpace(line)
			switch {
			case line == "" || line == "COMMIT":
			case strings.HasPrefix(line, "*"):
				table = line[1:]
			case strings.HasPrefix(line, "-F "):
				k.rules[table+"/"+strings.TrimPrefix(line, "-F ")] = nil
			case strings.HasPrefix(line, "-D "):
				fields := strings.Fields(line)
				key := table + "/" + fields[1]
				spec := fields[2:]
				found := false
				for i, r := range k.rules[key] {
					if ruleEqual(spec, r) {
						k.rules[key] = append(k.rules[key][:i:i], k.rules[key][i+1:]...)
						found = true
						break
					}
				}
				if !found {
					return fmt.Errorf("fake kernel: -D no match: %q", line)
				}
			case strings.HasPrefix(line, "-I "):
				fields := strings.Fields(line)
				key := table + "/" + fields[1]
				n, err := strconv.Atoi(fields[2])
				if err != nil || n < 1 || n > len(k.rules[key])+1 {
					return fmt.Errorf("fake kernel: bad -I position: %q", line)
				}
				rule := append([]string(nil), fields[3:]...)
				rs := k.rules[key]
				k.rules[key] = append(rs[:n-1:n-1], append([][]string{rule}, rs[n-1:]...)...)
			case strings.HasPrefix(line, "-A "):
				fields := strings.Fields(line)
				key := table + "/" + fields[1]
				k.rules[key] = append(k.rules[key], fields[2:])
			default:
				return fmt.Errorf("fake kernel: unsupported restore line %q", line)
			}
		}
		return nil
	}
	return func() { dumpIPTables, restoreIPTables = origDump, origRestore }
}

func TestRepairCanonicalizesMisorderAndDuplicates(t *testing.T) {
	spec := testSpec(true)
	rules, chains := specKernel(spec, map[string][][]string{
		"filter/FORWARD": {{"-i", "docker0", "-j", "ACCEPT"}},
	})
	// Sabotage FORWARD: move clamp after ACCEPTs and duplicate the udp drop.
	fw := rules["filter/FORWARD"]
	clamp := fw[2]
	fw = append(fw[:2], fw[3:]...)
	fw = append(fw, clamp, append([]string(nil), fw[1]...))
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()

	d, err := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if ok, _, _ := verifyHostFirewall(d, spec); ok {
		t.Fatal("sabotaged ruleset verified — test broken")
	}
	if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	nd, err := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err != nil {
		t.Fatalf("reparse: %v", err)
	}
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
	// The unrelated host rule must have survived.
	found := false
	for _, r := range k.rules["filter/FORWARD"] {
		if len(r) >= 2 && r[1] == "docker0" {
			found = true
		}
	}
	if !found {
		t.Fatal("repair deleted an unrelated host rule")
	}
}

func TestRepairIsOneAtomicTransactionPerTable(t *testing.T) {
	// The old repair inserted/deleted rule-by-rule (a bypass window and a
	// line-number race); the rebuilt chain must now land in a single restore
	// commit per table, with the final state verified.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	fw := rules["filter/FORWARD"]
	drop := fw[1]
	fw = append(append(fw[:1:1], fw[2:]...), drop) // misorder: drop at the end
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	if k.restores != 1 {
		t.Fatalf("want exactly one restore transaction, got %d", k.restores)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestRepairPreservesStricterForeignRulesAbove(t *testing.T) {
	// An operator's stricter veth DROP above the block must stay ABOVE vmd's
	// broad ACCEPT through a repair — demoting it would shadow it into a no-op.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	strict := []string{"-i", "veth+", "-p", "tcp", "--dport", "22", "-j", "DROP"}
	fw := rules["filter/FORWARD"]
	fw[2], fw[3] = fw[3], fw[2] // force a repair via misordered clamp
	rules["filter/FORWARD"] = append([][]string{strict}, fw...)

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	got := k.rules["filter/FORWARD"]
	strictIdx, acceptIdx := -1, -1
	for i, r := range got {
		if ruleEqual(r, strict) {
			strictIdx = i
		}
		if acceptIdx == -1 && ruleEqual(r, marked("-i", "veth+", "-o", "eth0", "-j", "ACCEPT")) {
			acceptIdx = i
		}
	}
	if strictIdx == -1 {
		t.Fatal("stricter foreign DROP deleted by repair")
	}
	if strictIdx > acceptIdx {
		t.Fatalf("stricter foreign DROP demoted below the ACCEPT (%d > %d)", strictIdx, acceptIdx)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestRepairRefusesAmbiguousForeignRuleAbove(t *testing.T) {
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	fw := rules["filter/FORWARD"]
	fw[2], fw[3] = fw[3], fw[2] // needs repair
	rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "OPERATOR_CHAIN"}}, fw...)

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err := repairSharedOrdering(context.Background(), d, spec); err == nil {
		t.Fatal("repair must refuse to reorder past an ambiguous foreign jump")
	}
	if k.restores != 0 {
		t.Fatalf("refusal must not mutate, got %d restores", k.restores)
	}
}

func TestVerifyHeadGuard(t *testing.T) {
	spec := testSpec(true)

	t.Run("foreign veth accept above the block", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "ACCEPT"}}, fw...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("foreign catch-all between jump and drop", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		withGap := append([][]string{fw[0], {"-j", "ACCEPT"}}, fw[1:]...)
		rules["filter/FORWARD"] = withGap
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("stricter veth DROP above the block is fine", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-p", "tcp", "--dport", "22", "-j", "DROP"}}, fw...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
			t.Fatalf("stricter foreign DROP flagged: %s", class)
		}
	})
	t.Run("ambiguous veth jump above the block fails distinctly", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "OPERATOR_CHAIN"}}, fw...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded-ambiguous" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("foreign docker rule above the block is fine", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "docker0", "-j", "ACCEPT"}}, fw...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
			t.Fatalf("explicit non-veth interface flagged: %s", class)
		}
	})
	t.Run("repair converges a preceded chain", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "ACCEPT"}}, fw...)
		k := &fakeKernel{rules: rules, chains: chains}
		defer k.install(t)()
		d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
		if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
			t.Fatalf("repair: %v", err)
		}
		nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
		if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
			t.Fatalf("post-repair verify failed: %s %s", class, detail)
		}
	})
	t.Run("non-owner has no head guard", func(t *testing.T) {
		unowned := testSpec(false)
		rules, chains := specKernel(unowned, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "SOME_DAEMON_CHAIN"}}, fw...)
		d, err := parseIPTablesSave(renderDump(rules, chains))
		if err != nil {
			t.Fatalf("parse: %v", err)
		}
		if ok, class, _ := verifyHostFirewall(d, unowned); !ok {
			t.Fatalf("non-owner flagged a daemon rule above its block: %s", class)
		}
	})
}

func TestSpecDeduplicatesBlockedPorts(t *testing.T) {
	// 853 configured AND implied by the DNS redirect must yield one rule pair;
	// the installer's AppendUnique collapses duplicates, so a spec keeping
	// them could never verify post-install.
	spec := hostFWSpecFor("eth0", 0, 0, 5353, "", 0, []uint16{853, 25, 25}, true)
	drops := spec.ownedChains["filter/"+portDropChain]
	if len(drops) != 4 { // {853,25} × {tcp,udp}
		t.Fatalf("want 4 deduped drops, got %d: %v", len(drops), drops)
	}
	if !ruleEqual(drops[0].args, []string{"-p", "tcp", "--dport", "853", "-j", "DROP"}) {
		t.Fatalf("first-occurrence order not preserved: %v", drops[0].args)
	}
}

func TestCanonicalRuleMissingOperandIsMismatchNotPanic(t *testing.T) {
	for _, args := range [][]string{{"-i"}, {"--dport"}, {"--tcp-flags", "SYN,RST"}, {"-d"}} {
		if _, ok := canonicalRule(args); ok {
			t.Fatalf("truncated rule %v canonicalized", args)
		}
	}
}

func TestNonOwnerNeverRunsRepair(t *testing.T) {
	// Template-builder shape: post-install verification failure must not
	// mutate shared-chain ordering (its partial spec omits the daemon's
	// jumps) — it logs and proceeds.
	origLock := hostFirewallLockPath
	hostFirewallLockPath = t.TempDir() + "/hostfw.lock" // unprivileged runners cannot open /run
	defer func() { hostFirewallLockPath = origLock }()
	unowned := testSpec(false)
	rules, chains := specKernel(unowned, nil)
	fw := rules["filter/FORWARD"]
	fw[0], fw[1] = fw[1], fw[0] // misorder its own rules
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	origInstall := installHostFirewallFn
	installHostFirewallFn = func(string, uint16, uint16, uint16, string, uint16, []uint16, bool, zerolog.Logger) error { return nil }
	defer func() { installHostFirewallFn = origInstall }()
	origRestore := restoreIPTables
	restoreIPTables = func(context.Context, string) error {
		t.Fatal("non-owner mutated shared-chain ordering")
		return nil
	}
	defer func() { restoreIPTables = origRestore }()

	iface, hp, tp, dp, sd, sp, bp := testSpecParams()
	if err := ensureHostFirewall(context.Background(), iface, hp, tp, dp, sd, sp, bp, false, zerolog.Nop()); err != nil {
		t.Fatalf("non-owner ensure must proceed without repair: %v", err)
	}
}

func TestNormalizeRoundTripShapes(t *testing.T) {
	spec := testSpec(true)
	roundTrip := func(key string, w fwRule) {
		line := "-A X " + strings.Join(saveForm(w.args), " ")
		tokens, err := splitRuleTokens(line)
		if err != nil {
			t.Fatalf("%s rule line unparseable: %v", key, err)
		}
		if !ruleEqual(w.args, tokens[2:]) {
			t.Fatalf("%s rule does not round-trip: %v vs %v", key, w.args, tokens[2:])
		}
	}
	for key, want := range spec.sharedOrdered {
		for _, w := range want {
			roundTrip(key, w)
		}
	}
	for key, want := range spec.ownedChains {
		for _, w := range want {
			roundTrip(key, w)
		}
	}
}

func FuzzParseIPTablesSave(f *testing.F) {
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	f.Add(renderDump(rules, chains))
	f.Add("*filter\n:FORWARD ACCEPT [0:0]\n-A FORWARD -i veth+ -j DROP\nCOMMIT\n")
	f.Add("")
	f.Add("*filter\n-A FORWARD -i\nCOMMIT\n") // truncated operand — must not panic
	f.Add("*filter\n:FORWARD ACCEPT [0:0]\n-A FORWARD -i veth+ -m comment --comment \"a -j DROP b\" -j ACCEPT\nCOMMIT\n")
	f.Fuzz(func(t *testing.T, in string) {
		d, err := parseIPTablesSave(in)
		if err != nil {
			return
		}
		// Whatever parsed must never verify as intact unless it genuinely
		// contains every spec rule — spot-check with the strictest chain.
		ok, _, _ := verifyHostFirewall(d, spec)
		if ok {
			// The fuzzer found an input that verifies: it must actually
			// contain the udp drop in FORWARD.
			found := false
			for _, r := range d.rules["filter/FORWARD"] {
				if ruleEqual(r, marked("-i", "veth+", "-p", "udp", "--dport", "443", "-j", "DROP")) {
					found = true
				}
			}
			if !found {
				t.Fatalf("verified-intact input lacks the udp drop: %q", in)
			}
		}
	})
}

var _ = zerolog.Nop

func TestForeignGotoIsAmbiguous(t *testing.T) {
	// -g/--goto is control flow without -j; it must never read as inert.
	for _, tokens := range [][]string{
		{"-i", "veth+", "-g", "OPERATOR_CHAIN"},
		{"-i", "veth+", "--goto", "OPERATOR_CHAIN"},
	} {
		if got := foreignDisposition(tokens); got != "ambiguous" {
			t.Fatalf("%v disposition = %s, want ambiguous", tokens, got)
		}
	}
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	fw := rules["filter/FORWARD"]
	rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-g", "OPERATOR_CHAIN"}}, fw...)
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded-ambiguous" {
		t.Fatalf("ok=%v class=%s", ok, class)
	}
}

func TestRepairPreservesInterleavedStrictRule(t *testing.T) {
	// A restrictive DROP interleaved BETWEEN vmd rules (not just above the
	// block) must stay above the rebuilt ACCEPT — demoting it would silently
	// disable an operator rule.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	strict := []string{"-i", "veth+", "-p", "tcp", "--dport", "22", "-j", "DROP"}
	fw := rules["filter/FORWARD"]
	// Interleave the strict rule between clamp and the accepts, and misorder
	// the clamp to force a repair.
	interleaved := append([][]string{}, fw[0], fw[1], strict, fw[3], fw[4], fw[2])
	rules["filter/FORWARD"] = interleaved

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	got := k.rules["filter/FORWARD"]
	strictIdx, acceptIdx := -1, -1
	for i, r := range got {
		if ruleEqual(r, strict) {
			strictIdx = i
		}
		if acceptIdx == -1 && ruleEqual(r, marked("-i", "veth+", "-o", "eth0", "-j", "ACCEPT")) {
			acceptIdx = i
		}
	}
	if strictIdx == -1 || strictIdx > acceptIdx {
		t.Fatalf("interleaved strict DROP not preserved above the ACCEPT (strict=%d accept=%d)", strictIdx, acceptIdx)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestLockHostFirewallSerializes(t *testing.T) {
	orig := hostFirewallLockPath
	hostFirewallLockPath = t.TempDir() + "/hostfw.lock"
	defer func() { hostFirewallLockPath = orig }()

	unlock, err := lockHostFirewall(context.Background())
	if err != nil {
		t.Fatalf("lock: %v", err)
	}
	acquired := make(chan struct{})
	go func() {
		u2, err := lockHostFirewall(context.Background())
		if err != nil {
			t.Errorf("second lock: %v", err)
			close(acquired)
			return
		}
		close(acquired)
		u2()
	}()
	select {
	case <-acquired:
		t.Fatal("second lock acquired while held")
	case <-time.After(100 * time.Millisecond):
	}
	unlock()
	select {
	case <-acquired:
	case <-time.After(2 * time.Second):
		t.Fatal("second lock never acquired after release")
	}
}

func TestLockHostFirewallHonorsContext(t *testing.T) {
	orig := hostFirewallLockPath
	hostFirewallLockPath = t.TempDir() + "/hostfw.lock"
	defer func() { hostFirewallLockPath = orig }()

	unlock, err := lockHostFirewall(context.Background())
	if err != nil {
		t.Fatalf("lock: %v", err)
	}
	defer unlock()

	ctx, cancel := context.WithTimeout(context.Background(), 200*time.Millisecond)
	defer cancel()
	if _, err := lockHostFirewall(ctx); err == nil {
		t.Fatal("contended lock with cancelled context must fail, not block")
	}
}

func TestRepairNeverNamesForeignRules(t *testing.T) {
	// The transaction may only reference vmd's own rules: no flushes, and
	// every -D/-I/-A rulespec must match the spec — so a foreign rule added
	// at ANY moment (even between dump and restore) cannot be deleted.
	spec := testSpec(true)
	rules, chains := specKernel(spec, map[string][][]string{
		"filter/FORWARD": {{"-i", "docker0", "-j", "ACCEPT"}},
	})
	fw := rules["filter/FORWARD"]
	fw[2], fw[3] = fw[3], fw[2] // force repair
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	specRules := map[string]bool{}
	for _, want := range spec.sharedOrdered {
		for _, w := range want {
			c, _ := canonicalRule(w.args)
			specRules[strings.Join(c, "|")] = true
		}
	}
	for _, input := range k.inputs {
		for _, line := range strings.Split(input, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || line == "COMMIT" || strings.HasPrefix(line, "*") {
				continue
			}
			if strings.HasPrefix(line, "-F ") {
				t.Fatalf("repair flushed a shared chain: %q", line)
			}
			fields := strings.Fields(line)
			args := fields[2:]
			if fields[0] == "-I" {
				args = fields[3:]
			}
			c, ok := canonicalRule(args)
			if !ok || !specRules[strings.Join(c, "|")] {
				t.Fatalf("repair referenced a non-vmd rule: %q", line)
			}
		}
	}
	// And the foreign rule is still present.
	found := false
	for _, r := range k.rules["filter/FORWARD"] {
		if len(r) >= 2 && r[1] == "docker0" {
			found = true
		}
	}
	if !found {
		t.Fatal("foreign rule lost")
	}
}

func TestRepairRefusesStrictForeignAbovePreroutingRedirect(t *testing.T) {
	// PREROUTING redirects are terminal: head-inserting ours would demote a
	// foreign DROP that ran before a redirect to below it, silently disabling
	// the operator rule. Repair must refuse without mutation.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	pre := rules["nat/PREROUTING"]
	strict := []string{"-i", "veth+", "-p", "tcp", "--dport", "80", "-j", "DROP"}
	// Strict foreign above the redirects, plus a misorder to force repair.
	pre[1], pre[2] = pre[2], pre[1]
	rules["nat/PREROUTING"] = append([][]string{strict}, pre...)

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err := repairSharedOrdering(context.Background(), d, spec); err == nil {
		t.Fatal("repair must refuse to demote a stricter foreign rule below a terminal redirect")
	}
	if k.restores != 0 {
		t.Fatalf("refusal must not mutate, got %d restores", k.restores)
	}
}

func TestStaleManagedRedirectIsReconciledNotFatal(t *testing.T) {
	// A supported config change (secretsproxy address, proxy port) leaves the
	// previous generation's redirect installed. It must classify as a
	// repairable stale-managed mismatch — not preceded-ambiguous — and repair
	// must delete it while foreign redirects stay untouched.
	spec := testSpec(true)
	oldSecrets := marked("-i", "veth+", "-p", "tcp", "-d", "169.254.0.99", "--dport", "9443", "-j", "REDIRECT", "--to-port", "9443")
	oldTLS := marked("-i", "veth+", "-p", "tcp", "--dport", "443", "-j", "REDIRECT", "--to-port", "9999")
	rules, chains := specKernel(spec, nil)
	rules["nat/PREROUTING"] = append([][]string{oldSecrets, oldTLS}, rules["nat/PREROUTING"]...)

	if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "stale-managed" {
		t.Fatalf("ok=%v class=%s, want stale-managed", ok, class)
	}

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
	for _, r := range k.rules["nat/PREROUTING"] {
		if ruleEqual(r, oldSecrets) || ruleEqual(r, oldTLS) {
			t.Fatalf("stale managed redirect survived reconciliation: %v", r)
		}
	}
}

func TestOperatorRulesNeverReadAsStale(t *testing.T) {
	// Staleness is keyed on the explicit ownership marker, never on shape: an
	// operator redirect — even one colliding with vmd ports — must never be
	// reconciled away.
	want := testSpec(true).sharedOrdered["nat/PREROUTING"]
	for _, tokens := range [][]string{
		{"-i", "veth+", "-p", "tcp", "--dport", "80", "-j", "REDIRECT", "--to-port", "8888"},
		{"-i", "veth+", "-p", "tcp", "--dport", "443", "-j", "REDIRECT", "--to-port", "8443"},
		{"-i", "veth+", "-p", "tcp", "-d", "10.0.0.5", "--dport", "9443", "-j", "REDIRECT", "--to-port", "9443"},
		{"-i", "veth+", "-p", "tcp", "--dport", "8080", "-j", "REDIRECT", "--to-port", "999", "-m", "comment", "--comment", "operator rule"},
	} {
		if staleManagedRule(tokens, want) {
			t.Fatalf("operator redirect misread as stale vmd rule: %v", tokens)
		}
	}
}

func TestUnmarkedTwinIsUpgradeMigrated(t *testing.T) {
	// The pre-marker generation of exactly a current rule (identical
	// parameters, no marker) is stale: deleting it and keeping the marked
	// twin is behavior-preserving — the one-time upgrade migration.
	spec := testSpec(true)
	want := spec.sharedOrdered["filter/FORWARD"]
	unmarkedDrop := []string{"-i", "veth+", "-p", "udp", "--dport", "443", "-j", "DROP"}
	if !staleManagedRule(unmarkedDrop, want) {
		t.Fatal("unmarked exact twin not recognized as upgrade-stale")
	}
	rules, chains := specKernel(spec, nil)
	rules["filter/FORWARD"] = append([][]string{unmarkedDrop}, rules["filter/FORWARD"]...)
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "stale-managed" {
		t.Fatalf("ok=%v class=%s", ok, class)
	}
	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-migration verify failed: %s %s", class, detail)
	}
	for _, r := range k.rules["filter/FORWARD"] {
		if ruleEqual(r, unmarkedDrop) {
			t.Fatal("unmarked twin survived migration")
		}
	}
}

func TestQuotedCommentCannotSpoofDisposition(t *testing.T) {
	// A foreign ACCEPT whose comment contains "-j DROP" must still classify
	// as permissive — quote-aware tokenization keeps the comment one token.
	line := `-A FORWARD -i veth+ -m comment --comment "audit -j DROP rule" -j ACCEPT`
	tokens, err := splitRuleTokens(line)
	if err != nil {
		t.Fatalf("split: %v", err)
	}
	if got := foreignDisposition(tokens[2:]); got != "permissive" {
		t.Fatalf("disposition = %s, want permissive", got)
	}
	// And end to end: that rule above the drops must flag, not pass.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	fw := rules["filter/FORWARD"]
	rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-m", "comment", "--comment", "audit -j DROP rule", "-j", "ACCEPT"}}, fw...)
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded" {
		t.Fatalf("ok=%v class=%s, want preceded", ok, class)
	}
	if _, err := splitRuleTokens(`-A FORWARD -m comment --comment "unbalanced`); err == nil {
		t.Fatal("unbalanced quote must error")
	}
}

func TestRepairKeepsClampAheadOfForeignAccept(t *testing.T) {
	// A tolerated foreign veth ACCEPT below the drops must not end up ahead
	// of the MSS clamp after a repair — unclamped sandbox SYNs would leave
	// FORWARD before TCPMSS runs.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	foreignAccept := []string{"-i", "veth+", "-p", "tcp", "--dport", "8443", "-j", "ACCEPT"}
	fw := rules["filter/FORWARD"]
	// Foreign accept after the drops (tolerated), duplicate udp drop at the
	// end to force a repair.
	fw = append(fw[:2:2], append([][]string{foreignAccept}, fw[2:]...)...)
	fw = append(fw, append([]string(nil), fw[1]...))
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	got := k.rules["filter/FORWARD"]
	clampIdx, foreignIdx := -1, -1
	for i, r := range got {
		if ruleEqual(r, marked("-o", "eth0", "-p", "tcp", "--tcp-flags", "SYN,RST", "SYN", "-j", "TCPMSS", "--clamp-mss-to-pmtu")) {
			clampIdx = i
		}
		if ruleEqual(r, foreignAccept) {
			foreignIdx = i
		}
	}
	if clampIdx == -1 || foreignIdx == -1 || clampIdx > foreignIdx {
		t.Fatalf("clamp not ahead of foreign accept after repair (clamp=%d foreign=%d)", clampIdx, foreignIdx)
	}
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestVerifyGuardsClampFromPrecedingTerminalAccept(t *testing.T) {
	spec := testSpec(true)

	t.Run("terminal accept between drops and clamp flags", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		foreign := []string{"-i", "veth+", "-p", "tcp", "--dport", "8443", "-j", "ACCEPT"}
		rules["filter/FORWARD"] = append(fw[:2:2], append([][]string{foreign}, fw[2:]...)...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded" {
			t.Fatalf("ok=%v class=%s, want preceded", ok, class)
		}
	})
	t.Run("non-terminal unknown between drops and clamp tolerated", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		logRule := []string{"-i", "veth+", "-j", "LOG"}
		rules["filter/FORWARD"] = append(fw[:2:2], append([][]string{logRule}, fw[2:]...)...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
			t.Fatalf("non-terminal unknown past the drops flagged: %s", class)
		}
	})
	t.Run("repair converges the flagged accept", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		foreign := []string{"-i", "veth+", "-p", "tcp", "--dport", "8443", "-j", "ACCEPT"}
		rules["filter/FORWARD"] = append(fw[:2:2], append([][]string{foreign}, fw[2:]...)...)
		k := &fakeKernel{rules: rules, chains: chains}
		defer k.install(t)()
		d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
		if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
			t.Fatalf("repair: %v", err)
		}
		nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
		if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
			t.Fatalf("post-repair verify failed: %s %s", class, detail)
		}
	})
}
