package network

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"testing"

	"github.com/rs/zerolog"
)

func testSpecParams() (string, uint16, uint16, uint16, string, uint16, []uint16) {
	return "eth0", 3128, 3129, 5353, "169.254.0.21", 9443, []uint16{25, 465}
}

func testSpec(owned bool) hostFWSpec {
	iface, hp, tp, dp, sd, sp, bp := testSpecParams()
	return hostFWSpecFor(iface, hp, tp, dp, sd, sp, bp, owned)
}

// renderDump renders a fake kernel ruleset as iptables-save output, in the
// canonical form iptables-save uses (-m tcp/udp inserted, --to-ports, /32).
func renderDump(rules map[string][][]string, chains []string) string {
	var b strings.Builder
	for _, table := range []string{"filter", "nat"} {
		fmt.Fprintf(&b, "# Generated by test\n*%s\n", table)
		builtins := map[string][]string{
			"filter": {"INPUT", "FORWARD", "OUTPUT"},
			"nat":    {"PREROUTING", "INPUT", "OUTPUT", "POSTROUTING"},
		}[table]
		for _, c := range builtins {
			fmt.Fprintf(&b, ":%s ACCEPT [0:0]\n", c)
		}
		for _, tc := range chains {
			tab, chain, _ := strings.Cut(tc, "/")
			if tab == table {
				fmt.Fprintf(&b, ":%s - [0:0]\n", chain)
			}
		}
		for key, rs := range rules {
			tab, chain, _ := strings.Cut(key, "/")
			if tab != table {
				continue
			}
			for _, r := range rs {
				fmt.Fprintf(&b, "-A %s %s\n", chain, strings.Join(saveForm(r), " "))
			}
		}
		b.WriteString("COMMIT\n")
	}
	return b.String()
}

// saveForm converts installer-arg form into iptables-save output form.
func saveForm(args []string) []string {
	out := make([]string, 0, len(args)+2)
	for i := 0; i < len(args); i++ {
		a := args[i]
		out = append(out, a)
		if a == "-p" && i+1 < len(args) && (args[i+1] == "tcp" || args[i+1] == "udp") {
			out = append(out, args[i+1], "-m", args[i+1])
			i++
			continue
		}
		if a == "--to-port" {
			out[len(out)-1] = "--to-ports"
		}
		if a == "-d" && i+1 < len(args) && !strings.Contains(args[i+1], "/") {
			out = append(out, args[i+1]+"/32")
			i++
		}
	}
	return out
}

// specKernel builds the fake kernel state exactly matching a spec, plus any
// unrelated host rules passed in.
func specKernel(spec hostFWSpec, extraShared map[string][][]string) (map[string][][]string, []string) {
	rules := map[string][][]string{}
	var chains []string
	for key, want := range spec.sharedOrdered {
		for _, w := range want {
			rules[key] = append(rules[key], append([]string(nil), w.args...))
		}
		for _, e := range extraShared[key] {
			rules[key] = append(rules[key], e)
		}
	}
	for key, want := range spec.ownedChains {
		chains = append(chains, key)
		for _, w := range want {
			rules[key] = append(rules[key], append([]string(nil), w.args...))
		}
	}
	return rules, chains
}

func mustVerify(t *testing.T, dump string, spec hostFWSpec) (bool, string) {
	t.Helper()
	d, err := parseIPTablesSave(dump)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	ok, class, _ := verifyHostFirewall(d, spec)
	return ok, class
}

func TestVerifyIntactAndIgnoresUnrelatedRules(t *testing.T) {
	spec := testSpec(true)
	rules, chains := specKernel(spec, map[string][][]string{
		"filter/FORWARD": {{"-i", "docker0", "-j", "ACCEPT"}},
	})
	// Unrelated rule interleaved: still intact.
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
		t.Fatalf("intact ruleset read as %s", class)
	}
}

func TestVerifyDetectsEveryMismatchClass(t *testing.T) {
	spec := testSpec(true)

	t.Run("missing-rule", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		rules["filter/FORWARD"] = rules["filter/FORWARD"][1:] // drop the port jump
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "missing-rule" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("duplicate-rule", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append(fw, fw[1]) // duplicate the udp drop at the end
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "duplicate-rule" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("misordered", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		// Move the clamp after the broad ACCEPT — the legacy AppendUnique hazard.
		fw[2], fw[3] = fw[3], fw[2]
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "misordered" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("mutated-rule", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		fw[1] = []string{"-i", "veth+", "-p", "udp", "--dport", "444", "-j", "DROP"} // wrong port
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "missing-rule" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("owned-chain-extra-rule", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		key := "filter/" + portDropChain
		rules[key] = append(rules[key], []string{"-p", "tcp", "--dport", "9999", "-j", "DROP"})
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "owned-chain-drift" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("owned-chain-reordered", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		key := "filter/" + portDropChain
		rs := rules[key]
		rs[0], rs[1] = rs[1], rs[0]
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "owned-chain-drift" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("missing-owned-chain", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		if ok, class := mustVerify(t, renderDump(rules, chains[:1]), spec); ok || class != "missing-chain" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
}

func TestVerifyWithoutOwnedChainsIgnoresThem(t *testing.T) {
	// Template-builder shape: manageOwnedChains=false must neither require nor
	// inspect the daemon-owned chains or their jumps.
	spec := testSpec(false)
	if len(spec.ownedChains) != 0 {
		t.Fatalf("unowned spec has owned chains: %v", spec.ownedChains)
	}
	for _, r := range spec.sharedOrdered["filter/FORWARD"] {
		if r.args[len(r.args)-1] == portDropChain {
			t.Fatal("unowned spec includes the port-drop jump")
		}
	}
	rules, chains := specKernel(spec, nil)
	if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
		t.Fatalf("unowned intact read as %s", class)
	}
}

func TestParseToleratesIncompatibleTableComments(t *testing.T) {
	// iptables-nft-save flags foreign native-nft tables (our host egress-block
	// table) as comment lines; they must parse cleanly, not force a slow path.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	dump := "# Table `sandbox_egress_block' is incompatible, use 'nft' tool.\n" + renderDump(rules, chains)
	if ok, class := mustVerify(t, dump, spec); !ok {
		t.Fatalf("incompatible-table comment broke verification: %s", class)
	}
}

func TestParseRejectsUnknownSyntax(t *testing.T) {
	for _, bad := range []string{
		"*filter\ngarbage line\nCOMMIT\n",
		"-A FORWARD -j ACCEPT\n", // rule before table
		"*filter\n-A\nCOMMIT\n",  // malformed rule
		":FORWARD ACCEPT [0:0]\n",
	} {
		if _, err := parseIPTablesSave(bad); err == nil {
			t.Fatalf("parser accepted %q", bad)
		}
	}
}

// fakeKernel backs the dump/run seams so ensureHostFirewall's repair loop can
// be exercised without iptables. It supports the two operations repair uses:
// -I chain 1 and -D chain <n>.
type fakeKernel struct {
	rules  map[string][][]string
	chains []string
}

func (k *fakeKernel) install(t *testing.T) func() {
	t.Helper()
	origDump, origRun := dumpIPTables, runIPTables
	dumpIPTables = func(context.Context) (string, error) { return renderDump(k.rules, k.chains), nil }
	runIPTables = func(_ context.Context, args []string) (string, error) {
		// args: -w 5 -t <table> (-I chain <n> rule... | -D chain <n>)
		table, op, chain := args[3], args[4], args[5]
		key := table + "/" + chain
		n, _ := strconv.Atoi(args[6])
		switch op {
		case "-I":
			rule := append([]string(nil), args[7:]...)
			if n < 1 || n > len(k.rules[key])+1 {
				return "", fmt.Errorf("fake kernel: insert position %d out of range", n)
			}
			rs := k.rules[key]
			k.rules[key] = append(rs[:n-1], append([][]string{rule}, rs[n-1:]...)...)
		case "-D":
			if n < 1 || n > len(k.rules[key]) {
				return "", fmt.Errorf("fake kernel: delete position %d out of range", n)
			}
			k.rules[key] = append(k.rules[key][:n-1], k.rules[key][n:]...)
		default:
			return "", fmt.Errorf("fake kernel: unsupported op %v", args)
		}
		return "", nil
	}
	return func() { dumpIPTables, runIPTables = origDump, origRun }
}

func TestRepairCanonicalizesMisorderAndDuplicates(t *testing.T) {
	spec := testSpec(true)
	rules, chains := specKernel(spec, map[string][][]string{
		"filter/FORWARD": {{"-i", "docker0", "-j", "ACCEPT"}},
	})
	// Sabotage FORWARD: move clamp after ACCEPTs and duplicate the udp drop.
	fw := rules["filter/FORWARD"]
	clamp := fw[2]
	fw = append(fw[:2], fw[3:]...)
	fw = append(fw, clamp, append([]string(nil), fw[1]...))
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()

	d, err := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if ok, _, _ := verifyHostFirewall(d, spec); ok {
		t.Fatal("sabotaged ruleset verified — test broken")
	}
	if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	nd, err := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err != nil {
		t.Fatalf("reparse: %v", err)
	}
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
	// The unrelated host rule must have survived.
	found := false
	for _, r := range k.rules["filter/FORWARD"] {
		if len(r) >= 2 && r[1] == "docker0" {
			found = true
		}
	}
	if !found {
		t.Fatal("repair deleted an unrelated host rule")
	}
}

func TestRepairNeverWeakensEnforcementMidFlight(t *testing.T) {
	// At every single mutation step: (a) the udp/443 DROP exists somewhere,
	// and (b) the number of veth+→host ACCEPTs with NO udp drop above them
	// never exceeds its starting value — the reverse-insert bug put a fresh
	// ACCEPT at the chain head before any drop, which this catches.
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	fw := rules["filter/FORWARD"]
	// Misorder: move the udp drop to the end (after the ACCEPTs).
	drop := fw[1]
	fw = append(append(fw[:1:1], fw[2:]...), drop)
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()

	udpDrop := []string{"-i", "veth+", "-p", "udp", "--dport", "443", "-j", "DROP"}
	acceptOut := []string{"-i", "veth+", "-o", "eth0", "-j", "ACCEPT"}
	unguardedAccepts := func() int {
		n, dropsSeen := 0, 0
		for _, r := range k.rules["filter/FORWARD"] {
			if ruleEqual(r, udpDrop) {
				dropsSeen++
			}
			if ruleEqual(r, acceptOut) && dropsSeen == 0 {
				n++
			}
		}
		return n
	}
	baseline := unguardedAccepts()

	origRun := runIPTables
	runIPTables = func(ctx context.Context, args []string) (string, error) {
		out, err := origRun(ctx, args)
		found := false
		for _, r := range k.rules["filter/FORWARD"] {
			if ruleEqual(r, udpDrop) {
				found = true
			}
		}
		if !found {
			t.Fatal("udp/443 DROP absent mid-repair — enforcement gap")
		}
		if got := unguardedAccepts(); got > baseline {
			t.Fatalf("unguarded ACCEPT count rose mid-repair (%d > %d) — bypass window", got, baseline)
		}
		return out, err
	}

	d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
		t.Fatalf("repair: %v", err)
	}
	runIPTables = origRun
	nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
	if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
		t.Fatalf("post-repair verify failed: %s %s", class, detail)
	}
}

func TestVerifyHeadGuard(t *testing.T) {
	spec := testSpec(true)

	t.Run("foreign veth accept above the block", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "ACCEPT"}}, fw...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("foreign catch-all between jump and drop", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		withGap := append([][]string{fw[0], {"-j", "ACCEPT"}}, fw[1:]...)
		rules["filter/FORWARD"] = withGap
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); ok || class != "preceded" {
			t.Fatalf("ok=%v class=%s", ok, class)
		}
	})
	t.Run("foreign docker rule above the block is fine", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "docker0", "-j", "ACCEPT"}}, fw...)
		if ok, class := mustVerify(t, renderDump(rules, chains), spec); !ok {
			t.Fatalf("explicit non-veth interface flagged: %s", class)
		}
	})
	t.Run("repair converges a preceded chain", func(t *testing.T) {
		rules, chains := specKernel(spec, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "ACCEPT"}}, fw...)
		k := &fakeKernel{rules: rules, chains: chains}
		defer k.install(t)()
		d, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
		if err := repairSharedOrdering(context.Background(), d, spec); err != nil {
			t.Fatalf("repair: %v", err)
		}
		nd, _ := parseIPTablesSave(renderDump(k.rules, k.chains))
		if ok, class, detail := verifyHostFirewall(nd, spec); !ok {
			t.Fatalf("post-repair verify failed: %s %s", class, detail)
		}
	})
	t.Run("non-owner has no head guard", func(t *testing.T) {
		unowned := testSpec(false)
		rules, chains := specKernel(unowned, nil)
		fw := rules["filter/FORWARD"]
		rules["filter/FORWARD"] = append([][]string{{"-i", "veth+", "-j", "SOME_DAEMON_CHAIN"}}, fw...)
		d, err := parseIPTablesSave(renderDump(rules, chains))
		if err != nil {
			t.Fatalf("parse: %v", err)
		}
		if ok, class, _ := verifyHostFirewall(d, unowned); !ok {
			t.Fatalf("non-owner flagged a daemon rule above its block: %s", class)
		}
	})
}

func TestSpecDeduplicatesBlockedPorts(t *testing.T) {
	// 853 configured AND implied by the DNS redirect must yield one rule pair;
	// the installer's AppendUnique collapses duplicates, so a spec keeping
	// them could never verify post-install.
	spec := hostFWSpecFor("eth0", 0, 0, 5353, "", 0, []uint16{853, 25, 25}, true)
	drops := spec.ownedChains["filter/"+portDropChain]
	if len(drops) != 4 { // {853,25} × {tcp,udp}
		t.Fatalf("want 4 deduped drops, got %d: %v", len(drops), drops)
	}
	if !ruleEqual(drops[0].args, []string{"-p", "tcp", "--dport", "853", "-j", "DROP"}) {
		t.Fatalf("first-occurrence order not preserved: %v", drops[0].args)
	}
}

func TestCanonicalRuleMissingOperandIsMismatchNotPanic(t *testing.T) {
	for _, args := range [][]string{{"-i"}, {"--dport"}, {"--tcp-flags", "SYN,RST"}, {"-d"}} {
		if _, ok := canonicalRule(args); ok {
			t.Fatalf("truncated rule %v canonicalized", args)
		}
	}
}

func TestNonOwnerNeverRunsRepair(t *testing.T) {
	// Template-builder shape: post-install verification failure must not
	// mutate shared-chain ordering (its partial spec omits the daemon's
	// jumps) — it logs and proceeds.
	unowned := testSpec(false)
	rules, chains := specKernel(unowned, nil)
	fw := rules["filter/FORWARD"]
	fw[0], fw[1] = fw[1], fw[0] // misorder its own rules
	rules["filter/FORWARD"] = fw

	k := &fakeKernel{rules: rules, chains: chains}
	defer k.install(t)()
	origInstall := installHostFirewallFn
	installHostFirewallFn = func(string, uint16, uint16, uint16, string, uint16, []uint16, bool, zerolog.Logger) error { return nil }
	defer func() { installHostFirewallFn = origInstall }()
	origRun := runIPTables
	runIPTables = func(context.Context, []string) (string, error) {
		t.Fatal("non-owner mutated shared-chain ordering")
		return "", nil
	}
	defer func() { runIPTables = origRun }()

	iface, hp, tp, dp, sd, sp, bp := testSpecParams()
	if err := ensureHostFirewall(context.Background(), iface, hp, tp, dp, sd, sp, bp, false, zerolog.Nop()); err != nil {
		t.Fatalf("non-owner ensure must proceed without repair: %v", err)
	}
}

func TestNormalizeRoundTripShapes(t *testing.T) {
	spec := testSpec(true)
	for key, want := range spec.sharedOrdered {
		for _, w := range want {
			if !ruleEqual(w.args, saveForm(w.args)) {
				t.Fatalf("%s rule does not round-trip: %v vs %v", key, w.args, saveForm(w.args))
			}
		}
	}
	for key, want := range spec.ownedChains {
		for _, w := range want {
			if !ruleEqual(w.args, saveForm(w.args)) {
				t.Fatalf("%s rule does not round-trip: %v", key, w.args)
			}
		}
	}
}

func FuzzParseIPTablesSave(f *testing.F) {
	spec := testSpec(true)
	rules, chains := specKernel(spec, nil)
	f.Add(renderDump(rules, chains))
	f.Add("*filter\n:FORWARD ACCEPT [0:0]\n-A FORWARD -i veth+ -j DROP\nCOMMIT\n")
	f.Add("")
	f.Add("*filter\n-A FORWARD -i\nCOMMIT\n") // truncated operand — must not panic
	f.Fuzz(func(t *testing.T, in string) {
		d, err := parseIPTablesSave(in)
		if err != nil {
			return
		}
		// Whatever parsed must never verify as intact unless it genuinely
		// contains every spec rule — spot-check with the strictest chain.
		ok, _, _ := verifyHostFirewall(d, spec)
		if ok {
			// The fuzzer found an input that verifies: it must actually
			// contain the udp drop in FORWARD.
			found := false
			for _, r := range d.rules["filter/FORWARD"] {
				if ruleEqual(r, []string{"-i", "veth+", "-p", "udp", "--dport", "443", "-j", "DROP"}) {
					found = true
				}
			}
			if !found {
				t.Fatalf("verified-intact input lacks the udp drop: %q", in)
			}
		}
	})
}

var _ = zerolog.Nop
