package scheduler

import (
	"context"
	"errors"
	"fmt"
	"math/rand/v2"
	"sort"
	"sync"
	"sync/atomic"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"

	"github.com/superserve-ai/sandbox/internal/db"
)

// HostCapabilityCapacityPressure is advertised on a host's heartbeat by a
// vmd build that publishes capacity pressure (PUT /internal/hosts/:id/
// pressure). It is the wire contract that lets the scheduler distinguish
// "this host never publishes pressure" (legacy placement allowed) from
// "this host should be publishing but its report is stale/missing" (fail
// closed: no new placement). The daemon-side definition lives with the
// heartbeat sender in internal/vm/heartbeat.go and must match.
const HostCapabilityCapacityPressure = "capacity_pressure_v1"

// Reservation policy constants. These parameterize the SQL in
// db/queries/hosts.sql (the freshness gate in ReserveHostCapacity, the
// counter recomputation in UpsertHostPressure, RetireHostReservations,
// and the drain-visible count in ListHostsAdmin) so the policy has
// exactly one definition; the retirement contract they implement is
// documented on the host_reservation table.
const (
	// PressureFreshnessSecs is how old a pressure report may be before a
	// pressure-capable host fails closed for admission. Three heartbeat
	// intervals: one report in flight, one missed, and margin — a
	// publisher that broke while its heartbeat stays healthy must stop
	// taking placements before the drift can matter, but a single lost
	// report must not blip a healthy host out of rotation.
	PressureFreshnessSecs = 90

	// ReservationLeaseSecs bounds how long an unmaterialized reservation
	// keeps charging capacity. It only exists for creates that die
	// between admission and the vmd RPC returning (control-plane crash,
	// context torn down before the abort ran): every deliberate failure
	// path deletes its row immediately. Generous on purpose — an expired
	// lease under a live create would over-place, an over-long lease
	// merely under-places by one slot for its duration.
	ReservationLeaseSecs = 300

	// ReservationRetireSlackSecs is how far a pressure report's
	// reported_at must clear a reservation's materialized_at before the
	// reservation stops charging. A report can be SAMPLED on the host
	// before the VM entered vmd's instance map and ARRIVE at the
	// database after — the slack covers that publish-in-flight window
	// (observed well under a second; sized with margin because the cost
	// of slack is only a few seconds of double-counting an
	// already-counted VM).
	ReservationRetireSlackSecs = 15
)

const (
	// admissionMaxAttempts bounds how many ranked hosts one create tries
	// before giving up. Attempts beyond the first mean the cached view
	// disagreed with the fenced truth (a race or a burst); more retries
	// than this add latency without adding placements worth having.
	admissionMaxAttempts = 3

	// pressureScoreTolerance defines "comparable" dominant pressure:
	// every host within this band of the best score is an equally valid
	// target, and the choice within the band is uniformly random. The
	// randomness is load-bearing — if every control-plane replica tried
	// the globally best host first, its reservation row would serialize
	// the whole fleet's creates (and the band re-creates exactly the
	// thundering herd the legacy power-of-two choice exists to avoid).
	pressureScoreTolerance = 0.15
)

// PlacementRequest describes one sandbox create to place.
type PlacementRequest struct {
	// SandboxID is generated by the caller BEFORE placement so the
	// reservation ledger row carries the sandbox's real identity —
	// that's what makes admission idempotent under control-plane
	// retries (the same create can never double-reserve).
	SandboxID            uuid.UUID
	RequiredCapabilities []string
	// MemoryMib/Vcpus are the request's resource shape: charged into the
	// reservation ledger and folded into ranking. Not hard admission
	// limits (firecracker hosts overcommit both; see ReserveHostCapacity).
	MemoryMib int32
	Vcpus     int32
	// AllowedHosts restricts candidates to this set when non-empty. The
	// hook for template locality (a create from a template only the
	// building host holds) — the constraint's producer is separate work;
	// placement just honors it.
	AllowedHosts []string
}

// Placement is a selected host plus the reservation's lifecycle hooks.
// Confirm and Abort are non-nil only when an admission reservation
// fences this placement; both are safe to call from detached contexts
// and both tolerate failure (an unconfirmed reservation stops charging
// at lease expiry, an unaborted one likewise — always in the direction
// of transient under-placement, never over-placement).
type Placement struct {
	HostID string
	// Confirm records that the vmd create RPC returned success: the VM
	// now provably exists in vmd's instance map, which starts the
	// reservation's retirement clock. Call it as soon as the RPC
	// returns, off the hot path.
	Confirm func(ctx context.Context)
	// Abort frees the reservation immediately. Call it on every path
	// where the sandbox will not exist on the host: vmd rejection,
	// insert failure, any handler abort before dispatch.
	Abort func(ctx context.Context)
}

// PlacementObservation is one placement decision, for metrics. All
// fields are bounded enums or small ints — safe as metric labels.
type PlacementObservation struct {
	// Mode: "capacity" (fenced admission), "legacy" (non-publishing
	// hosts, unfenced), "fallback" (default-host bootstrap path).
	Mode string
	// Result: "placed", "exhausted" (every candidate rejected),
	// "no_hosts", "error".
	Result string
	// Attempts is how many admission statements ran (0 in legacy and
	// fallback modes).
	Attempts int
	// Reason qualifies rejections, from the cached view: "sandbox_limit",
	// "slot_limit", "raced" (cache said it fit; the fence disagreed —
	// another replica won the headroom or the report went stale between
	// cache and admission).
	Reason   string
	Duration time.Duration
}

// CapacityAware places sandboxes by published host pressure with an
// atomic per-create reservation fence. Enabled by config opt-in
// (SCHEDULER_CAPACITY_ADMISSION); LeastLoaded remains the default.
//
// Eligibility is three-state, per the capability on the host's current
// heartbeat:
//   - pressure-capable with a fresh report: fenced capacity admission;
//   - pressure-capable with a stale/missing report: EXCLUDED — a broken
//     publisher under a healthy heartbeat must not take unbounded
//     placements on legacy counts the fence can't see;
//   - not pressure-capable (legacy vmd): legacy least-loaded placement,
//     the controlled migration path for mixed fleets.
//
// The candidate set is cached exactly like LeastLoaded's (same TTL,
// stale-grace and fill-timeout contract — hostctl's drain convergence
// window budgets for those bounds); the only per-create database work
// is the single-statement reservation.
type CapacityAware struct {
	DB            *db.Queries
	DefaultHostID string // bootstrap fallback when no host rows exist
	// Region, when set, prefers candidates in the same region: hosts in
	// other regions are considered only when no same-region candidate is
	// eligible. Cells are region-scoped today, so this is usually a
	// no-op guard rather than an active choice.
	Region string
	TTL    time.Duration // 0 = use defaultCacheTTL
	// Observe, when set, receives one observation per placement.
	Observe func(PlacementObservation)

	mu         sync.RWMutex
	cache      map[string]capacityCacheEntry
	gen        uint64
	refreshing atomic.Bool
}

type capacityCacheEntry struct {
	rows     []db.ListCapacityCandidatesRow
	cachedAt time.Time
	// defaultStatus mirrors hostCacheEntry's: resolved at fill time only
	// when rows is empty, so the bootstrap-fallback decision never
	// queries on the per-create path.
	defaultStatus string
}

func (s *CapacityAware) ttl() time.Duration {
	if s.TTL > 0 {
		return s.TTL
	}
	return defaultCacheTTL
}

// Invalidate drops all cached candidate sets so the next placement
// reflects status or capability changes immediately.
func (s *CapacityAware) Invalidate() {
	s.mu.Lock()
	s.gen++
	s.cache = nil
	s.mu.Unlock()
}

func (s *CapacityAware) observe(obs PlacementObservation) {
	if s.Observe != nil {
		s.Observe(obs)
	}
}

// PlaceSandbox selects a host for the request and, on the capacity
// path, atomically reserves the headroom before returning.
func (s *CapacityAware) PlaceSandbox(ctx context.Context, req PlacementRequest) (Placement, error) {
	started := time.Now()
	placement, obs, err := s.place(ctx, req)
	obs.Duration = time.Since(started)
	s.observe(obs)
	return placement, err
}

func (s *CapacityAware) place(ctx context.Context, req PlacementRequest) (Placement, PlacementObservation, error) {
	entry, err := s.loadCandidates(ctx, req.RequiredCapabilities)
	if err != nil {
		return Placement{}, PlacementObservation{Mode: "capacity", Result: "error"}, err
	}

	rows := entry.rows
	if len(req.AllowedHosts) > 0 {
		allowed := make(map[string]bool, len(req.AllowedHosts))
		for _, id := range req.AllowedHosts {
			allowed[id] = true
		}
		filtered := rows[:0:0]
		for _, row := range rows {
			if allowed[row.ID] {
				filtered = append(filtered, row)
			}
		}
		rows = filtered
	}

	if len(rows) == 0 {
		return s.placeFallback(entry, req)
	}

	// Three-state partition (see the type comment). The freshness check
	// here compares a database timestamp against the local clock — fine
	// for pre-filtering because the admission statement re-checks
	// freshness authoritatively on the database clock alone.
	var eligible, legacy []db.ListCapacityCandidatesRow
	for _, row := range rows {
		switch {
		case !row.PressureCapable:
			legacy = append(legacy, row)
		case row.ReportedAt.Valid && time.Since(row.ReportedAt.Time) < PressureFreshnessSecs*time.Second:
			eligible = append(eligible, row)
		default:
			// Capable but stale/missing: fail closed, drop entirely.
		}
	}
	eligible = preferRegion(eligible, s.Region)
	legacy = preferRegion(legacy, s.Region)

	if len(eligible) > 0 {
		placement, obs, err := s.placeCapacity(ctx, req, eligible)
		if !errors.Is(err, errCapacityExhausted) {
			// Placed, or failed terminally (a database error during
			// admission): either way this is the answer. Only exhaustion
			// falls through.
			return placement, obs, err
		}
		// Every eligible host rejected the fence. Legacy hosts are
		// still a valid overflow target — they were valid before this
		// scheduler existed — but capable-stale hosts never are.
		if len(legacy) == 0 {
			return Placement{}, obs, fmt.Errorf("no host admitted the sandbox (capacity)")
		}
	}
	if len(legacy) > 0 {
		return s.placeLegacy(legacy)
	}
	return Placement{}, PlacementObservation{Mode: "capacity", Result: "no_hosts"},
		fmt.Errorf("no active hosts available for placement")
}

// errCapacityExhausted signals that every eligible host refused this
// create, so the caller may consider legacy overflow. Any other error is
// terminal for the placement.
var errCapacityExhausted = errors.New("capacity exhausted")

// placeCapacity runs the fenced admission over the ranked candidates.
func (s *CapacityAware) placeCapacity(ctx context.Context, req PlacementRequest, eligible []db.ListCapacityCandidatesRow) (Placement, PlacementObservation, error) {
	order := rankCandidates(eligible, req)
	obs := PlacementObservation{Mode: "capacity"}
	if len(order) == 0 {
		// The cached view already knew every eligible host was full, so
		// no statement ran. Report why anyway — an operator reading
		// "exhausted" needs to know whether the cell hit its sandbox cap
		// or ran out of network slots.
		obs.Result = "exhausted"
		obs.Reason = rejectionReason(eligible[0], req)
		return Placement{}, obs, errCapacityExhausted
	}
	for _, cand := range order {
		if obs.Attempts >= admissionMaxAttempts {
			break
		}
		obs.Attempts++
		_, err := s.DB.ReserveHostCapacity(ctx, db.ReserveHostCapacityParams{
			SandboxID:     req.SandboxID,
			MemoryMib:     int64(req.MemoryMib),
			Vcpus:         int64(req.Vcpus),
			HostID:        cand.ID,
			FreshnessSecs: PressureFreshnessSecs,
		})
		switch {
		case err == nil:
			obs.Result = "placed"
			return s.reservedPlacement(cand.ID, req.SandboxID), obs, nil
		case errors.Is(err, pgx.ErrNoRows):
			// The fence said no. Record why the CACHE thought it would
			// fit or not — approximate but label-bounded, and it never
			// costs a diagnostic query on the create path.
			if obs.Reason == "" {
				obs.Reason = rejectionReason(cand, req)
			}
			continue
		default:
			// Database failure: the create's own INSERT is about to hit
			// the same database, so failing the placement is honest.
			log.Error().Err(err).Str("host_id", cand.ID).Msg("capacity reservation failed")
			obs.Result = "error"
			return Placement{}, obs, fmt.Errorf("capacity reservation on %s: %w", cand.ID, err)
		}
	}
	obs.Result = "exhausted"
	return Placement{}, obs, errCapacityExhausted
}

func (s *CapacityAware) reservedPlacement(hostID string, sandboxID uuid.UUID) Placement {
	return Placement{
		HostID: hostID,
		Confirm: func(ctx context.Context) {
			// Failure tolerated: an unmaterialized row keeps charging
			// until lease expiry — transient under-placement, never
			// over-placement.
			if err := s.DB.MaterializeHostReservation(ctx, sandboxID); err != nil {
				log.Warn().Err(err).Str("sandbox_id", sandboxID.String()).
					Msg("materialize reservation failed; row retires at lease expiry")
			}
		},
		Abort: func(ctx context.Context) {
			if err := s.DB.ReleaseHostReservation(ctx, sandboxID); err != nil {
				log.Warn().Err(err).Str("sandbox_id", sandboxID.String()).
					Msg("release reservation failed; row retires at lease expiry")
			}
		},
	}
}

// placeLegacy is the controlled fallback for hosts that predate pressure
// publication: the same power-of-two-choices selection LeastLoaded uses,
// unfenced because there is nothing to fence against.
func (s *CapacityAware) placeLegacy(legacy []db.ListCapacityCandidatesRow) (Placement, PlacementObservation, error) {
	obs := PlacementObservation{Mode: "legacy", Result: "placed"}
	if len(legacy) == 1 {
		return Placement{HostID: legacy[0].ID}, obs, nil
	}
	a := rand.IntN(len(legacy))
	b := rand.IntN(len(legacy) - 1)
	if b >= a {
		b++
	}
	if legacy[a].ActiveSandboxCount <= legacy[b].ActiveSandboxCount {
		return Placement{HostID: legacy[a].ID}, obs, nil
	}
	return Placement{HostID: legacy[b].ID}, obs, nil
}

// placeFallback mirrors LeastLoaded's bootstrap semantics for an empty
// candidate set (see SelectHost): creation must work before the host
// table is populated, and must not route to a non-active default row.
func (s *CapacityAware) placeFallback(entry capacityCacheEntry, req PlacementRequest) (Placement, PlacementObservation, error) {
	obs := PlacementObservation{Mode: "fallback"}
	if len(req.AllowedHosts) > 0 {
		// A locality constraint that matches nothing is a hard miss —
		// the default host does not hold artifacts it was never
		// recorded as holding.
		obs.Result = "no_hosts"
		return Placement{}, obs, fmt.Errorf("no active host satisfies the placement constraint")
	}
	if s.DefaultHostID == "" {
		obs.Result = "no_hosts"
		return Placement{}, obs, fmt.Errorf("no active hosts available")
	}
	switch entry.defaultStatus {
	case "missing": // unpopulated table: bootstrap path
		obs.Result = "placed"
		return Placement{HostID: s.DefaultHostID}, obs, nil
	case "active":
		// Present but filtered out by capabilities; the create-time
		// capability gate still enforces. Preserves LeastLoaded behavior.
		obs.Result = "placed"
		return Placement{HostID: s.DefaultHostID}, obs, nil
	case "":
		obs.Result = "no_hosts"
		return Placement{}, obs, fmt.Errorf("no active hosts available")
	default:
		obs.Result = "no_hosts"
		return Placement{}, obs, fmt.Errorf("no active hosts available (default host is %s)", entry.defaultStatus)
	}
}

// preferRegion keeps only same-region rows when any exist; otherwise the
// full set stands (a remote-region host beats a failed create).
func preferRegion(rows []db.ListCapacityCandidatesRow, region string) []db.ListCapacityCandidatesRow {
	if region == "" || len(rows) == 0 {
		return rows
	}
	var local []db.ListCapacityCandidatesRow
	for _, row := range rows {
		if row.Region == region {
			local = append(local, row)
		}
	}
	if len(local) > 0 {
		return local
	}
	return rows
}

// rankCandidates orders eligible hosts for admission attempts:
// obviously-full hosts are dropped (the fence would reject them; skip
// the round trip), every survivor gets a dominant-pressure score, the
// tolerance band around the best score is shuffled uniformly (see
// pressureScoreTolerance for why the randomness is load-bearing), and
// out-of-band hosts follow in score order as overflow targets.
func rankCandidates(eligible []db.ListCapacityCandidatesRow, req PlacementRequest) []db.ListCapacityCandidatesRow {
	type scored struct {
		row   db.ListCapacityCandidatesRow
		score float64
	}
	candidates := make([]scored, 0, len(eligible))
	for _, row := range eligible {
		if !fitsCached(row, req) {
			continue
		}
		candidates = append(candidates, scored{row: row, score: dominantScore(row, req)})
	}
	if len(candidates) == 0 {
		return nil
	}
	best := candidates[0].score
	for _, c := range candidates[1:] {
		if c.score < best {
			best = c.score
		}
	}
	// Inside the band every host is an equally good target on pressure
	// grounds, so warm-slot availability decides — but only as a
	// partition, and each partition is shuffled: preferring warmth must
	// not reintroduce a deterministic first choice for every replica.
	var warmBand, coldBand, rest []scored
	for _, c := range candidates {
		switch {
		case c.score > best+pressureScoreTolerance:
			rest = append(rest, c)
		case hasWarmSlot(c.row):
			warmBand = append(warmBand, c)
		default:
			coldBand = append(coldBand, c)
		}
	}
	rand.Shuffle(len(warmBand), func(i, j int) { warmBand[i], warmBand[j] = warmBand[j], warmBand[i] })
	rand.Shuffle(len(coldBand), func(i, j int) { coldBand[i], coldBand[j] = coldBand[j], coldBand[i] })
	sort.SliceStable(rest, func(i, j int) bool { return rest[i].score < rest[j].score })

	out := make([]db.ListCapacityCandidatesRow, 0, len(candidates))
	for _, group := range [][]scored{warmBand, coldBand, rest} {
		for _, c := range group {
			out = append(out, c.row)
		}
	}
	return out
}

// fitsCached mirrors the admission statement's hard checks against the
// cached view: an attempt that the cache already knows would fail is a
// wasted round trip. The fence remains authoritative — this can be
// stale in both directions and that's fine.
func fitsCached(row db.ListCapacityCandidatesRow, req PlacementRequest) bool {
	if row.MaxSandboxes > 0 &&
		row.RunningSandboxes+row.ProvisioningSandboxes+row.PausedSandboxes+row.ChargedCount+1 > row.MaxSandboxes {
		return false
	}
	if lim := effectiveSlotLimit(row.MaxNetworkSlots, row.NetSlotCeiling); lim > 0 {
		netNew := row.ChargedCount + 1 - row.WarmNetSlots
		if netNew < 0 {
			netNew = 0
		}
		if row.UsedNetSlots+row.ProvisioningNetSlots+row.WarmNetSlots+netNew > lim {
			return false
		}
	}
	return true
}

// dominantScore is the host's worst pressure ratio across the four
// resource axes, with this request's own shape charged in, minus the
// warm-slot bonus when the warm pool can absorb this create. Memory and
// vcpu ratios may legitimately exceed 1.0 on overcommitted hosts —
// they're ordering signals, not limits.
func dominantScore(row db.ListCapacityCandidatesRow, req PlacementRequest) float64 {
	var score float64
	if row.MaxSandboxes > 0 {
		s := float64(row.RunningSandboxes+row.ProvisioningSandboxes+row.PausedSandboxes+row.ChargedCount+1) /
			float64(row.MaxSandboxes)
		score = max(score, s)
	}
	if lim := effectiveSlotLimit(row.MaxNetworkSlots, row.NetSlotCeiling); lim > 0 {
		netNew := row.ChargedCount + 1 - row.WarmNetSlots
		if netNew < 0 {
			netNew = 0
		}
		s := float64(row.UsedNetSlots+row.ProvisioningNetSlots+row.WarmNetSlots+netNew) / float64(lim)
		score = max(score, s)
	}
	if row.CapacityMemoryMib > 0 {
		s := float64(row.AllocatedMemoryMib+row.ChargedMemoryMib+int64(req.MemoryMib)) /
			float64(row.CapacityMemoryMib)
		score = max(score, s)
	}
	if row.CapacityVcpus > 0 {
		s := float64(row.AllocatedVcpus+row.ChargedVcpus+int64(req.Vcpus)) /
			float64(row.CapacityVcpus)
		score = max(score, s)
	}
	return score
}

// hasWarmSlot reports whether a warm, already-prepared network slot is
// available for THIS create even after every charged reservation ahead
// of it takes one. Used to order within the tolerance band, never to
// change the score: a create that lands on a warm slot skips slot
// provisioning, but warmth must not pull a more-loaded host ahead of a
// less-loaded one.
func hasWarmSlot(row db.ListCapacityCandidatesRow) bool {
	return row.WarmNetSlots > row.ChargedCount
}

func effectiveSlotLimit(maxSlots, ceiling int32) int32 {
	switch {
	case maxSlots > 0 && ceiling > 0:
		return min(maxSlots, ceiling)
	case maxSlots > 0:
		return maxSlots
	default:
		return ceiling
	}
}

// rejectionReason approximates why the fence rejected, from the cached
// numbers, for the bounded metric label. Never queries.
func rejectionReason(row db.ListCapacityCandidatesRow, req PlacementRequest) string {
	if row.MaxSandboxes > 0 &&
		row.RunningSandboxes+row.ProvisioningSandboxes+row.PausedSandboxes+row.ChargedCount+1 > row.MaxSandboxes {
		return "sandbox_limit"
	}
	if lim := effectiveSlotLimit(row.MaxNetworkSlots, row.NetSlotCeiling); lim > 0 {
		netNew := row.ChargedCount + 1 - row.WarmNetSlots
		if netNew < 0 {
			netNew = 0
		}
		if row.UsedNetSlots+row.ProvisioningNetSlots+row.WarmNetSlots+netNew > lim {
			return "slot_limit"
		}
	}
	return "raced"
}

// loadCandidates mirrors loadHosts' cache contract exactly (TTL, stale
// grace, bounded fills, generation fencing) over the capacity candidate
// query. See loadHosts for the rationale on each bound.
func (s *CapacityAware) loadCandidates(ctx context.Context, requiredCapabilities []string) (capacityCacheEntry, error) {
	key, normalized := capabilityCacheKey(requiredCapabilities)
	s.mu.RLock()
	entry, cached := s.cache[key]
	startGen := s.gen
	s.mu.RUnlock()

	if cached && time.Since(entry.cachedAt) >= s.ttl()+hostsStaleGrace {
		cached = false
	}
	if cached {
		if time.Since(entry.cachedAt) >= s.ttl() && s.refreshing.CompareAndSwap(false, true) {
			qctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), hostsFillTimeout)
			go func() {
				defer cancel()
				defer s.refreshing.Store(false)
				fresh, err := s.fillCandidates(qctx, normalized)
				if err != nil {
					log.Warn().Err(err).Strs("required_capabilities", normalized).
						Msg("capacity candidate refresh failed; serving stale until the grace window expires")
					return
				}
				s.mu.Lock()
				if s.gen == startGen {
					if s.cache == nil {
						s.cache = make(map[string]capacityCacheEntry)
					}
					s.cache[key] = fresh
				}
				s.mu.Unlock()
			}()
		}
		return entry, nil
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	if entry, ok := s.cache[key]; ok && time.Since(entry.cachedAt) < s.ttl()+hostsStaleGrace {
		return entry, nil
	}
	fillCtx, fillCancel := context.WithTimeout(ctx, hostsFillTimeout)
	fresh, err := s.fillCandidates(fillCtx, normalized)
	fillCancel()
	if err != nil {
		return capacityCacheEntry{}, err
	}
	s.gen++
	if s.cache == nil {
		s.cache = make(map[string]capacityCacheEntry)
	}
	s.cache[key] = fresh
	return fresh, nil
}

func (s *CapacityAware) fillCandidates(ctx context.Context, normalized []string) (capacityCacheEntry, error) {
	rows, err := s.DB.ListCapacityCandidates(ctx, db.ListCapacityCandidatesParams{
		PressureCapability:   HostCapabilityCapacityPressure,
		RequiredCapabilities: normalized,
	})
	if err != nil {
		return capacityCacheEntry{}, fmt.Errorf("list capacity candidates: %w", err)
	}
	entry := capacityCacheEntry{rows: rows, cachedAt: time.Now()}
	if len(rows) == 0 && s.DefaultHostID != "" {
		host, err := s.DB.GetHost(ctx, s.DefaultHostID)
		switch {
		case errors.Is(err, pgx.ErrNoRows):
			entry.defaultStatus = "missing"
		case err != nil:
			return capacityCacheEntry{}, fmt.Errorf("get default host %q: %w", s.DefaultHostID, err)
		default:
			entry.defaultStatus = host.Status
		}
	}
	return entry, nil
}
