// Package secrets is the qm-api's view of Secret Manager: named secrets
// scoped to one GCP project, addressed by short name. Values pass through
// this package only; they are never logged and never reach Postgres, which
// stores just the resource reference returned by Put.
package secrets

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"strings"
)

// ErrNotFound is returned by Get when the secret (or its latest version)
// does not exist. Delete on a missing secret is a no-op, not an error.
var ErrNotFound = errors.New("secret not found")

// Store is the narrow Secret Manager surface qm-api and the provisioner use.
type Store interface {
	// Put creates the secret if needed and adds value as its newest version.
	// It returns the resource reference to record in qm.tenant_secrets.
	Put(ctx context.Context, name string, value []byte) (ref string, err error)
	// Get reads the latest version.
	Get(ctx context.Context, name string) ([]byte, error)
	// Delete removes the secret and every version. Idempotent.
	Delete(ctx context.Context, name string) error
}

// Names of the per-tenant secrets. The model key is written by qm-api at
// create time (the Cloud Run Job's overrides are visible in execution
// metadata, so it must not travel there); the rest are generated by the
// provisioner's secrets step.
const (
	PortalSessionSecret = "PORTAL_SESSION_SECRET"
	modelKeySuffix      = "_API_KEY"
)

var nameRe = regexp.MustCompile(`^[A-Za-z0-9_-]{1,255}$`)

// TenantSecretName is the Secret Manager name for one of a tenant's
// secrets: qm-<slug>-<NAME>, e.g. qm-pilot-team-PORTAL_SESSION_SECRET.
func TenantSecretName(slug, name string) string {
	return "qm-" + slug + "-" + name
}

// ModelKeyName is the env-var-style name a tenant's model provider key is
// stored under: ANTHROPIC_API_KEY, OPENAI_API_KEY, OPENROUTER_API_KEY.
func ModelKeyName(provider string) string {
	return strings.ToUpper(provider) + modelKeySuffix
}

// ValidName rejects names Secret Manager would refuse before a call is made.
func ValidName(name string) error {
	if !nameRe.MatchString(name) {
		return fmt.Errorf("invalid secret name %q", name)
	}
	return nil
}
