// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createActivity = `-- name: CreateActivity :exec
INSERT INTO activity (vm_id, category, action, metadata)
VALUES ($1, $2, $3, $4)
`

type CreateActivityParams struct {
	VmID     uuid.UUID `json:"vm_id"`
	Category string    `json:"category"`
	Action   string    `json:"action"`
	Metadata []byte    `json:"metadata"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) error {
	_, err := q.db.Exec(ctx, createActivity,
		arg.VmID,
		arg.Category,
		arg.Action,
		arg.Metadata,
	)
	return err
}
