// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activity (sandbox_id, team_id, actor_id, category, action, status, sandbox_name, duration_ms, error, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, sandbox_id, team_id, actor_id, category, action, status, sandbox_name, duration_ms, error, metadata, created_at
`

type CreateActivityParams struct {
	SandboxID   uuid.UUID   `json:"sandbox_id"`
	TeamID      uuid.UUID   `json:"team_id"`
	ActorID     pgtype.UUID `json:"actor_id"`
	Category    string      `json:"category"`
	Action      string      `json:"action"`
	Status      *string     `json:"status"`
	SandboxName *string     `json:"sandbox_name"`
	DurationMs  *int32      `json:"duration_ms"`
	Error       *string     `json:"error"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.SandboxID,
		arg.TeamID,
		arg.ActorID,
		arg.Category,
		arg.Action,
		arg.Status,
		arg.SandboxName,
		arg.DurationMs,
		arg.Error,
		arg.Metadata,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.SandboxID,
		&i.TeamID,
		&i.ActorID,
		&i.Category,
		&i.Action,
		&i.Status,
		&i.SandboxName,
		&i.DurationMs,
		&i.Error,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityByCategory = `-- name: ListActivityByCategory :many
SELECT id, sandbox_id, team_id, actor_id, category, action, status, sandbox_name, duration_ms, error, metadata, created_at FROM activity
WHERE team_id = $1 AND category = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListActivityByCategoryParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	Category string    `json:"category"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListActivityByCategory(ctx context.Context, arg ListActivityByCategoryParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivityByCategory, arg.TeamID, arg.Category, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.SandboxID,
			&i.TeamID,
			&i.ActorID,
			&i.Category,
			&i.Action,
			&i.Status,
			&i.SandboxName,
			&i.DurationMs,
			&i.Error,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityBySandbox = `-- name: ListActivityBySandbox :many
SELECT id, sandbox_id, team_id, actor_id, category, action, status, sandbox_name, duration_ms, error, metadata, created_at FROM activity
WHERE sandbox_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListActivityBySandboxParams struct {
	SandboxID uuid.UUID `json:"sandbox_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListActivityBySandbox(ctx context.Context, arg ListActivityBySandboxParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivityBySandbox, arg.SandboxID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.SandboxID,
			&i.TeamID,
			&i.ActorID,
			&i.Category,
			&i.Action,
			&i.Status,
			&i.SandboxName,
			&i.DurationMs,
			&i.Error,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityByTeam = `-- name: ListActivityByTeam :many
SELECT id, sandbox_id, team_id, actor_id, category, action, status, sandbox_name, duration_ms, error, metadata, created_at FROM activity
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListActivityByTeamParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListActivityByTeam(ctx context.Context, arg ListActivityByTeamParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivityByTeam, arg.TeamID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.SandboxID,
			&i.TeamID,
			&i.ActorID,
			&i.Category,
			&i.Action,
			&i.Status,
			&i.SandboxName,
			&i.DurationMs,
			&i.Error,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
