// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backups.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const latestSandboxBackup = `-- name: LatestSandboxBackup :one
SELECT generation, bucket, completed_at
FROM backup_generation
WHERE sandbox_id = $1
ORDER BY completed_at DESC
LIMIT 1
`

type LatestSandboxBackupRow struct {
	Generation  string    `json:"generation"`
	Bucket      string    `json:"bucket"`
	CompletedAt time.Time `json:"completed_at"`
}

func (q *Queries) LatestSandboxBackup(ctx context.Context, sandboxID pgtype.UUID) (LatestSandboxBackupRow, error) {
	row := q.db.QueryRow(ctx, latestSandboxBackup, sandboxID)
	var i LatestSandboxBackupRow
	err := row.Scan(&i.Generation, &i.Bucket, &i.CompletedAt)
	return i, err
}

const latestSnapshotVMState = `-- name: LatestSnapshotVMState :one
SELECT s.id AS snapshot_id,
       COALESCE((SELECT am.sha256 FROM artifact_manifest am
         WHERE am.snapshot_id = s.id AND am.file_name = 'vmstate.snap'), '') AS vmstate_sha256
FROM snapshot s
WHERE s.sandbox_id = $1
ORDER BY s.generation DESC
LIMIT 1
`

type LatestSnapshotVMStateRow struct {
	SnapshotID    uuid.UUID   `json:"snapshot_id"`
	VmstateSha256 interface{} `json:"vmstate_sha256"`
}

// The sandbox's newest snapshot row and the vmstate digest its pause-time
// manifest recorded. The digest is the join point between a backup report
// and the snapshot row it describes: pause-time manifests are
// vmstate-only, so a matching vmstate sha proves the report covers
// exactly this pause.
func (q *Queries) LatestSnapshotVMState(ctx context.Context, sandboxID uuid.UUID) (LatestSnapshotVMStateRow, error) {
	row := q.db.QueryRow(ctx, latestSnapshotVMState, sandboxID)
	var i LatestSnapshotVMStateRow
	err := row.Scan(&i.SnapshotID, &i.VmstateSha256)
	return i, err
}

const lockSandboxRow = `-- name: LockSandboxRow :one
SELECT id FROM sandbox WHERE id = $1 FOR UPDATE
`

// Serializes the backup report's snapshot-size sync against FinalizePause,
// which takes the same row lock: the vmstate match below stays true for
// the duration of the transaction or the sync is skipped.
func (q *Queries) LockSandboxRow(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockSandboxRow, id)
	err := row.Scan(&id)
	return id, err
}

const recordSandboxBackupGeneration = `-- name: RecordSandboxBackupGeneration :execrows
INSERT INTO backup_generation (sandbox_id, generation, bucket, completed_at, files)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (sandbox_id, bucket, generation) WHERE sandbox_id IS NOT NULL
DO UPDATE SET completed_at = excluded.completed_at, reported_at = now()
WHERE excluded.completed_at > backup_generation.completed_at
`

type RecordSandboxBackupGenerationParams struct {
	SandboxID   pgtype.UUID `json:"sandbox_id"`
	Generation  string      `json:"generation"`
	Bucket      string      `json:"bucket"`
	CompletedAt time.Time   `json:"completed_at"`
	Files       []byte      `json:"files"`
}

// Idempotent by construction: reports are delivered at least once from
// the host's outbox. A conflict refreshes completed_at only when the
// report carries a strictly newer verification (an unchanged re-pause
// re-verifies the same content-addressed generation later, and
// freshness checks must see the current pause as covered), so an exact
// redelivery affects zero rows.
func (q *Queries) RecordSandboxBackupGeneration(ctx context.Context, arg RecordSandboxBackupGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordSandboxBackupGeneration,
		arg.SandboxID,
		arg.Generation,
		arg.Bucket,
		arg.CompletedAt,
		arg.Files,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordTemplateBackupGeneration = `-- name: RecordTemplateBackupGeneration :execrows
INSERT INTO backup_generation (template_id, build_id, generation, bucket, completed_at, files)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (template_id, build_id, bucket, generation) WHERE template_id IS NOT NULL
DO UPDATE SET completed_at = excluded.completed_at, reported_at = now()
WHERE excluded.completed_at > backup_generation.completed_at
`

type RecordTemplateBackupGenerationParams struct {
	TemplateID  pgtype.UUID `json:"template_id"`
	BuildID     *string     `json:"build_id"`
	Generation  string      `json:"generation"`
	Bucket      string      `json:"bucket"`
	CompletedAt time.Time   `json:"completed_at"`
	Files       []byte      `json:"files"`
}

// Template variant of RecordSandboxBackupGeneration; the two exist
// because each conflict target must name its own partial unique index.
func (q *Queries) RecordTemplateBackupGeneration(ctx context.Context, arg RecordTemplateBackupGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordTemplateBackupGeneration,
		arg.TemplateID,
		arg.BuildID,
		arg.Generation,
		arg.Bucket,
		arg.CompletedAt,
		arg.Files,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSnapshotSizeBytes = `-- name: SetSnapshotSizeBytes :exec
UPDATE snapshot SET size_bytes = $2 WHERE id = $1
`

type SetSnapshotSizeBytesParams struct {
	ID        uuid.UUID `json:"id"`
	SizeBytes int64     `json:"size_bytes"`
}

func (q *Queries) SetSnapshotSizeBytes(ctx context.Context, arg SetSnapshotSizeBytesParams) error {
	_, err := q.db.Exec(ctx, setSnapshotSizeBytes, arg.ID, arg.SizeBytes)
	return err
}
