// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backups.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimBackupGenerationsToPurge = `-- name: ClaimBackupGenerationsToPurge :many
WITH due AS (
  SELECT bg.id
  FROM backup_generation bg
  JOIN sandbox s ON s.id = bg.sandbox_id
  WHERE bg.bucket = $1::text
    AND s.status = 'deleted'
    AND bg.purged_at IS NULL
    AND (bg.purge_claimed_at IS NULL
         OR bg.purge_claimed_at < now() - make_interval(secs => $2::float8))
  ORDER BY s.destroyed_at ASC
  LIMIT $3
  FOR UPDATE OF bg SKIP LOCKED
)
UPDATE backup_generation bg
SET purge_claimed_at = clock_timestamp()
FROM due
WHERE bg.id = due.id
RETURNING bg.id, bg.sandbox_id, bg.generation, bg.purge_claimed_at AS claimed_at
`

type ClaimBackupGenerationsToPurgeParams struct {
	Bucket       string  `json:"bucket"`
	LeaseSeconds float64 `json:"lease_seconds"`
	BatchSize    int32   `json:"batch_size"`
}

type ClaimBackupGenerationsToPurgeRow struct {
	ID         uuid.UUID          `json:"id"`
	SandboxID  pgtype.UUID        `json:"sandbox_id"`
	Generation string             `json:"generation"`
	ClaimedAt  pgtype.Timestamptz `json:"claimed_at"`
}

// Leases this bucket's generations of deleted sandboxes to one purge worker
// at a time. A claim older than the lease belongs to a worker that died and
// may be taken over. The claim time is the worker's token: finishing the
// purge requires it unchanged, and a report landing meanwhile clears it.
func (q *Queries) ClaimBackupGenerationsToPurge(ctx context.Context, arg ClaimBackupGenerationsToPurgeParams) ([]ClaimBackupGenerationsToPurgeRow, error) {
	rows, err := q.db.Query(ctx, claimBackupGenerationsToPurge, arg.Bucket, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimBackupGenerationsToPurgeRow{}
	for rows.Next() {
		var i ClaimBackupGenerationsToPurgeRow
		if err := rows.Scan(
			&i.ID,
			&i.SandboxID,
			&i.Generation,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimBackupWalk = `-- name: ClaimBackupWalk :execrows
INSERT INTO backup_walk (bucket, started_at)
VALUES ($1, now())
ON CONFLICT (bucket) DO UPDATE SET started_at = now()
WHERE backup_walk.started_at < now() - make_interval(secs => $2::float8)
`

type ClaimBackupWalkParams struct {
	Bucket          string  `json:"bucket"`
	IntervalSeconds float64 `json:"interval_seconds"`
}

// Takes the bucket's walk for this interval; zero rows means another
// replica started one within the interval. A walk that died keeps its claim
// until the interval passes and is simply taken next time.
func (q *Queries) ClaimBackupWalk(ctx context.Context, arg ClaimBackupWalkParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimBackupWalk, arg.Bucket, arg.IntervalSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const coveredBackupGeneration = `-- name: CoveredBackupGeneration :one
SELECT COALESCE(bg.generation, '')::text AS generation
FROM sandbox sb
JOIN snapshot s ON s.id = sb.snapshot_id
LEFT JOIN LATERAL (
  SELECT generation FROM backup_generation
  WHERE covered_snapshot_id = s.id AND covered_snapshot_generation = s.generation
    AND purged_at IS NULL
  ORDER BY completed_at DESC LIMIT 1
) bg ON true
WHERE sb.id = $1
`

// The backup generation recorded as covering the sandbox's current pause,
// exactly: the snapshot row and its generation counter, since the row is
// reused across pauses. Empty when the pause has no completed backup.
func (q *Queries) CoveredBackupGeneration(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, coveredBackupGeneration, id)
	var generation string
	err := row.Scan(&generation)
	return generation, err
}

const inUseBasePaths = `-- name: InUseBasePaths :many
SELECT DISTINCT base_path::text AS base_path FROM sandbox WHERE destroyed_at IS NULL AND base_path IS NOT NULL
UNION
SELECT DISTINCT base_path::text FROM template WHERE deleted_at IS NULL AND base_path IS NOT NULL
UNION
SELECT DISTINCT base_path::text FROM sandbox_snapshot WHERE deleted_at IS NULL AND status IN ('creating', 'ready')
`

// Base images a future pause can name: those of live sandboxes, of existing
// template builds, and of live saved snapshots, which fork new sandboxes
// from them. Same holders as ListPinnedBuildPaths, plus templates.
func (q *Queries) InUseBasePaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, inUseBasePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var base_path string
		if err := rows.Scan(&base_path); err != nil {
			return nil, err
		}
		items = append(items, base_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestSandboxBackup = `-- name: LatestSandboxBackup :one
SELECT generation, bucket, LEAST(completed_at, reported_at)::timestamptz AS completed_at
FROM (
  SELECT generation, bucket, completed_at, reported_at,
    CASE WHEN completed_at > reported_at
      THEN MIN(reported_at) FILTER (WHERE completed_at > reported_at) OVER ()
      ELSE completed_at END AS effective_at
  FROM backup_generation
  WHERE sandbox_id = $1 AND purged_at IS NULL
) ranked
ORDER BY effective_at DESC, completed_at DESC
LIMIT 1
`

type LatestSandboxBackupRow struct {
	Generation  string    `json:"generation"`
	Bucket      string    `json:"bucket"`
	CompletedAt time.Time `json:"completed_at"`
}

// Freshness bounds future timestamps at read instead of rewriting them
// at insert: completed_at is stored exactly as the host verified it, so
// redeliveries stay idempotent under the strictly-newer upsert guard.
// The cap is reported_at, the server-side receive instant fixed at
// insert: a skewed-ahead row ranks no later than when the control plane
// actually learned of it, so any subsequently completed legitimate
// generation outranks it (a now() cap would keep tying the skewed row
// to the query clock and it would win every read until wall time passed
// the stamp). The returned completed_at is bounded the same way so
// freshness consumers never see an unbounded future value; the raw
// column breaks ranking ties, preserving the host's own order.
// Future-stamped rows (completed_at > reported_at) all rank at the
// sandbox's EARLIEST future receive instant rather than each at its
// own, so their order among themselves comes from the raw tie-break
// (the host's own clock) instead of delivery order, while the class
// still cannot outrank any legitimately later completion.
func (q *Queries) LatestSandboxBackup(ctx context.Context, sandboxID pgtype.UUID) (LatestSandboxBackupRow, error) {
	row := q.db.QueryRow(ctx, latestSandboxBackup, sandboxID)
	var i LatestSandboxBackupRow
	err := row.Scan(&i.Generation, &i.Bucket, &i.CompletedAt)
	return i, err
}

const latestSnapshotManifest = `-- name: LatestSnapshotManifest :many
SELECT s.id AS snapshot_id, s.generation AS snapshot_generation,
       COALESCE(s.pause_token, '') AS pause_token, am.file_name, am.sha256
FROM snapshot s
JOIN artifact_manifest am ON am.snapshot_id = s.id
WHERE s.sandbox_id = $1
  AND s.generation = (SELECT MAX(generation) FROM snapshot WHERE sandbox_id = $1)
ORDER BY am.file_name
`

type LatestSnapshotManifestRow struct {
	SnapshotID         uuid.UUID `json:"snapshot_id"`
	SnapshotGeneration int64     `json:"snapshot_generation"`
	PauseToken         string    `json:"pause_token"`
	FileName           string    `json:"file_name"`
	Sha256             string    `json:"sha256"`
}

// The sandbox's newest snapshot row with every digest its pause-time
// manifest recorded. The full recorded set is the join point between a
// backup report and the snapshot row it describes: vmstate alone is not
// a unique pause identity (identical vmstate bytes with different disk
// contents are possible), so the report must match EVERY recorded row.
// Pause-time manifests are vmstate-only today; rows tighten the match
// automatically as richer manifests appear.
func (q *Queries) LatestSnapshotManifest(ctx context.Context, sandboxID uuid.UUID) ([]LatestSnapshotManifestRow, error) {
	rows, err := q.db.Query(ctx, latestSnapshotManifest, sandboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestSnapshotManifestRow{}
	for rows.Next() {
		var i LatestSnapshotManifestRow
		if err := rows.Scan(
			&i.SnapshotID,
			&i.SnapshotGeneration,
			&i.PauseToken,
			&i.FileName,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSandboxRow = `-- name: LockSandboxRow :one
SELECT id, status, updated_at, pause_op_id
FROM sandbox WHERE id = $1 FOR UPDATE
`

type LockSandboxRowRow struct {
	ID        uuid.UUID     `json:"id"`
	Status    SandboxStatus `json:"status"`
	UpdatedAt time.Time     `json:"updated_at"`
	PauseOpID pgtype.UUID   `json:"pause_op_id"`
}

// Serializes the backup report's snapshot-size sync against FinalizePause,
// which takes the same row lock: the vmstate match below stays true for
// the duration of the transaction or the sync is skipped. Status rides
// along because 'pausing' marks a finalize that has not committed yet:
// a fast upload's report arriving in that window must retry rather than
// silently miss its size sync. A pause operation on the row says the
// transition is still being worked (see finalizeInFlight).
func (q *Queries) LockSandboxRow(ctx context.Context, id uuid.UUID) (LockSandboxRowRow, error) {
	row := q.db.QueryRow(ctx, lockSandboxRow, id)
	var i LockSandboxRowRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UpdatedAt,
		&i.PauseOpID,
	)
	return i, err
}

const markBackupGenerationPurged = `-- name: MarkBackupGenerationPurged :execrows
UPDATE backup_generation
SET purged_at = now(), purge_claimed_at = NULL
WHERE id = $1 AND purge_claimed_at = $2
`

type MarkBackupGenerationPurgedParams struct {
	ID        uuid.UUID          `json:"id"`
	ClaimedAt pgtype.Timestamptz `json:"claimed_at"`
}

// Zero rows means the claim was cleared by a report that landed during the
// purge: the generation was uploaded again and is left for the next pass.
func (q *Queries) MarkBackupGenerationPurged(ctx context.Context, arg MarkBackupGenerationPurgedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBackupGenerationPurged, arg.ID, arg.ClaimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSandboxBackupCovered = `-- name: MarkSandboxBackupCovered :exec
UPDATE backup_generation
SET covered_snapshot_id = $1,
    covered_snapshot_generation = $2
WHERE sandbox_id = $3
  AND bucket = $4
  AND generation = $5
`

type MarkSandboxBackupCoveredParams struct {
	SnapshotID         pgtype.UUID `json:"snapshot_id"`
	SnapshotGeneration *int64      `json:"snapshot_generation"`
	SandboxID          pgtype.UUID `json:"sandbox_id"`
	Bucket             string      `json:"bucket"`
	Generation         string      `json:"generation"`
}

// Persists the report handler's identity verdict, verified under the
// sandbox row lock: either the report's pause_token equals the head
// snapshot's (STRONG — names the exact pause), or a tokenless report's
// manifest matched every recorded digest (legacy fallback).
// (snapshot_id, snapshot_generation) names the exact pause — the
// generation counter distinguishes pauses even while the legacy
// finalize reuses one snapshot row id. Written in the report's
// transaction, so the coverage row and its identity link commit
// together.
func (q *Queries) MarkSandboxBackupCovered(ctx context.Context, arg MarkSandboxBackupCoveredParams) error {
	_, err := q.db.Exec(ctx, markSandboxBackupCovered,
		arg.SnapshotID,
		arg.SnapshotGeneration,
		arg.SandboxID,
		arg.Bucket,
		arg.Generation,
	)
	return err
}

const oldestRecordedBackup = `-- name: OldestRecordedBackup :one
SELECT reported_at
FROM backup_generation
WHERE bucket = $1
ORDER BY reported_at ASC
LIMIT 1
`

// When the database began recording this bucket's generations; a base
// object older than this may be referenced by a generation it never saw.
func (q *Queries) OldestRecordedBackup(ctx context.Context, bucket string) (time.Time, error) {
	row := q.db.QueryRow(ctx, oldestRecordedBackup, bucket)
	var reported_at time.Time
	err := row.Scan(&reported_at)
	return reported_at, err
}

const recordSandboxBackupGeneration = `-- name: RecordSandboxBackupGeneration :execrows
INSERT INTO backup_generation (sandbox_id, generation, bucket, completed_at, files)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (sandbox_id, bucket, generation) WHERE sandbox_id IS NOT NULL
DO UPDATE SET
  -- A generation uploaded again after its purge (a host's queued upload
  -- landing late) is purged again.
  purged_at = NULL,
  purge_claimed_at = NULL,
  -- reported_at is the receive-instant freshness cap for skew-bounded
  -- reads, so it moves only when a freshness arm fires: an
  -- enrichment-only update re-describes the same verification and must
  -- not advance when the control plane first learned of it.
  reported_at = CASE
    WHEN excluded.completed_at > backup_generation.completed_at
         OR (backup_generation.completed_at > now()
             AND excluded.completed_at < backup_generation.completed_at)
      THEN now()
    ELSE backup_generation.reported_at END,
  completed_at = CASE
    WHEN excluded.completed_at > backup_generation.completed_at
      THEN excluded.completed_at
    WHEN backup_generation.completed_at > now()
         AND excluded.completed_at < backup_generation.completed_at
      THEN excluded.completed_at
    ELSE backup_generation.completed_at END,
  -- files, in order: a coverage-only report (empty files: the outbox
  -- seed reconstructs no manifest) must never erase a recorded
  -- manifest; a manifest that carries object paths is frozen (the
  -- bucket manifest it mirrors is immutable, redeliveries carry the
  -- identical set, and nothing conforming can legitimately rename a
  -- generation's objects, so first-writer-wins is what keeps the paths
  -- deletion-trustworthy for GC); anything richer refreshes.
  files = CASE
    WHEN jsonb_array_length(excluded.files) = 0
      THEN backup_generation.files
    WHEN jsonb_path_exists(backup_generation.files, '$[*].object')
      THEN backup_generation.files
    ELSE excluded.files END
WHERE excluded.completed_at > backup_generation.completed_at
   OR (backup_generation.completed_at > now() AND excluded.completed_at < backup_generation.completed_at)
   OR (jsonb_path_exists(excluded.files, '$[*].object')
       AND NOT jsonb_path_exists(backup_generation.files, '$[*].object'))
   -- Any report for a purged or purge-claimed generation, an exact
   -- redelivery included, comes from a host that holds its objects: the
   -- purge must run again.
   OR backup_generation.purged_at IS NOT NULL
   OR backup_generation.purge_claimed_at IS NOT NULL
`

type RecordSandboxBackupGenerationParams struct {
	SandboxID   pgtype.UUID `json:"sandbox_id"`
	Generation  string      `json:"generation"`
	Bucket      string      `json:"bucket"`
	CompletedAt time.Time   `json:"completed_at"`
	Files       []byte      `json:"files"`
}

// Idempotent by construction: reports are delivered at least once from
// the host's outbox. A conflict refreshes completed_at only when the
// report carries a strictly newer verification (an unchanged re-pause
// re-verifies the same content-addressed generation later, and
// freshness checks must see the current pause as covered), so an exact
// redelivery affects zero rows. The second refresh arm lets a corrected
// clock repair its own damage: a stored future value (provably bogus,
// it exceeds now()) yields to ANY smaller incoming one, sane or merely
// less skewed, so repair is monotone even when the correction lands
// while some skew remains; redelivery of either report matches neither
// arm and stays a no-op. The third arm lets a report carrying object
// paths enrich a row that lacks them regardless of freshness: a
// rollout-window fallback can land a pathless copy of the same
// verification first (same pinned instant, so the freshness arms never
// fire for the redelivery), and the paths are what a lifecycle GC
// reasons from. Enrichment leaves completed_at where it stands (the
// CASE below): an older rich redelivery must not regress freshness.
func (q *Queries) RecordSandboxBackupGeneration(ctx context.Context, arg RecordSandboxBackupGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordSandboxBackupGeneration,
		arg.SandboxID,
		arg.Generation,
		arg.Bucket,
		arg.CompletedAt,
		arg.Files,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordTemplateBackupGeneration = `-- name: RecordTemplateBackupGeneration :execrows
INSERT INTO backup_generation (template_id, build_id, generation, bucket, completed_at, files)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (template_id, build_id, bucket, generation) WHERE template_id IS NOT NULL
DO UPDATE SET
  reported_at = CASE
    WHEN excluded.completed_at > backup_generation.completed_at
         OR (backup_generation.completed_at > now()
             AND excluded.completed_at < backup_generation.completed_at)
      THEN now()
    ELSE backup_generation.reported_at END,
  completed_at = CASE
    WHEN excluded.completed_at > backup_generation.completed_at
      THEN excluded.completed_at
    WHEN backup_generation.completed_at > now()
         AND excluded.completed_at < backup_generation.completed_at
      THEN excluded.completed_at
    ELSE backup_generation.completed_at END,
  files = CASE
    WHEN jsonb_array_length(excluded.files) = 0
      THEN backup_generation.files
    WHEN jsonb_path_exists(backup_generation.files, '$[*].object')
      THEN backup_generation.files
    ELSE excluded.files END
WHERE excluded.completed_at > backup_generation.completed_at
   OR (backup_generation.completed_at > now() AND excluded.completed_at < backup_generation.completed_at)
   OR (jsonb_path_exists(excluded.files, '$[*].object')
       AND NOT jsonb_path_exists(backup_generation.files, '$[*].object'))
`

type RecordTemplateBackupGenerationParams struct {
	TemplateID  pgtype.UUID `json:"template_id"`
	BuildID     *string     `json:"build_id"`
	Generation  string      `json:"generation"`
	Bucket      string      `json:"bucket"`
	CompletedAt time.Time   `json:"completed_at"`
	Files       []byte      `json:"files"`
}

// Template variant of RecordSandboxBackupGeneration; the two exist
// because each conflict target must name its own partial unique index.
func (q *Queries) RecordTemplateBackupGeneration(ctx context.Context, arg RecordTemplateBackupGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordTemplateBackupGeneration,
		arg.TemplateID,
		arg.BuildID,
		arg.Generation,
		arg.Bucket,
		arg.CompletedAt,
		arg.Files,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordedGenerations = `-- name: RecordedGenerations :many
SELECT sandbox_id, generation
FROM backup_generation
WHERE bucket = $1 AND sandbox_id IS NOT NULL AND purged_at IS NULL
`

type RecordedGenerationsRow struct {
	SandboxID  pgtype.UUID `json:"sandbox_id"`
	Generation string      `json:"generation"`
}

// The unpurged generations the database knows in this bucket; a complete
// bucket generation outside this set was never reported, or was purged
// and uploaded again, and either way its owner decides its fate.
func (q *Queries) RecordedGenerations(ctx context.Context, bucket string) ([]RecordedGenerationsRow, error) {
	rows, err := q.db.Query(ctx, recordedGenerations, bucket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecordedGenerationsRow{}
	for rows.Next() {
		var i RecordedGenerationsRow
		if err := rows.Scan(&i.SandboxID, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordedSharedBasePaths = `-- name: RecordedSharedBasePaths :many
SELECT DISTINCT (f->>'base_sha256')::text AS sha256, s.base_path::text AS base_path
FROM backup_generation bg
JOIN sandbox s ON s.id = bg.sandbox_id, jsonb_array_elements(bg.files) f
WHERE bg.bucket = $1::text
  AND coalesce(f->>'base_sha256', '') <> ''
  AND s.base_path IS NOT NULL
`

type RecordedSharedBasePathsRow struct {
	Sha256   string `json:"sha256"`
	BasePath string `json:"base_path"`
}

// Which base image each shared base digest was recorded for, from the
// sandboxes whose generations named it. A digest with no row here has
// unknown provenance.
func (q *Queries) RecordedSharedBasePaths(ctx context.Context, bucket string) ([]RecordedSharedBasePathsRow, error) {
	rows, err := q.db.Query(ctx, recordedSharedBasePaths, bucket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecordedSharedBasePathsRow{}
	for rows.Next() {
		var i RecordedSharedBasePathsRow
		if err := rows.Scan(&i.Sha256, &i.BasePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const referencedSharedBases = `-- name: ReferencedSharedBases :many
SELECT DISTINCT (f->>'base_sha256')::text AS sha256
FROM backup_generation bg, jsonb_array_elements(bg.files) f
WHERE bg.bucket = $1::text
  AND coalesce(f->>'base_sha256', '') <> ''
  AND (bg.purged_at IS NULL
       OR greatest(bg.reported_at, bg.purged_at) > now() - make_interval(secs => $2::float8))
`

type ReferencedSharedBasesParams struct {
	Bucket       string  `json:"bucket"`
	GraceSeconds float64 `json:"grace_seconds"`
}

// The shared base digests named by a generation that can still be
// restored, or by one reported or purged within the grace period: hosts
// skip re-uploading a base they verified that recently and a new generation
// may name it without shipping it. Judged by server time, never the host's
// clock.
func (q *Queries) ReferencedSharedBases(ctx context.Context, arg ReferencedSharedBasesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, referencedSharedBases, arg.Bucket, arg.GraceSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var sha256 string
		if err := rows.Scan(&sha256); err != nil {
			return nil, err
		}
		items = append(items, sha256)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSnapshotSizeBytes = `-- name: SetSnapshotSizeBytes :exec
UPDATE snapshot SET size_bytes = $2 WHERE id = $1
`

type SetSnapshotSizeBytesParams struct {
	ID        uuid.UUID `json:"id"`
	SizeBytes int64     `json:"size_bytes"`
}

func (q *Queries) SetSnapshotSizeBytes(ctx context.Context, arg SetSnapshotSizeBytesParams) error {
	_, err := q.db.Exec(ctx, setSnapshotSizeBytes, arg.ID, arg.SizeBytes)
	return err
}
