// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyTeamCreditGrant = `-- name: ApplyTeamCreditGrant :one
UPDATE team_credit_grant
SET remaining_usd = remaining_usd - $1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND $1 > 0
  AND remaining_usd >= $1
  AND (expires_at IS NULL OR expires_at > now())
RETURNING id, team_id, amount_usd, remaining_usd, currency, reason, expires_at, created_by, created_at, updated_at
`

type ApplyTeamCreditGrantParams struct {
	AmountUsd pgtype.Numeric `json:"amount_usd"`
	GrantID   uuid.UUID      `json:"grant_id"`
	TeamID    uuid.UUID      `json:"team_id"`
}

func (q *Queries) ApplyTeamCreditGrant(ctx context.Context, arg ApplyTeamCreditGrantParams) (TeamCreditGrant, error) {
	row := q.db.QueryRow(ctx, applyTeamCreditGrant, arg.AmountUsd, arg.GrantID, arg.TeamID)
	var i TeamCreditGrant
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AmountUsd,
		&i.RemainingUsd,
		&i.Currency,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const approveTeamBillingPeriod = `-- name: ApproveTeamBillingPeriod :one
UPDATE team_billing_period
SET status = 'approved',
    approved_by = $1,
    approved_at = now(),
    blocked_reason = NULL,
    blocked_at = NULL,
    updated_at = now()
WHERE team_billing_period.team_id = $2
  AND team_billing_period.period_start = $3
  AND team_billing_period.period_end = $4
  AND team_billing_period.status IN ('validating', 'blocked')
  AND team_billing_period.finalized_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM billing_period_anomaly a
      WHERE a.team_id = team_billing_period.team_id
        AND a.period_start = team_billing_period.period_start
        AND a.period_end = team_billing_period.period_end
        AND a.resolved_at IS NULL
        AND a.severity IN ('error', 'critical')
  )
RETURNING team_id, period_start, period_end, status, blocked_reason, blocked_at, approved_by, approved_at, exported_at, finalized_at, created_at, updated_at, gross_charges_usd, credits_applied_usd, net_invoice_amount_usd
`

type ApproveTeamBillingPeriodParams struct {
	ApprovedBy  pgtype.UUID `json:"approved_by"`
	TeamID      uuid.UUID   `json:"team_id"`
	PeriodStart time.Time   `json:"period_start"`
	PeriodEnd   time.Time   `json:"period_end"`
}

func (q *Queries) ApproveTeamBillingPeriod(ctx context.Context, arg ApproveTeamBillingPeriodParams) (TeamBillingPeriod, error) {
	row := q.db.QueryRow(ctx, approveTeamBillingPeriod,
		arg.ApprovedBy,
		arg.TeamID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var i TeamBillingPeriod
	err := row.Scan(
		&i.TeamID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.BlockedReason,
		&i.BlockedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ExportedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GrossChargesUsd,
		&i.CreditsAppliedUsd,
		&i.NetInvoiceAmountUsd,
	)
	return i, err
}

const assignTeamPricingPlan = `-- name: AssignTeamPricingPlan :one
INSERT INTO team_pricing_plan (team_id, plan_key, effective_from, effective_to, assigned_by)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING team_id, plan_key, effective_from, effective_to, assigned_by, created_at
`

type AssignTeamPricingPlanParams struct {
	TeamID        uuid.UUID          `json:"team_id"`
	PlanKey       string             `json:"plan_key"`
	EffectiveFrom time.Time          `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	AssignedBy    pgtype.UUID        `json:"assigned_by"`
}

func (q *Queries) AssignTeamPricingPlan(ctx context.Context, arg AssignTeamPricingPlanParams) (TeamPricingPlan, error) {
	row := q.db.QueryRow(ctx, assignTeamPricingPlan,
		arg.TeamID,
		arg.PlanKey,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.AssignedBy,
	)
	var i TeamPricingPlan
	err := row.Scan(
		&i.TeamID,
		&i.PlanKey,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.AssignedBy,
		&i.CreatedAt,
	)
	return i, err
}

const blockTeamBillingPeriod = `-- name: BlockTeamBillingPeriod :one
UPDATE team_billing_period
SET status = 'blocked',
    blocked_reason = $1,
    blocked_at = now(),
    updated_at = now()
WHERE team_billing_period.team_id = $2
  AND team_billing_period.period_start = $3
  AND team_billing_period.period_end = $4
  AND team_billing_period.status IN ('open', 'validating', 'blocked')
  AND team_billing_period.finalized_at IS NULL
RETURNING team_id, period_start, period_end, status, blocked_reason, blocked_at, approved_by, approved_at, exported_at, finalized_at, created_at, updated_at, gross_charges_usd, credits_applied_usd, net_invoice_amount_usd
`

type BlockTeamBillingPeriodParams struct {
	BlockedReason *string   `json:"blocked_reason"`
	TeamID        uuid.UUID `json:"team_id"`
	PeriodStart   time.Time `json:"period_start"`
	PeriodEnd     time.Time `json:"period_end"`
}

func (q *Queries) BlockTeamBillingPeriod(ctx context.Context, arg BlockTeamBillingPeriodParams) (TeamBillingPeriod, error) {
	row := q.db.QueryRow(ctx, blockTeamBillingPeriod,
		arg.BlockedReason,
		arg.TeamID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var i TeamBillingPeriod
	err := row.Scan(
		&i.TeamID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.BlockedReason,
		&i.BlockedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ExportedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GrossChargesUsd,
		&i.CreditsAppliedUsd,
		&i.NetInvoiceAmountUsd,
	)
	return i, err
}

const createBillingPeriodAnomaly = `-- name: CreateBillingPeriodAnomaly :one
INSERT INTO billing_period_anomaly (
    team_id, period_start, period_end, severity, kind, sandbox_id, details
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, team_id, period_start, period_end, severity, kind, sandbox_id, details, detected_at, resolved_at, resolved_by
`

type CreateBillingPeriodAnomalyParams struct {
	TeamID      uuid.UUID   `json:"team_id"`
	PeriodStart time.Time   `json:"period_start"`
	PeriodEnd   time.Time   `json:"period_end"`
	Severity    string      `json:"severity"`
	Kind        string      `json:"kind"`
	SandboxID   pgtype.UUID `json:"sandbox_id"`
	Details     []byte      `json:"details"`
}

func (q *Queries) CreateBillingPeriodAnomaly(ctx context.Context, arg CreateBillingPeriodAnomalyParams) (BillingPeriodAnomaly, error) {
	row := q.db.QueryRow(ctx, createBillingPeriodAnomaly,
		arg.TeamID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Severity,
		arg.Kind,
		arg.SandboxID,
		arg.Details,
	)
	var i BillingPeriodAnomaly
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Severity,
		&i.Kind,
		&i.SandboxID,
		&i.Details,
		&i.DetectedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const getActiveTeamBillingPeriod = `-- name: GetActiveTeamBillingPeriod :one
SELECT team_id, period_start, period_end, status, blocked_reason, blocked_at, approved_by, approved_at, exported_at, finalized_at, created_at, updated_at, gross_charges_usd, credits_applied_usd, net_invoice_amount_usd
FROM team_billing_period
WHERE team_id = $1
  AND finalized_at IS NULL
ORDER BY period_start DESC
LIMIT 1
`

func (q *Queries) GetActiveTeamBillingPeriod(ctx context.Context, teamID uuid.UUID) (TeamBillingPeriod, error) {
	row := q.db.QueryRow(ctx, getActiveTeamBillingPeriod, teamID)
	var i TeamBillingPeriod
	err := row.Scan(
		&i.TeamID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.BlockedReason,
		&i.BlockedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ExportedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GrossChargesUsd,
		&i.CreditsAppliedUsd,
		&i.NetInvoiceAmountUsd,
	)
	return i, err
}

const getTeamActivePricingPlan = `-- name: GetTeamActivePricingPlan :one
SELECT COALESCE((
    SELECT tpp.plan_key
    FROM team_pricing_plan tpp
    JOIN pricing_plan p ON p.key = tpp.plan_key
    WHERE tpp.team_id = $1
      AND p.active
      AND tpp.effective_from <= now()
      AND (tpp.effective_to IS NULL OR tpp.effective_to > now())
    ORDER BY tpp.effective_from DESC
    LIMIT 1
), 'payg')::text AS plan_key
`

func (q *Queries) GetTeamActivePricingPlan(ctx context.Context, teamID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTeamActivePricingPlan, teamID)
	var plan_key string
	err := row.Scan(&plan_key)
	return plan_key, err
}

const getTeamBillingUsage = `-- name: GetTeamBillingUsage :one
WITH compute AS (
    SELECT
        COALESCE(SUM(
            EXTRACT(EPOCH FROM (
                LEAST(COALESCE(i.ended_at, now()), $3)
                - GREATEST(i.started_at, $2)
            )) * i.vcpu_count
        ), 0)::numeric AS vcpu_seconds,
        COALESCE(SUM(
            EXTRACT(EPOCH FROM (
                LEAST(COALESCE(i.ended_at, now()), $3)
                - GREATEST(i.started_at, $2)
            )) * i.memory_mib
        ), 0)::numeric AS memory_mib_seconds
    FROM sandbox_compute_billing_interval i
    WHERE i.team_id = $1
      AND $2 < LEAST(now(), $3)
      AND i.started_at < LEAST(now(), $3)
      AND COALESCE(i.ended_at, LEAST(now(), $3)) > $2
),
storage AS (
    SELECT COALESCE(SUM(
        EXTRACT(EPOCH FROM (
            LEAST(COALESCE(i.ended_at, now()), $3)
            - GREATEST(i.started_at, $2)
        )) * i.disk_mib
    ), 0)::numeric AS storage_mib_seconds
    FROM sandbox_storage_interval i
    WHERE i.team_id = $1
      AND $2 < LEAST(now(), $3)
      AND i.started_at < LEAST(now(), $3)
      AND COALESCE(i.ended_at, LEAST(now(), $3)) > $2
)
SELECT
    $1::uuid AS team_id,
    $2::timestamptz AS period_start,
    $3::timestamptz AS period_end,
    compute.vcpu_seconds,
    (compute.memory_mib_seconds / 1024.0)::numeric AS memory_gib_seconds,
    (storage.storage_mib_seconds / 1024.0)::numeric AS storage_gib_seconds
FROM compute, storage
`

type GetTeamBillingUsageParams struct {
	TeamID      uuid.UUID `json:"team_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type GetTeamBillingUsageRow struct {
	TeamID            uuid.UUID      `json:"team_id"`
	PeriodStart       time.Time      `json:"period_start"`
	PeriodEnd         time.Time      `json:"period_end"`
	VcpuSeconds       pgtype.Numeric `json:"vcpu_seconds"`
	MemoryGibSeconds  pgtype.Numeric `json:"memory_gib_seconds"`
	StorageGibSeconds pgtype.Numeric `json:"storage_gib_seconds"`
}

// Allocated usage for one team clipped to [period_start, period_end).
func (q *Queries) GetTeamBillingUsage(ctx context.Context, arg GetTeamBillingUsageParams) (GetTeamBillingUsageRow, error) {
	row := q.db.QueryRow(ctx, getTeamBillingUsage, arg.TeamID, arg.PeriodStart, arg.PeriodEnd)
	var i GetTeamBillingUsageRow
	err := row.Scan(
		&i.TeamID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.VcpuSeconds,
		&i.MemoryGibSeconds,
		&i.StorageGibSeconds,
	)
	return i, err
}

const getTeamCreditBalance = `-- name: GetTeamCreditBalance :one
SELECT COALESCE(SUM(remaining_usd), 0)::numeric AS balance_usd
FROM team_credit_grant
WHERE team_id = $1
  AND remaining_usd > 0
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetTeamCreditBalance(ctx context.Context, teamID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTeamCreditBalance, teamID)
	var balance_usd pgtype.Numeric
	err := row.Scan(&balance_usd)
	return balance_usd, err
}

const grantTeamCredit = `-- name: GrantTeamCredit :one
INSERT INTO team_credit_grant (
    team_id, amount_usd, remaining_usd, reason, expires_at, created_by
)
VALUES (
    $1,
    $2,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, team_id, amount_usd, remaining_usd, currency, reason, expires_at, created_by, created_at, updated_at
`

type GrantTeamCreditParams struct {
	TeamID    uuid.UUID          `json:"team_id"`
	AmountUsd pgtype.Numeric     `json:"amount_usd"`
	Reason    *string            `json:"reason"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
}

func (q *Queries) GrantTeamCredit(ctx context.Context, arg GrantTeamCreditParams) (TeamCreditGrant, error) {
	row := q.db.QueryRow(ctx, grantTeamCredit,
		arg.TeamID,
		arg.AmountUsd,
		arg.Reason,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i TeamCreditGrant
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AmountUsd,
		&i.RemainingUsd,
		&i.Currency,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isFeatureEnabledForTeam = `-- name: IsFeatureEnabledForTeam :one
SELECT feature_enabled($1, $2)::boolean AS enabled
`

type IsFeatureEnabledForTeamParams struct {
	Key    string      `json:"key"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) IsFeatureEnabledForTeam(ctx context.Context, arg IsFeatureEnabledForTeamParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFeatureEnabledForTeam, arg.Key, arg.TeamID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const listActivePricingRates = `-- name: ListActivePricingRates :many
WITH ranked_rates AS (
    SELECT
        r.plan_key,
        p.name AS plan_name,
        p.currency,
        r.resource,
        r.unit,
        r.price_usd,
        r.effective_from,
        row_number() OVER (
            PARTITION BY r.resource, r.unit
            ORDER BY r.effective_from DESC, r.created_at DESC, r.id DESC
        ) AS rate_rank
    FROM pricing_rate r
    JOIN pricing_plan p ON p.key = r.plan_key
    WHERE r.plan_key = $1
      AND p.active
      AND r.effective_from <= now()
      AND (r.effective_to IS NULL OR r.effective_to > now())
)
SELECT
    plan_key,
    plan_name,
    currency,
    resource,
    unit,
    price_usd,
    effective_from
FROM ranked_rates
WHERE rate_rank = 1
ORDER BY resource, unit
`

type ListActivePricingRatesRow struct {
	PlanKey       string         `json:"plan_key"`
	PlanName      string         `json:"plan_name"`
	Currency      string         `json:"currency"`
	Resource      string         `json:"resource"`
	Unit          string         `json:"unit"`
	PriceUsd      pgtype.Numeric `json:"price_usd"`
	EffectiveFrom time.Time      `json:"effective_from"`
}

func (q *Queries) ListActivePricingRates(ctx context.Context, planKey string) ([]ListActivePricingRatesRow, error) {
	rows, err := q.db.Query(ctx, listActivePricingRates, planKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePricingRatesRow{}
	for rows.Next() {
		var i ListActivePricingRatesRow
		if err := rows.Scan(
			&i.PlanKey,
			&i.PlanName,
			&i.Currency,
			&i.Resource,
			&i.Unit,
			&i.PriceUsd,
			&i.EffectiveFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePricingRatesForTeam = `-- name: ListActivePricingRatesForTeam :many
WITH selected_plan AS (
    SELECT COALESCE((
        SELECT tpp.plan_key
        FROM team_pricing_plan tpp
        JOIN pricing_plan p ON p.key = tpp.plan_key
        WHERE tpp.team_id = $1
          AND p.active
          AND tpp.effective_from <= $2::timestamptz
          AND (tpp.effective_to IS NULL OR tpp.effective_to > $2::timestamptz)
        ORDER BY tpp.effective_from DESC
        LIMIT 1
    ), 'payg')::text AS plan_key
),
ranked_rates AS (
    SELECT
        r.plan_key,
        p.name AS plan_name,
        p.currency,
        r.resource,
        r.unit,
        r.price_usd,
        r.effective_from,
        row_number() OVER (
            PARTITION BY r.resource, r.unit
            ORDER BY r.effective_from DESC, r.created_at DESC, r.id DESC
        ) AS rate_rank
    FROM selected_plan sp
    JOIN pricing_rate r ON r.plan_key = sp.plan_key
    JOIN pricing_plan p ON p.key = r.plan_key
    WHERE p.active
      AND r.effective_from <= $2::timestamptz
      AND (r.effective_to IS NULL OR r.effective_to > $2::timestamptz)
)
SELECT
    plan_key,
    plan_name,
    currency,
    resource,
    unit,
    price_usd,
    effective_from
FROM ranked_rates
WHERE rate_rank = 1
ORDER BY resource, unit
`

type ListActivePricingRatesForTeamParams struct {
	TeamID      uuid.UUID `json:"team_id"`
	EffectiveAt time.Time `json:"effective_at"`
}

type ListActivePricingRatesForTeamRow struct {
	PlanKey       string         `json:"plan_key"`
	PlanName      string         `json:"plan_name"`
	Currency      string         `json:"currency"`
	Resource      string         `json:"resource"`
	Unit          string         `json:"unit"`
	PriceUsd      pgtype.Numeric `json:"price_usd"`
	EffectiveFrom time.Time      `json:"effective_from"`
}

func (q *Queries) ListActivePricingRatesForTeam(ctx context.Context, arg ListActivePricingRatesForTeamParams) ([]ListActivePricingRatesForTeamRow, error) {
	rows, err := q.db.Query(ctx, listActivePricingRatesForTeam, arg.TeamID, arg.EffectiveAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePricingRatesForTeamRow{}
	for rows.Next() {
		var i ListActivePricingRatesForTeamRow
		if err := rows.Scan(
			&i.PlanKey,
			&i.PlanName,
			&i.Currency,
			&i.Resource,
			&i.Unit,
			&i.PriceUsd,
			&i.EffectiveFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportedTeamBillingPeriods = `-- name: ListExportedTeamBillingPeriods :many
WITH ranked AS (
    SELECT
        team_billing_period.team_id, team_billing_period.period_start, team_billing_period.period_end, team_billing_period.status, team_billing_period.blocked_reason, team_billing_period.blocked_at, team_billing_period.approved_by, team_billing_period.approved_at, team_billing_period.exported_at, team_billing_period.finalized_at, team_billing_period.created_at, team_billing_period.updated_at, team_billing_period.gross_charges_usd, team_billing_period.credits_applied_usd, team_billing_period.net_invoice_amount_usd,
        ROW_NUMBER() OVER (
            PARTITION BY team_id
            ORDER BY period_end ASC, period_start ASC
        ) AS team_rank
    FROM team_billing_period
    WHERE finalized_at IS NULL
)
SELECT team_id, period_start, period_end, status, blocked_reason, blocked_at, approved_by, approved_at, exported_at, finalized_at, created_at, updated_at, gross_charges_usd, credits_applied_usd, net_invoice_amount_usd, team_rank
FROM ranked
WHERE team_rank = 1
  AND status = 'exported'
ORDER BY period_end ASC, period_start ASC, team_id ASC
LIMIT $1
`

type ListExportedTeamBillingPeriodsRow struct {
	TeamID              uuid.UUID          `json:"team_id"`
	PeriodStart         time.Time          `json:"period_start"`
	PeriodEnd           time.Time          `json:"period_end"`
	Status              string             `json:"status"`
	BlockedReason       *string            `json:"blocked_reason"`
	BlockedAt           pgtype.Timestamptz `json:"blocked_at"`
	ApprovedBy          pgtype.UUID        `json:"approved_by"`
	ApprovedAt          pgtype.Timestamptz `json:"approved_at"`
	ExportedAt          pgtype.Timestamptz `json:"exported_at"`
	FinalizedAt         pgtype.Timestamptz `json:"finalized_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	GrossChargesUsd     pgtype.Numeric     `json:"gross_charges_usd"`
	CreditsAppliedUsd   pgtype.Numeric     `json:"credits_applied_usd"`
	NetInvoiceAmountUsd pgtype.Numeric     `json:"net_invoice_amount_usd"`
	TeamRank            int64              `json:"team_rank"`
}

func (q *Queries) ListExportedTeamBillingPeriods(ctx context.Context, batchSize int32) ([]ListExportedTeamBillingPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listExportedTeamBillingPeriods, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExportedTeamBillingPeriodsRow{}
	for rows.Next() {
		var i ListExportedTeamBillingPeriodsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.BlockedReason,
			&i.BlockedAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ExportedAt,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GrossChargesUsd,
			&i.CreditsAppliedUsd,
			&i.NetInvoiceAmountUsd,
			&i.TeamRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingRatesForPlanAt = `-- name: ListPricingRatesForPlanAt :many
WITH ranked_rates AS (
    SELECT
        r.plan_key,
        p.name AS plan_name,
        p.currency,
        r.resource,
        r.unit,
        r.price_usd,
        r.effective_from,
        row_number() OVER (
            PARTITION BY r.resource, r.unit
            ORDER BY r.effective_from DESC, r.created_at DESC, r.id DESC
        ) AS rate_rank
    FROM pricing_rate r
    JOIN pricing_plan p ON p.key = r.plan_key
    WHERE r.plan_key = $1
      AND r.effective_from <= $2::timestamptz
      AND (r.effective_to IS NULL OR r.effective_to > $2::timestamptz)
)
SELECT
    plan_key,
    plan_name,
    currency,
    resource,
    unit,
    price_usd,
    effective_from
FROM ranked_rates
WHERE rate_rank = 1
ORDER BY resource, unit
`

type ListPricingRatesForPlanAtParams struct {
	PlanKey     string    `json:"plan_key"`
	EffectiveAt time.Time `json:"effective_at"`
}

type ListPricingRatesForPlanAtRow struct {
	PlanKey       string         `json:"plan_key"`
	PlanName      string         `json:"plan_name"`
	Currency      string         `json:"currency"`
	Resource      string         `json:"resource"`
	Unit          string         `json:"unit"`
	PriceUsd      pgtype.Numeric `json:"price_usd"`
	EffectiveFrom time.Time      `json:"effective_from"`
}

func (q *Queries) ListPricingRatesForPlanAt(ctx context.Context, arg ListPricingRatesForPlanAtParams) ([]ListPricingRatesForPlanAtRow, error) {
	rows, err := q.db.Query(ctx, listPricingRatesForPlanAt, arg.PlanKey, arg.EffectiveAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPricingRatesForPlanAtRow{}
	for rows.Next() {
		var i ListPricingRatesForPlanAtRow
		if err := rows.Scan(
			&i.PlanKey,
			&i.PlanName,
			&i.Currency,
			&i.Resource,
			&i.Unit,
			&i.PriceUsd,
			&i.EffectiveFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamBillingUsageHourly = `-- name: ListTeamBillingUsageHourly :many
SELECT team_id, hour_start, hour_end, vcpu_seconds, memory_mib_seconds, storage_mib_seconds, updated_at
FROM team_billing_usage_hourly
WHERE team_id = $1
  AND feature_enabled('tenant_usage_dashboard', team_id)
  AND hour_start >= $2
  AND hour_start < $3
ORDER BY hour_start ASC
`

type ListTeamBillingUsageHourlyParams struct {
	TeamID      uuid.UUID `json:"team_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

func (q *Queries) ListTeamBillingUsageHourly(ctx context.Context, arg ListTeamBillingUsageHourlyParams) ([]TeamBillingUsageHourly, error) {
	rows, err := q.db.Query(ctx, listTeamBillingUsageHourly, arg.TeamID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamBillingUsageHourly{}
	for rows.Next() {
		var i TeamBillingUsageHourly
		if err := rows.Scan(
			&i.TeamID,
			&i.HourStart,
			&i.HourEnd,
			&i.VcpuSeconds,
			&i.MemoryMibSeconds,
			&i.StorageMibSeconds,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamCreditGrants = `-- name: ListTeamCreditGrants :many
SELECT id, team_id, amount_usd, remaining_usd, currency, reason, expires_at, created_by, created_at, updated_at
FROM team_credit_grant
WHERE team_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTeamCreditGrants(ctx context.Context, teamID uuid.UUID) ([]TeamCreditGrant, error) {
	rows, err := q.db.Query(ctx, listTeamCreditGrants, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamCreditGrant{}
	for rows.Next() {
		var i TeamCreditGrant
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.AmountUsd,
			&i.RemainingUsd,
			&i.Currency,
			&i.Reason,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedBillingPeriodAnomalies = `-- name: ListUnresolvedBillingPeriodAnomalies :many
SELECT id, team_id, period_start, period_end, severity, kind, sandbox_id, details, detected_at, resolved_at, resolved_by
FROM billing_period_anomaly
WHERE team_id = $1
  AND period_start = $2
  AND period_end = $3
  AND resolved_at IS NULL
ORDER BY
  CASE severity
    WHEN 'critical' THEN 0
    WHEN 'error' THEN 1
    ELSE 2
  END,
  detected_at ASC
`

type ListUnresolvedBillingPeriodAnomaliesParams struct {
	TeamID      uuid.UUID `json:"team_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

func (q *Queries) ListUnresolvedBillingPeriodAnomalies(ctx context.Context, arg ListUnresolvedBillingPeriodAnomaliesParams) ([]BillingPeriodAnomaly, error) {
	rows, err := q.db.Query(ctx, listUnresolvedBillingPeriodAnomalies, arg.TeamID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingPeriodAnomaly{}
	for rows.Next() {
		var i BillingPeriodAnomaly
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Severity,
			&i.Kind,
			&i.SandboxID,
			&i.Details,
			&i.DetectedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTeamBillingPeriodExported = `-- name: MarkTeamBillingPeriodExported :one
WITH exported_period AS (
    UPDATE team_billing_period
    SET status = 'exported',
        exported_at = now(),
        updated_at = now()
    WHERE team_billing_period.team_id = $1
      AND team_billing_period.period_start = $2
      AND team_billing_period.period_end = $3
      AND team_billing_period.status = 'approved'
      AND team_billing_period.finalized_at IS NULL
      AND EXISTS (
          SELECT 1
          FROM team_billing_usage u
          WHERE u.team_id = team_billing_period.team_id
            AND u.period_start = team_billing_period.period_start
            AND u.period_end = team_billing_period.period_end
            AND u.exported_at IS NULL
            AND u.finalized_at IS NULL
      )
      AND feature_enabled('billing_export_enabled', team_billing_period.team_id)
    RETURNING team_id, period_start, period_end, status, blocked_reason, blocked_at, approved_by, approved_at, exported_at, finalized_at, created_at, updated_at, gross_charges_usd, credits_applied_usd, net_invoice_amount_usd
),
exported_usage AS (
    UPDATE team_billing_usage u
    SET exported_at = exported_period.exported_at,
        updated_at = now()
    FROM exported_period
    WHERE u.team_id = exported_period.team_id
      AND u.period_start = exported_period.period_start
      AND u.period_end = exported_period.period_end
      AND u.exported_at IS NULL
      AND u.finalized_at IS NULL
    RETURNING u.team_id
)
SELECT team_id, period_start, period_end, status, blocked_reason, blocked_at, approved_by, approved_at, exported_at, finalized_at, created_at, updated_at, gross_charges_usd, credits_applied_usd, net_invoice_amount_usd
FROM exported_period
`

type MarkTeamBillingPeriodExportedParams struct {
	TeamID      uuid.UUID `json:"team_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type MarkTeamBillingPeriodExportedRow struct {
	TeamID              uuid.UUID          `json:"team_id"`
	PeriodStart         time.Time          `json:"period_start"`
	PeriodEnd           time.Time          `json:"period_end"`
	Status              string             `json:"status"`
	BlockedReason       *string            `json:"blocked_reason"`
	BlockedAt           pgtype.Timestamptz `json:"blocked_at"`
	ApprovedBy          pgtype.UUID        `json:"approved_by"`
	ApprovedAt          pgtype.Timestamptz `json:"approved_at"`
	ExportedAt          pgtype.Timestamptz `json:"exported_at"`
	FinalizedAt         pgtype.Timestamptz `json:"finalized_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	GrossChargesUsd     pgtype.Numeric     `json:"gross_charges_usd"`
	CreditsAppliedUsd   pgtype.Numeric     `json:"credits_applied_usd"`
	NetInvoiceAmountUsd pgtype.Numeric     `json:"net_invoice_amount_usd"`
}

func (q *Queries) MarkTeamBillingPeriodExported(ctx context.Context, arg MarkTeamBillingPeriodExportedParams) (MarkTeamBillingPeriodExportedRow, error) {
	row := q.db.QueryRow(ctx, markTeamBillingPeriodExported, arg.TeamID, arg.PeriodStart, arg.PeriodEnd)
	var i MarkTeamBillingPeriodExportedRow
	err := row.Scan(
		&i.TeamID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.BlockedReason,
		&i.BlockedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ExportedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GrossChargesUsd,
		&i.CreditsAppliedUsd,
		&i.NetInvoiceAmountUsd,
	)
	return i, err
}

const recordTeamCreditLedgerEntry = `-- name: RecordTeamCreditLedgerEntry :one
INSERT INTO team_credit_ledger (
    team_id,
    grant_id,
    billing_period_start,
    billing_period_end,
    amount_usd,
    reason,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, team_id, grant_id, billing_period_start, billing_period_end, amount_usd, reason, created_by, created_at
`

type RecordTeamCreditLedgerEntryParams struct {
	TeamID             uuid.UUID          `json:"team_id"`
	GrantID            pgtype.UUID        `json:"grant_id"`
	BillingPeriodStart pgtype.Timestamptz `json:"billing_period_start"`
	BillingPeriodEnd   pgtype.Timestamptz `json:"billing_period_end"`
	AmountUsd          pgtype.Numeric     `json:"amount_usd"`
	Reason             string             `json:"reason"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
}

func (q *Queries) RecordTeamCreditLedgerEntry(ctx context.Context, arg RecordTeamCreditLedgerEntryParams) (TeamCreditLedger, error) {
	row := q.db.QueryRow(ctx, recordTeamCreditLedgerEntry,
		arg.TeamID,
		arg.GrantID,
		arg.BillingPeriodStart,
		arg.BillingPeriodEnd,
		arg.AmountUsd,
		arg.Reason,
		arg.CreatedBy,
	)
	var i TeamCreditLedger
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.GrantID,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.AmountUsd,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const resolveBillingPeriodAnomaly = `-- name: ResolveBillingPeriodAnomaly :one
UPDATE billing_period_anomaly
SET resolved_at = now(),
    resolved_by = $1
WHERE billing_period_anomaly.id = $2
  AND billing_period_anomaly.resolved_at IS NULL
RETURNING id, team_id, period_start, period_end, severity, kind, sandbox_id, details, detected_at, resolved_at, resolved_by
`

type ResolveBillingPeriodAnomalyParams struct {
	ResolvedBy pgtype.UUID `json:"resolved_by"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) ResolveBillingPeriodAnomaly(ctx context.Context, arg ResolveBillingPeriodAnomalyParams) (BillingPeriodAnomaly, error) {
	row := q.db.QueryRow(ctx, resolveBillingPeriodAnomaly, arg.ResolvedBy, arg.ID)
	var i BillingPeriodAnomaly
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Severity,
		&i.Kind,
		&i.SandboxID,
		&i.Details,
		&i.DetectedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const setFeatureFlag = `-- name: SetFeatureFlag :one
INSERT INTO feature_flag (key, enabled, description)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET enabled = EXCLUDED.enabled,
    description = COALESCE(EXCLUDED.description, feature_flag.description),
    updated_at = now()
RETURNING key, enabled, description, created_at, updated_at
`

type SetFeatureFlagParams struct {
	Key         string  `json:"key"`
	Enabled     bool    `json:"enabled"`
	Description *string `json:"description"`
}

func (q *Queries) SetFeatureFlag(ctx context.Context, arg SetFeatureFlagParams) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, setFeatureFlag, arg.Key, arg.Enabled, arg.Description)
	var i FeatureFlag
	err := row.Scan(
		&i.Key,
		&i.Enabled,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTeamFeatureFlag = `-- name: SetTeamFeatureFlag :one
INSERT INTO team_feature_flag (team_id, key, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (team_id, key) DO UPDATE
SET enabled = EXCLUDED.enabled,
    updated_at = now()
RETURNING team_id, key, enabled, created_at, updated_at
`

type SetTeamFeatureFlagParams struct {
	TeamID  uuid.UUID `json:"team_id"`
	Key     string    `json:"key"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) SetTeamFeatureFlag(ctx context.Context, arg SetTeamFeatureFlagParams) (TeamFeatureFlag, error) {
	row := q.db.QueryRow(ctx, setTeamFeatureFlag, arg.TeamID, arg.Key, arg.Enabled)
	var i TeamFeatureFlag
	err := row.Scan(
		&i.TeamID,
		&i.Key,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTeamBillingPeriod = `-- name: UpsertTeamBillingPeriod :one
INSERT INTO team_billing_period (team_id, period_start, period_end, status)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (team_id, period_start, period_end) DO UPDATE
SET status = CASE
        WHEN team_billing_period.status IN ('blocked', 'approved', 'exported')
            THEN team_billing_period.status
        ELSE EXCLUDED.status
    END,
    updated_at = now()
WHERE team_billing_period.finalized_at IS NULL
RETURNING team_id, period_start, period_end, status, blocked_reason, blocked_at, approved_by, approved_at, exported_at, finalized_at, created_at, updated_at, gross_charges_usd, credits_applied_usd, net_invoice_amount_usd
`

type UpsertTeamBillingPeriodParams struct {
	TeamID      uuid.UUID `json:"team_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
	Status      string    `json:"status"`
}

func (q *Queries) UpsertTeamBillingPeriod(ctx context.Context, arg UpsertTeamBillingPeriodParams) (TeamBillingPeriod, error) {
	row := q.db.QueryRow(ctx, upsertTeamBillingPeriod,
		arg.TeamID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Status,
	)
	var i TeamBillingPeriod
	err := row.Scan(
		&i.TeamID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.BlockedReason,
		&i.BlockedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ExportedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GrossChargesUsd,
		&i.CreditsAppliedUsd,
		&i.NetInvoiceAmountUsd,
	)
	return i, err
}

const upsertTeamBillingUsage = `-- name: UpsertTeamBillingUsage :one
WITH compute AS (
    SELECT
        COALESCE(SUM(
            EXTRACT(EPOCH FROM (
                LEAST(COALESCE(i.ended_at, now()), $1)
                - GREATEST(i.started_at, $2)
            )) * i.vcpu_count
        ), 0)::numeric AS vcpu_seconds,
        COALESCE(SUM(
            EXTRACT(EPOCH FROM (
                LEAST(COALESCE(i.ended_at, now()), $1)
                - GREATEST(i.started_at, $2)
            )) * i.memory_mib
        ), 0)::numeric AS memory_mib_seconds
    FROM sandbox_compute_billing_interval i
    WHERE i.team_id = $3
      AND $2 < LEAST(now(), $1)
      AND i.started_at < LEAST(now(), $1)
      AND COALESCE(i.ended_at, LEAST(now(), $1)) > $2
),
storage AS (
    SELECT COALESCE(SUM(
        EXTRACT(EPOCH FROM (
            LEAST(COALESCE(i.ended_at, now()), $1)
            - GREATEST(i.started_at, $2)
        )) * i.disk_mib
    ), 0)::numeric AS storage_mib_seconds
    FROM sandbox_storage_interval i
    WHERE i.team_id = $3
      AND $2 < LEAST(now(), $1)
      AND i.started_at < LEAST(now(), $1)
      AND COALESCE(i.ended_at, LEAST(now(), $1)) > $2
),
usage AS (
    SELECT
        $3::uuid AS team_id,
        $2::timestamptz AS period_start,
        $1::timestamptz AS period_end,
        compute.vcpu_seconds,
        compute.memory_mib_seconds,
        storage.storage_mib_seconds
    FROM compute, storage
),
upserted AS (
    INSERT INTO team_billing_usage (
        team_id, period_start, period_end,
        vcpu_seconds, memory_mib_seconds, storage_mib_seconds
    )
    SELECT
        usage.team_id,
        usage.period_start,
        usage.period_end,
        usage.vcpu_seconds,
        usage.memory_mib_seconds,
        usage.storage_mib_seconds
    FROM usage
    WHERE NOT EXISTS (
        SELECT 1
        FROM team_billing_period p
        WHERE p.team_id = usage.team_id
          AND p.period_start = usage.period_start
          AND p.period_end = usage.period_end
          AND (
              p.status IN ('exported', 'finalized')
              OR p.exported_at IS NOT NULL
              OR p.finalized_at IS NOT NULL
          )
    )
    ON CONFLICT (team_id, period_start, period_end) DO UPDATE
    SET vcpu_seconds = EXCLUDED.vcpu_seconds,
        memory_mib_seconds = EXCLUDED.memory_mib_seconds,
        storage_mib_seconds = EXCLUDED.storage_mib_seconds,
        updated_at = now()
    WHERE team_billing_usage.finalized_at IS NULL
      AND team_billing_usage.exported_at IS NULL
    RETURNING
        team_id, period_start, period_end,
        vcpu_seconds, memory_mib_seconds, storage_mib_seconds,
        finalized_at, exported_at, updated_at
),
immutable_existing AS (
    SELECT
        existing.team_id,
        existing.period_start,
        existing.period_end,
        existing.vcpu_seconds,
        existing.memory_mib_seconds,
        existing.storage_mib_seconds,
        existing.finalized_at,
        existing.exported_at,
        existing.updated_at
    FROM team_billing_usage existing
    JOIN usage
      ON usage.team_id = existing.team_id
     AND usage.period_start = existing.period_start
     AND usage.period_end = existing.period_end
    WHERE NOT EXISTS (SELECT 1 FROM upserted)
      AND (
          existing.exported_at IS NOT NULL
          OR existing.finalized_at IS NOT NULL
      )
)
SELECT team_id, period_start, period_end, vcpu_seconds, memory_mib_seconds, storage_mib_seconds, finalized_at, exported_at, updated_at FROM upserted
UNION ALL
SELECT team_id, period_start, period_end, vcpu_seconds, memory_mib_seconds, storage_mib_seconds, finalized_at, exported_at, updated_at FROM immutable_existing
LIMIT 1
`

type UpsertTeamBillingUsageParams struct {
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	TeamID      uuid.UUID          `json:"team_id"`
}

type UpsertTeamBillingUsageRow struct {
	TeamID            uuid.UUID          `json:"team_id"`
	PeriodStart       time.Time          `json:"period_start"`
	PeriodEnd         time.Time          `json:"period_end"`
	VcpuSeconds       pgtype.Numeric     `json:"vcpu_seconds"`
	MemoryMibSeconds  pgtype.Numeric     `json:"memory_mib_seconds"`
	StorageMibSeconds pgtype.Numeric     `json:"storage_mib_seconds"`
	FinalizedAt       pgtype.Timestamptz `json:"finalized_at"`
	ExportedAt        pgtype.Timestamptz `json:"exported_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

// Recomputes a team's period rollup from raw intervals. Exported/finalized
// rows are immutable so a billing export cannot be silently rewritten.
func (q *Queries) UpsertTeamBillingUsage(ctx context.Context, arg UpsertTeamBillingUsageParams) (UpsertTeamBillingUsageRow, error) {
	row := q.db.QueryRow(ctx, upsertTeamBillingUsage, arg.PeriodEnd, arg.PeriodStart, arg.TeamID)
	var i UpsertTeamBillingUsageRow
	err := row.Scan(
		&i.TeamID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.VcpuSeconds,
		&i.MemoryMibSeconds,
		&i.StorageMibSeconds,
		&i.FinalizedAt,
		&i.ExportedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTeamBillingUsageHour = `-- name: UpsertTeamBillingUsageHour :one
WITH compute AS (
    SELECT
        COALESCE(SUM(
            EXTRACT(EPOCH FROM (
                LEAST(COALESCE(i.ended_at, billing_request_now()), $1)
                - GREATEST(i.started_at, $2)
            )) * i.vcpu_count
        ), 0)::numeric AS vcpu_seconds,
        COALESCE(SUM(
            EXTRACT(EPOCH FROM (
                LEAST(COALESCE(i.ended_at, billing_request_now()), $1)
                - GREATEST(i.started_at, $2)
            )) * i.memory_mib
        ), 0)::numeric AS memory_mib_seconds
    FROM sandbox_compute_billing_interval i
    WHERE i.team_id = $3
      AND i.started_at < $1
      AND $2 < LEAST(billing_request_now(), $1)
      AND COALESCE(i.ended_at, LEAST(billing_request_now(), $1)) > $2
),
storage AS (
    SELECT COALESCE(SUM(
        EXTRACT(EPOCH FROM (
            LEAST(COALESCE(i.ended_at, billing_request_now()), $1)
            - GREATEST(i.started_at, $2)
        )) * i.disk_mib
    ), 0)::numeric AS storage_mib_seconds
    FROM sandbox_storage_interval i
    WHERE i.team_id = $3
      AND i.started_at < $1
      AND $2 < LEAST(billing_request_now(), $1)
      AND COALESCE(i.ended_at, LEAST(billing_request_now(), $1)) > $2
),
usage AS (
    SELECT
        $3::uuid AS team_id,
        $2::timestamptz AS hour_start,
        $1::timestamptz AS hour_end,
        compute.vcpu_seconds,
        compute.memory_mib_seconds,
        storage.storage_mib_seconds
    FROM compute, storage
    WHERE feature_enabled('billing_hourly_rollups', $3::uuid)
)
INSERT INTO team_billing_usage_hourly (
    team_id, hour_start, hour_end,
    vcpu_seconds, memory_mib_seconds, storage_mib_seconds
)
SELECT
    usage.team_id,
    usage.hour_start,
    usage.hour_end,
    usage.vcpu_seconds,
    usage.memory_mib_seconds,
    usage.storage_mib_seconds
FROM usage
ON CONFLICT (team_id, hour_start) DO UPDATE
SET hour_end = EXCLUDED.hour_end,
    vcpu_seconds = EXCLUDED.vcpu_seconds,
    memory_mib_seconds = EXCLUDED.memory_mib_seconds,
    storage_mib_seconds = EXCLUDED.storage_mib_seconds,
    updated_at = now()
RETURNING team_id, hour_start, hour_end, vcpu_seconds, memory_mib_seconds, storage_mib_seconds, updated_at
`

type UpsertTeamBillingUsageHourParams struct {
	HourEnd   pgtype.Timestamptz `json:"hour_end"`
	HourStart pgtype.Timestamptz `json:"hour_start"`
	TeamID    uuid.UUID          `json:"team_id"`
}

func (q *Queries) UpsertTeamBillingUsageHour(ctx context.Context, arg UpsertTeamBillingUsageHourParams) (TeamBillingUsageHourly, error) {
	row := q.db.QueryRow(ctx, upsertTeamBillingUsageHour, arg.HourEnd, arg.HourStart, arg.TeamID)
	var i TeamBillingUsageHourly
	err := row.Scan(
		&i.TeamID,
		&i.HourStart,
		&i.HourEnd,
		&i.VcpuSeconds,
		&i.MemoryMibSeconds,
		&i.StorageMibSeconds,
		&i.UpdatedAt,
	)
	return i, err
}
