// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hosts.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindHostIdentity = `-- name: BindHostIdentity :exec
UPDATE host
SET identity_bound = true, updated_at = now()
WHERE id = $1
`

// Opt-in: an existing (legacy) row whose holder sent a complete
// self-description at its current address enters identity-bound mode.
func (q *Queries) BindHostIdentity(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bindHostIdentity, id)
	return err
}

const createHost = `-- name: CreateHost :one
INSERT INTO host (id, vmd_addr, proxy_addr, region, capacity_memory_mib, capacity_vcpus)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, identity_bound
`

type CreateHostParams struct {
	ID                string `json:"id"`
	VmdAddr           string `json:"vmd_addr"`
	ProxyAddr         string `json:"proxy_addr"`
	Region            string `json:"region"`
	CapacityMemoryMib int32  `json:"capacity_memory_mib"`
	CapacityVcpus     int32  `json:"capacity_vcpus"`
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, createHost,
		arg.ID,
		arg.VmdAddr,
		arg.ProxyAddr,
		arg.Region,
		arg.CapacityMemoryMib,
		arg.CapacityVcpus,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.VmdAddr,
		&i.ProxyAddr,
		&i.Region,
		&i.Status,
		&i.CapacityMemoryMib,
		&i.CapacityVcpus,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityBound,
	)
	return i, err
}

const getHost = `-- name: GetHost :one
SELECT id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, identity_bound FROM host WHERE id = $1
`

func (q *Queries) GetHost(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRow(ctx, getHost, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.VmdAddr,
		&i.ProxyAddr,
		&i.Region,
		&i.Status,
		&i.CapacityMemoryMib,
		&i.CapacityVcpus,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityBound,
	)
	return i, err
}

const getHostForUpdate = `-- name: GetHostForUpdate :one
SELECT id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, identity_bound FROM host WHERE id = $1 FOR UPDATE
`

// Row-locked read for the heartbeat's identity check, so the guard and the
// heartbeat update see the same row version inside one transaction.
func (q *Queries) GetHostForUpdate(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRow(ctx, getHostForUpdate, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.VmdAddr,
		&i.ProxyAddr,
		&i.Region,
		&i.Status,
		&i.CapacityMemoryMib,
		&i.CapacityVcpus,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityBound,
	)
	return i, err
}

const hostHasCapabilities = `-- name: HostHasCapabilities :one
WITH target_host AS MATERIALIZED (
  SELECT id, last_heartbeat_at
  FROM host
  WHERE id = $2
    AND status = 'active'
    AND last_heartbeat_at IS NOT NULL
  FOR SHARE
)
SELECT EXISTS (
  SELECT 1
  FROM target_host h
  WHERE NOT EXISTS (
    SELECT 1
    FROM unnest($1::text[]) AS required(capability)
    WHERE NOT EXISTS (
      SELECT 1
      FROM host_capability hc
      WHERE hc.host_id = h.id
        AND hc.capability = required.capability
        AND hc.heartbeat_at = h.last_heartbeat_at
    )
  )
)
`

type HostHasCapabilitiesParams struct {
	RequiredCapabilities []string `json:"required_capabilities"`
	HostID               string   `json:"host_id"`
}

// Lock the one active host row whose heartbeat anchors this capability set.
// Callers that run this in a mutation transaction keep the host stable until
// VMD delivery and commit, while the relational division below proves that
// every requested capability belongs to that exact heartbeat.
func (q *Queries) HostHasCapabilities(ctx context.Context, arg HostHasCapabilitiesParams) (bool, error) {
	row := q.db.QueryRow(ctx, hostHasCapabilities, arg.RequiredCapabilities, arg.HostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hostHasCapabilitiesUnlocked = `-- name: HostHasCapabilitiesUnlocked :one
WITH target_host AS MATERIALIZED (
  SELECT id, last_heartbeat_at
  FROM host
  WHERE id = $2
    AND status = 'active'
    AND last_heartbeat_at IS NOT NULL
)
SELECT EXISTS (
  SELECT 1
  FROM target_host h
  WHERE NOT EXISTS (
    SELECT 1
    FROM unnest($1::text[]) AS required(capability)
    WHERE NOT EXISTS (
      SELECT 1
      FROM host_capability hc
      WHERE hc.host_id = h.id
        AND hc.capability = required.capability
        AND hc.heartbeat_at = h.last_heartbeat_at
    )
  )
)
`

type HostHasCapabilitiesUnlockedParams struct {
	RequiredCapabilities []string `json:"required_capabilities"`
	HostID               string   `json:"host_id"`
}

// HostHasCapabilities without the row lock, for standalone pre-flight reads
// outside a mutation transaction: omitting the lock keeps concurrent checks
// from serializing behind the host's heartbeat writer. Transactional callers
// that must pin the host across a commit use HostHasCapabilities.
func (q *Queries) HostHasCapabilitiesUnlocked(ctx context.Context, arg HostHasCapabilitiesUnlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hostHasCapabilitiesUnlocked, arg.RequiredCapabilities, arg.HostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveHosts = `-- name: ListActiveHosts :many
SELECT id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, identity_bound FROM host
WHERE status = 'active'
ORDER BY created_at ASC
`

func (q *Queries) ListActiveHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.Query(ctx, listActiveHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.VmdAddr,
			&i.ProxyAddr,
			&i.Region,
			&i.Status,
			&i.CapacityMemoryMib,
			&i.CapacityVcpus,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdentityBound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveHostsByLoad = `-- name: ListActiveHostsByLoad :many
SELECT h.id, h.vmd_addr, h.proxy_addr, h.region, h.status,
       h.capacity_memory_mib, h.capacity_vcpus,
       h.last_heartbeat_at, h.created_at, h.updated_at,
       COALESCE(COUNT(s.id), 0)::int AS active_sandbox_count
FROM host h
LEFT JOIN sandbox s ON s.host_id = h.id
  AND s.status IN ('active', 'starting')
  AND s.destroyed_at IS NULL
WHERE h.status = 'active'
  AND NOT EXISTS (
    SELECT 1
    FROM unnest($1::text[]) AS required(capability)
    WHERE NOT EXISTS (
      SELECT 1 FROM host_capability hc
      WHERE hc.host_id = h.id
        AND hc.capability = required.capability
        AND hc.heartbeat_at = h.last_heartbeat_at
    )
  )
GROUP BY h.id
ORDER BY COUNT(s.id) ASC
`

type ListActiveHostsByLoadRow struct {
	ID                 string             `json:"id"`
	VmdAddr            string             `json:"vmd_addr"`
	ProxyAddr          string             `json:"proxy_addr"`
	Region             string             `json:"region"`
	Status             string             `json:"status"`
	CapacityMemoryMib  int32              `json:"capacity_memory_mib"`
	CapacityVcpus      int32              `json:"capacity_vcpus"`
	LastHeartbeatAt    pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	ActiveSandboxCount int32              `json:"active_sandbox_count"`
}

// Returns active hosts sorted by current sandbox count (ascending).
// The scheduler picks the first row (least loaded host). One query
// replaces N per-host lookups.
func (q *Queries) ListActiveHostsByLoad(ctx context.Context, requiredCapabilities []string) ([]ListActiveHostsByLoadRow, error) {
	rows, err := q.db.Query(ctx, listActiveHostsByLoad, requiredCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveHostsByLoadRow{}
	for rows.Next() {
		var i ListActiveHostsByLoadRow
		if err := rows.Scan(
			&i.ID,
			&i.VmdAddr,
			&i.ProxyAddr,
			&i.Region,
			&i.Status,
			&i.CapacityMemoryMib,
			&i.CapacityVcpus,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveSandboxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHosts = `-- name: ListHosts :many
SELECT id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, identity_bound FROM host
ORDER BY created_at ASC
`

func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.Query(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.VmdAddr,
			&i.ProxyAddr,
			&i.Region,
			&i.Status,
			&i.CapacityMemoryMib,
			&i.CapacityVcpus,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdentityBound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostsAdmin = `-- name: ListHostsAdmin :many
SELECT h.id, h.vmd_addr, h.proxy_addr, h.region, h.status,
       h.capacity_memory_mib, h.capacity_vcpus,
       h.last_heartbeat_at, h.created_at, h.updated_at,
       COALESCE(COUNT(s.id) FILTER (WHERE s.status IN ('active', 'starting')
                                      AND s.destroyed_at IS NULL), 0)::int AS running_count,
       COALESCE(COUNT(s.id) FILTER (WHERE s.status IN ('pausing', 'resuming')
                                      AND s.destroyed_at IS NULL), 0)::int AS transitional_count,
       COALESCE(COUNT(s.id) FILTER (WHERE s.status = 'paused'
                                      AND s.destroyed_at IS NULL), 0)::int AS paused_count,
       -- Scalar subquery, not a second LEFT JOIN: joining two child tables
       -- would cross-multiply the per-host rows and corrupt the counts.
       COALESCE((SELECT COUNT(*) FROM template_build tb
                 WHERE tb.vmd_host_id = h.id
                   AND tb.status IN ('building', 'snapshotting')), 0)::int AS building_count,
       -- Paused sandboxes whose CURRENT pause has no durable backup: the
       -- ones whose only up-to-date copy lives on this host's local disk.
       -- Retiring the machine destroys them outright; even
       -- paused-with-coverage stays pinned here until cross-host restore
       -- exists, but unbacked is the irrecoverable class an operator must
       -- never retire past.
       --
       -- "Current pause" means a generation completed at/after the head
       -- snapshot's created_at (which refreshes on every pause finalize) —
       -- a generation recorded for some EARLIER pause does not cover data
       -- written since. The comparison errs conservative: an upload that
       -- completed just before the finalize landed reads as unbacked until
       -- the next report, never the reverse. A paused sandbox with no
       -- snapshot row counts as unbacked for the same reason.
       COALESCE((SELECT COUNT(*) FROM sandbox s2
                 WHERE s2.host_id = h.id
                   AND s2.status = 'paused'
                   AND s2.destroyed_at IS NULL
                   AND NOT EXISTS (SELECT 1
                                   FROM snapshot snap
                                   JOIN backup_generation bg ON bg.sandbox_id = s2.id
                                   WHERE snap.id = s2.snapshot_id
                                     AND bg.completed_at >= snap.created_at)), 0)::int AS paused_unbacked_count
FROM host h
LEFT JOIN sandbox s ON s.host_id = h.id
WHERE $1::text IS NULL OR h.id = $1
GROUP BY h.id
ORDER BY h.created_at ASC
`

type ListHostsAdminRow struct {
	ID                  string             `json:"id"`
	VmdAddr             string             `json:"vmd_addr"`
	ProxyAddr           string             `json:"proxy_addr"`
	Region              string             `json:"region"`
	Status              string             `json:"status"`
	CapacityMemoryMib   int32              `json:"capacity_memory_mib"`
	CapacityVcpus       int32              `json:"capacity_vcpus"`
	LastHeartbeatAt     pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	RunningCount        int32              `json:"running_count"`
	TransitionalCount   int32              `json:"transitional_count"`
	PausedCount         int32              `json:"paused_count"`
	BuildingCount       int32              `json:"building_count"`
	PausedUnbackedCount int32              `json:"paused_unbacked_count"`
}

// Operator view (hostctl): every host regardless of status, with live
// sandbox counts for drain progress. transitional counts pausing/resuming
// sandboxes whose lifecycle RPC is still using the host — a host is not
// drained while any exist, even when running and paused both read zero.
// The optional id filter exists for drain polling: `hostctl drain --wait`
// re-reads one host every few seconds, and the per-host counts (the
// backup-coverage probe especially) must not be recomputed for the whole
// fleet on every poll.
func (q *Queries) ListHostsAdmin(ctx context.Context, id *string) ([]ListHostsAdminRow, error) {
	rows, err := q.db.Query(ctx, listHostsAdmin, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostsAdminRow{}
	for rows.Next() {
		var i ListHostsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.VmdAddr,
			&i.ProxyAddr,
			&i.Region,
			&i.Status,
			&i.CapacityMemoryMib,
			&i.CapacityVcpus,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunningCount,
			&i.TransitionalCount,
			&i.PausedCount,
			&i.BuildingCount,
			&i.PausedUnbackedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleHosts = `-- name: ListStaleHosts :many
SELECT id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, identity_bound FROM host
WHERE status = 'active'
  AND last_heartbeat_at IS NOT NULL
  AND last_heartbeat_at < $1
ORDER BY last_heartbeat_at ASC
`

// Returns active hosts whose last heartbeat is older than the given
// threshold. Used by the unhealthy-host detector.
func (q *Queries) ListStaleHosts(ctx context.Context, lastHeartbeatAt pgtype.Timestamptz) ([]Host, error) {
	rows, err := q.db.Query(ctx, listStaleHosts, lastHeartbeatAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.VmdAddr,
			&i.ProxyAddr,
			&i.Region,
			&i.Status,
			&i.CapacityMemoryMib,
			&i.CapacityVcpus,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdentityBound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHostUnhealthy = `-- name: MarkHostUnhealthy :exec
UPDATE host
SET status = 'unhealthy', updated_at = now()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) MarkHostUnhealthy(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markHostUnhealthy, id)
	return err
}

const registerHost = `-- name: RegisterHost :one
INSERT INTO host (id, vmd_addr, proxy_addr, region, status,
                  capacity_memory_mib, capacity_vcpus, last_heartbeat_at,
                  identity_bound)
VALUES ($1, $2, $3, $4, 'provisioning', $5, $6, now(), true)
RETURNING id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, identity_bound
`

type RegisterHostParams struct {
	ID                string `json:"id"`
	VmdAddr           string `json:"vmd_addr"`
	ProxyAddr         string `json:"proxy_addr"`
	Region            string `json:"region"`
	CapacityMemoryMib int32  `json:"capacity_memory_mib"`
	CapacityVcpus     int32  `json:"capacity_vcpus"`
}

// Self-registration from a first heartbeat. Starts in 'provisioning' so the
// scheduler never sees the host until an operator activates it. Stamps
// last_heartbeat_at because capability attestation keys on it: without a
// heartbeat time, InsertHostCapability is a silent no-op.
func (q *Queries) RegisterHost(ctx context.Context, arg RegisterHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, registerHost,
		arg.ID,
		arg.VmdAddr,
		arg.ProxyAddr,
		arg.Region,
		arg.CapacityMemoryMib,
		arg.CapacityVcpus,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.VmdAddr,
		&i.ProxyAddr,
		&i.Region,
		&i.Status,
		&i.CapacityMemoryMib,
		&i.CapacityVcpus,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityBound,
	)
	return i, err
}

const syncHostCapabilities = `-- name: SyncHostCapabilities :exec
WITH current_host AS (
    SELECT id, last_heartbeat_at
    FROM host
    WHERE id = $1 AND last_heartbeat_at IS NOT NULL
), advertised AS (
    SELECT DISTINCT unnest(COALESCE($2::text[], ARRAY[]::text[])) AS capability
), upserted AS (
    INSERT INTO host_capability (host_id, capability, heartbeat_at)
    SELECT h.id, a.capability, h.last_heartbeat_at
    FROM current_host h
    CROSS JOIN advertised a
    ON CONFLICT (host_id, capability)
    DO UPDATE SET heartbeat_at = EXCLUDED.heartbeat_at
    RETURNING capability
)
DELETE FROM host_capability hc
WHERE hc.host_id = $1
  AND NOT (hc.capability = ANY(COALESCE($2::text[], ARRAY[]::text[])))
`

type SyncHostCapabilitiesParams struct {
	HostID       string   `json:"host_id"`
	Capabilities []string `json:"capabilities"`
}

// Refresh the advertised set in place and prune only capabilities omitted by
// this heartbeat. Empty capabilities intentionally remove the entire set.
func (q *Queries) SyncHostCapabilities(ctx context.Context, arg SyncHostCapabilitiesParams) error {
	_, err := q.db.Exec(ctx, syncHostCapabilities, arg.HostID, arg.Capabilities)
	return err
}

const updateHostAddresses = `-- name: UpdateHostAddresses :exec
UPDATE host
SET vmd_addr = $2, proxy_addr = $3, region = $4,
    capacity_memory_mib = $5, capacity_vcpus = $6,
    status = 'provisioning', identity_bound = true, updated_at = now()
WHERE id = $1
`

type UpdateHostAddressesParams struct {
	ID                string `json:"id"`
	VmdAddr           string `json:"vmd_addr"`
	ProxyAddr         string `json:"proxy_addr"`
	Region            string `json:"region"`
	CapacityMemoryMib int32  `json:"capacity_memory_mib"`
	CapacityVcpus     int32  `json:"capacity_vcpus"`
}

// Re-provision path: the identity is reclaiming its row from a new address
// after the old holder went silent. Guarded by the handler's staleness check.
// The reclaim DEMOTES the row to provisioning in the same statement: an
// address change is a re-registration, and every holder of the vmd-internal
// token can trigger one after two minutes of silence — it must never leave
// (or make) a host schedulable without the operator credential re-approving.
func (q *Queries) UpdateHostAddresses(ctx context.Context, arg UpdateHostAddressesParams) error {
	_, err := q.db.Exec(ctx, updateHostAddresses,
		arg.ID,
		arg.VmdAddr,
		arg.ProxyAddr,
		arg.Region,
		arg.CapacityMemoryMib,
		arg.CapacityVcpus,
	)
	return err
}

const updateHostHeartbeat = `-- name: UpdateHostHeartbeat :one
WITH prev AS (
    SELECT h.id, h.status FROM host h WHERE h.id = $1 FOR UPDATE
)
UPDATE host
SET last_heartbeat_at = now(),
    status = CASE WHEN host.status = 'unhealthy' THEN 'active' ELSE host.status END,
    updated_at = now()
FROM prev
WHERE host.id = prev.id
RETURNING host.id, host.vmd_addr, host.proxy_addr, host.region, host.status, host.capacity_memory_mib, host.capacity_vcpus, host.last_heartbeat_at, host.created_at, host.updated_at, host.identity_bound, prev.status AS prev_status
`

type UpdateHostHeartbeatRow struct {
	ID                string             `json:"id"`
	VmdAddr           string             `json:"vmd_addr"`
	ProxyAddr         string             `json:"proxy_addr"`
	Region            string             `json:"region"`
	Status            string             `json:"status"`
	CapacityMemoryMib int32              `json:"capacity_memory_mib"`
	CapacityVcpus     int32              `json:"capacity_vcpus"`
	LastHeartbeatAt   pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	IdentityBound     bool               `json:"identity_bound"`
	PrevStatus        string             `json:"prev_status"`
}

// Returns the host row so the caller can verify the host exists. Also
// re-activates unhealthy hosts that resume heartbeating — this is the
// automatic recovery path after a transient network outage. prev_status lets
// the caller detect that transition and invalidate the scheduler's host cache
// so recovered capacity is usable immediately instead of after the cache TTL.
// The pre-image is read FOR UPDATE so it reflects the row version this
// statement actually modifies; a plain snapshot read racing a concurrent
// status write could report the transition as active→active and hide it.
func (q *Queries) UpdateHostHeartbeat(ctx context.Context, id string) (UpdateHostHeartbeatRow, error) {
	row := q.db.QueryRow(ctx, updateHostHeartbeat, id)
	var i UpdateHostHeartbeatRow
	err := row.Scan(
		&i.ID,
		&i.VmdAddr,
		&i.ProxyAddr,
		&i.Region,
		&i.Status,
		&i.CapacityMemoryMib,
		&i.CapacityVcpus,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityBound,
		&i.PrevStatus,
	)
	return i, err
}

const updateHostStatus = `-- name: UpdateHostStatus :one
UPDATE host
SET status = $2, updated_at = now()
WHERE id = $1
  AND ($2 <> 'active'
       OR (last_heartbeat_at IS NOT NULL
           AND last_heartbeat_at > $3))
RETURNING id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, identity_bound
`

type UpdateHostStatusParams struct {
	ID                   string             `json:"id"`
	Status               string             `json:"status"`
	ActiveHeartbeatAfter pgtype.Timestamptz `json:"active_heartbeat_after"`
}

// Activation requires a live heartbeat: a provisioning host that died
// before the operator activated it must not become schedulable — the
// unhealthy detector only watches active rows, so it would sit exposed to
// placement until the detector's next pass. Non-active targets carry no
// freshness requirement; draining a dead host is legitimate.
func (q *Queries) UpdateHostStatus(ctx context.Context, arg UpdateHostStatusParams) (Host, error) {
	row := q.db.QueryRow(ctx, updateHostStatus, arg.ID, arg.Status, arg.ActiveHeartbeatAfter)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.VmdAddr,
		&i.ProxyAddr,
		&i.Region,
		&i.Status,
		&i.CapacityMemoryMib,
		&i.CapacityVcpus,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityBound,
	)
	return i, err
}
