// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hosts.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHost = `-- name: CreateHost :one
INSERT INTO host (id, vmd_addr, proxy_addr, region, capacity_memory_mib, capacity_vcpus)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, maintenance_window_start
`

type CreateHostParams struct {
	ID                string `json:"id"`
	VmdAddr           string `json:"vmd_addr"`
	ProxyAddr         string `json:"proxy_addr"`
	Region            string `json:"region"`
	CapacityMemoryMib int32  `json:"capacity_memory_mib"`
	CapacityVcpus     int32  `json:"capacity_vcpus"`
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, createHost,
		arg.ID,
		arg.VmdAddr,
		arg.ProxyAddr,
		arg.Region,
		arg.CapacityMemoryMib,
		arg.CapacityVcpus,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.VmdAddr,
		&i.ProxyAddr,
		&i.Region,
		&i.Status,
		&i.CapacityMemoryMib,
		&i.CapacityVcpus,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaintenanceWindowStart,
	)
	return i, err
}

const deleteHostCapabilities = `-- name: DeleteHostCapabilities :exec
DELETE FROM host_capability WHERE host_id = $1
`

func (q *Queries) DeleteHostCapabilities(ctx context.Context, hostID string) error {
	_, err := q.db.Exec(ctx, deleteHostCapabilities, hostID)
	return err
}

const drainHost = `-- name: DrainHost :execrows
UPDATE host
SET status = 'draining', updated_at = now()
WHERE id = $1 AND status = 'active'
`

// Guarded transition active -> draining: an unhealthy host must not be
// "drained" into looking deliberately managed, and a double drain is a no-op.
func (q *Queries) DrainHost(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, drainHost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const drainHostsDueForMaintenance = `-- name: DrainHostsDueForMaintenance :many
UPDATE host
SET status = 'draining', updated_at = now()
WHERE status = 'active'
  AND maintenance_window_start IS NOT NULL
  AND maintenance_window_start <= now() + make_interval(secs => $1::int)
  AND maintenance_window_start >= now() - make_interval(secs => $1::int)
RETURNING id, maintenance_window_start
`

type DrainHostsDueForMaintenanceRow struct {
	ID                     string             `json:"id"`
	MaintenanceWindowStart pgtype.Timestamptz `json:"maintenance_window_start"`
}

// Flips active hosts whose RECORDED maintenance window has entered the lead
// period. This is the drain decision's single home: driving it from the
// persisted deadline (not from freshly reported values) means a window
// recorded hours ago still drains on time even if every later metadata
// probe fails. The lower bound keeps long-stale windows (metadata that
// never cleared after a completed restart) from re-draining an un-drained
// host.
func (q *Queries) DrainHostsDueForMaintenance(ctx context.Context, leadSeconds int32) ([]DrainHostsDueForMaintenanceRow, error) {
	rows, err := q.db.Query(ctx, drainHostsDueForMaintenance, leadSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DrainHostsDueForMaintenanceRow{}
	for rows.Next() {
		var i DrainHostsDueForMaintenanceRow
		if err := rows.Scan(&i.ID, &i.MaintenanceWindowStart); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHost = `-- name: GetHost :one
SELECT id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, maintenance_window_start FROM host WHERE id = $1
`

func (q *Queries) GetHost(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRow(ctx, getHost, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.VmdAddr,
		&i.ProxyAddr,
		&i.Region,
		&i.Status,
		&i.CapacityMemoryMib,
		&i.CapacityVcpus,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaintenanceWindowStart,
	)
	return i, err
}

const hostHasCapabilities = `-- name: HostHasCapabilities :one
WITH target_host AS MATERIALIZED (
  SELECT id, last_heartbeat_at
  FROM host
  WHERE id = $2
    -- 'draining' still qualifies: a drain (announced host maintenance) stops
    -- new placement, not service — resumes must keep working right up to the
    -- window, and the drain reaper re-pauses whatever they re-activate.
    AND status IN ('active', 'draining')
    AND last_heartbeat_at IS NOT NULL
  FOR SHARE
)
SELECT EXISTS (
  SELECT 1
  FROM target_host h
  WHERE NOT EXISTS (
    SELECT 1
    FROM unnest($1::text[]) AS required(capability)
    WHERE NOT EXISTS (
      SELECT 1
      FROM host_capability hc
      WHERE hc.host_id = h.id
        AND hc.capability = required.capability
        AND hc.heartbeat_at = h.last_heartbeat_at
    )
  )
)
`

type HostHasCapabilitiesParams struct {
	RequiredCapabilities []string `json:"required_capabilities"`
	HostID               string   `json:"host_id"`
}

// Lock the one active host row whose heartbeat anchors this capability set.
// Callers that run this in a mutation transaction keep the host stable until
// VMD delivery and commit, while the relational division below proves that
// every requested capability belongs to that exact heartbeat.
func (q *Queries) HostHasCapabilities(ctx context.Context, arg HostHasCapabilitiesParams) (bool, error) {
	row := q.db.QueryRow(ctx, hostHasCapabilities, arg.RequiredCapabilities, arg.HostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hostHasCapabilitiesUnlocked = `-- name: HostHasCapabilitiesUnlocked :one
WITH target_host AS MATERIALIZED (
  SELECT id, last_heartbeat_at
  FROM host
  WHERE id = $2
    AND status IN ('active', 'draining')  -- same rationale as HostHasCapabilities
    AND last_heartbeat_at IS NOT NULL
)
SELECT EXISTS (
  SELECT 1
  FROM target_host h
  WHERE NOT EXISTS (
    SELECT 1
    FROM unnest($1::text[]) AS required(capability)
    WHERE NOT EXISTS (
      SELECT 1
      FROM host_capability hc
      WHERE hc.host_id = h.id
        AND hc.capability = required.capability
        AND hc.heartbeat_at = h.last_heartbeat_at
    )
  )
)
`

type HostHasCapabilitiesUnlockedParams struct {
	RequiredCapabilities []string `json:"required_capabilities"`
	HostID               string   `json:"host_id"`
}

// HostHasCapabilities without the row lock, for standalone pre-flight reads
// outside a mutation transaction: omitting the lock keeps concurrent checks
// from serializing behind the host's heartbeat writer. Transactional callers
// that must pin the host across a commit use HostHasCapabilities.
func (q *Queries) HostHasCapabilitiesUnlocked(ctx context.Context, arg HostHasCapabilitiesUnlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hostHasCapabilitiesUnlocked, arg.RequiredCapabilities, arg.HostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertHostCapability = `-- name: InsertHostCapability :exec
INSERT INTO host_capability (host_id, capability, heartbeat_at)
SELECT id, $1, last_heartbeat_at
FROM host
WHERE id = $2 AND last_heartbeat_at IS NOT NULL
ON CONFLICT (host_id, capability)
DO UPDATE SET heartbeat_at = EXCLUDED.heartbeat_at
`

type InsertHostCapabilityParams struct {
	Capability string `json:"capability"`
	HostID     string `json:"host_id"`
}

func (q *Queries) InsertHostCapability(ctx context.Context, arg InsertHostCapabilityParams) error {
	_, err := q.db.Exec(ctx, insertHostCapability, arg.Capability, arg.HostID)
	return err
}

const listActiveHosts = `-- name: ListActiveHosts :many
SELECT id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, maintenance_window_start FROM host
WHERE status = 'active'
ORDER BY created_at ASC
`

func (q *Queries) ListActiveHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.Query(ctx, listActiveHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.VmdAddr,
			&i.ProxyAddr,
			&i.Region,
			&i.Status,
			&i.CapacityMemoryMib,
			&i.CapacityVcpus,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaintenanceWindowStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveHostsByLoad = `-- name: ListActiveHostsByLoad :many
SELECT h.id, h.vmd_addr, h.proxy_addr, h.region, h.status,
       h.capacity_memory_mib, h.capacity_vcpus,
       h.last_heartbeat_at, h.created_at, h.updated_at,
       COALESCE(COUNT(s.id), 0)::int AS active_sandbox_count
FROM host h
LEFT JOIN sandbox s ON s.host_id = h.id
  AND s.status IN ('active', 'starting')
  AND s.destroyed_at IS NULL
WHERE h.status = 'active'
  AND NOT EXISTS (
    SELECT 1
    FROM unnest($1::text[]) AS required(capability)
    WHERE NOT EXISTS (
      SELECT 1 FROM host_capability hc
      WHERE hc.host_id = h.id
        AND hc.capability = required.capability
        AND hc.heartbeat_at = h.last_heartbeat_at
    )
  )
GROUP BY h.id
ORDER BY COUNT(s.id) ASC
`

type ListActiveHostsByLoadRow struct {
	ID                 string             `json:"id"`
	VmdAddr            string             `json:"vmd_addr"`
	ProxyAddr          string             `json:"proxy_addr"`
	Region             string             `json:"region"`
	Status             string             `json:"status"`
	CapacityMemoryMib  int32              `json:"capacity_memory_mib"`
	CapacityVcpus      int32              `json:"capacity_vcpus"`
	LastHeartbeatAt    pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	ActiveSandboxCount int32              `json:"active_sandbox_count"`
}

// Returns active hosts sorted by current sandbox count (ascending).
// The scheduler picks the first row (least loaded host). One query
// replaces N per-host lookups.
func (q *Queries) ListActiveHostsByLoad(ctx context.Context, requiredCapabilities []string) ([]ListActiveHostsByLoadRow, error) {
	rows, err := q.db.Query(ctx, listActiveHostsByLoad, requiredCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveHostsByLoadRow{}
	for rows.Next() {
		var i ListActiveHostsByLoadRow
		if err := rows.Scan(
			&i.ID,
			&i.VmdAddr,
			&i.ProxyAddr,
			&i.Region,
			&i.Status,
			&i.CapacityMemoryMib,
			&i.CapacityVcpus,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveSandboxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrainingHosts = `-- name: ListDrainingHosts :many
SELECT id, maintenance_window_start
FROM host
WHERE status = 'draining'
ORDER BY maintenance_window_start ASC NULLS LAST, id
`

type ListDrainingHostsRow struct {
	ID                     string             `json:"id"`
	MaintenanceWindowStart pgtype.Timestamptz `json:"maintenance_window_start"`
}

// Hosts being drained ahead of an announced restart, most urgent first: the
// claim budget is spent in list order, so the nearest maintenance deadline
// must come first — a host restarting in minutes cannot sit behind manual
// drains (NULL window, no deadline pressure: deliberately last) or hosts
// with later windows. maintenance_window_start also drives the
// drain-incomplete alert.
func (q *Queries) ListDrainingHosts(ctx context.Context) ([]ListDrainingHostsRow, error) {
	rows, err := q.db.Query(ctx, listDrainingHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDrainingHostsRow{}
	for rows.Next() {
		var i ListDrainingHostsRow
		if err := rows.Scan(&i.ID, &i.MaintenanceWindowStart); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHosts = `-- name: ListHosts :many
SELECT id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, maintenance_window_start FROM host
ORDER BY created_at ASC
`

func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.Query(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.VmdAddr,
			&i.ProxyAddr,
			&i.Region,
			&i.Status,
			&i.CapacityMemoryMib,
			&i.CapacityVcpus,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaintenanceWindowStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleHosts = `-- name: ListStaleHosts :many
SELECT id, vmd_addr, proxy_addr, region, status, capacity_memory_mib, capacity_vcpus, last_heartbeat_at, created_at, updated_at, maintenance_window_start FROM host
WHERE status = 'active'
  AND last_heartbeat_at IS NOT NULL
  AND last_heartbeat_at < $1
ORDER BY last_heartbeat_at ASC
`

// Returns active hosts whose last heartbeat is older than the given
// threshold. Used by the unhealthy-host detector.
func (q *Queries) ListStaleHosts(ctx context.Context, lastHeartbeatAt pgtype.Timestamptz) ([]Host, error) {
	rows, err := q.db.Query(ctx, listStaleHosts, lastHeartbeatAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.VmdAddr,
			&i.ProxyAddr,
			&i.Region,
			&i.Status,
			&i.CapacityMemoryMib,
			&i.CapacityVcpus,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaintenanceWindowStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHostUnhealthy = `-- name: MarkHostUnhealthy :exec
UPDATE host
SET status = 'unhealthy', updated_at = now()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) MarkHostUnhealthy(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markHostUnhealthy, id)
	return err
}

const undrainHost = `-- name: UndrainHost :execrows
UPDATE host
SET status = 'active', updated_at = now()
WHERE id = $1 AND status = 'draining'
`

// Guarded transition draining -> active. Deliberately manual-only (operator
// endpoint): the mistake costs are asymmetric — staying drained too long
// costs placement capacity, while un-draining on a flaky signal puts fresh
// workloads on a machine about to restart. The heartbeat never un-drains.
func (q *Queries) UndrainHost(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, undrainHost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateHostHeartbeat = `-- name: UpdateHostHeartbeat :one
WITH prev AS (
    SELECT h.id, h.status FROM host h WHERE h.id = $1 FOR UPDATE
)
UPDATE host
SET last_heartbeat_at = now(),
    status = CASE WHEN host.status = 'unhealthy' THEN 'active' ELSE host.status END,
    updated_at = now()
FROM prev
WHERE host.id = prev.id
RETURNING host.id, host.vmd_addr, host.proxy_addr, host.region, host.status, host.capacity_memory_mib, host.capacity_vcpus, host.last_heartbeat_at, host.created_at, host.updated_at, host.maintenance_window_start, prev.status AS prev_status
`

type UpdateHostHeartbeatRow struct {
	ID                     string             `json:"id"`
	VmdAddr                string             `json:"vmd_addr"`
	ProxyAddr              string             `json:"proxy_addr"`
	Region                 string             `json:"region"`
	Status                 string             `json:"status"`
	CapacityMemoryMib      int32              `json:"capacity_memory_mib"`
	CapacityVcpus          int32              `json:"capacity_vcpus"`
	LastHeartbeatAt        pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	MaintenanceWindowStart pgtype.Timestamptz `json:"maintenance_window_start"`
	PrevStatus             string             `json:"prev_status"`
}

// Returns the host row so the caller can verify the host exists. Also
// re-activates unhealthy hosts that resume heartbeating — this is the
// automatic recovery path after a transient network outage. prev_status lets
// the caller detect that transition and invalidate the scheduler's host cache
// so recovered capacity is usable immediately instead of after the cache TTL.
// The pre-image is read FOR UPDATE so it reflects the row version this
// statement actually modifies; a plain snapshot read racing a concurrent
// status write could report the transition as active→active and hide it.
func (q *Queries) UpdateHostHeartbeat(ctx context.Context, id string) (UpdateHostHeartbeatRow, error) {
	row := q.db.QueryRow(ctx, updateHostHeartbeat, id)
	var i UpdateHostHeartbeatRow
	err := row.Scan(
		&i.ID,
		&i.VmdAddr,
		&i.ProxyAddr,
		&i.Region,
		&i.Status,
		&i.CapacityMemoryMib,
		&i.CapacityVcpus,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaintenanceWindowStart,
		&i.PrevStatus,
	)
	return i, err
}

const updateHostMaintenanceWindow = `-- name: UpdateHostMaintenanceWindow :exec
UPDATE host
SET maintenance_window_start = $2, updated_at = now()
WHERE id = $1
`

type UpdateHostMaintenanceWindowParams struct {
	ID                     string             `json:"id"`
	MaintenanceWindowStart pgtype.Timestamptz `json:"maintenance_window_start"`
}

// Records (or clears, with NULL) the machine's next announced maintenance
// window, as reported by the host's heartbeat.
func (q *Queries) UpdateHostMaintenanceWindow(ctx context.Context, arg UpdateHostMaintenanceWindowParams) error {
	_, err := q.db.Exec(ctx, updateHostMaintenanceWindow, arg.ID, arg.MaintenanceWindowStart)
	return err
}

const updateHostStatus = `-- name: UpdateHostStatus :exec
UPDATE host
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateHostStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateHostStatus(ctx context.Context, arg UpdateHostStatusParams) error {
	_, err := q.db.Exec(ctx, updateHostStatus, arg.ID, arg.Status)
	return err
}
