// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: qm_locks.sql

package db

import (
	"context"
)

const tryLockQMTenant = `-- name: TryLockQMTenant :one
SELECT pg_try_advisory_xact_lock(hashtext('qm-tenant:' || $1::text)::bigint)::boolean AS locked
`

// Non-blocking per-tenant lock held for a whole provisioner run; a second
// run for the same tenant sees false and exits instead of queueing.
func (q *Queries) TryLockQMTenant(ctx context.Context, tenantID string) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockQMTenant, tenantID)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}
