// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routing_hints.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSandboxWithPreviewPolicyForRouting = `-- name: GetSandboxWithPreviewPolicyForRouting :one
SELECT s.id, s.team_id, s.name, s.status, s.vcpu_count, s.memory_mib, s.host_id, s.ip_address, s.pid, s.snapshot_id, s.created_at, s.updated_at, s.destroyed_at, s.network_config, s.timeout_seconds, s.metadata, s.template_id, s.snapshot_path, s.mem_path, s.base_path, s.delta_path, s.disk_mib, s.auto_delete_seconds, s.auto_delete_at, s.failed_at, s.had_secret_bindings, s.secret_env_fingerprint, s.secret_env_ip, s.secret_env_injected_at, s.secret_env_expires_at, s.pause_op_id, s.pause_op_started_at, s.pause_op_lease_until, s.pause_op_lease_version, s.pause_op_attention_at, s.pause_op_trigger, s.pause_op_actor_id, s.routing_version, s.legacy_storage_refs, s.source_snapshot_id, statement_timestamp()::timestamptz AS routing_observed_at,
  COALESCE(p.default_access, p.access, 'legacy_public')::text AS access
FROM sandbox s
LEFT JOIN sandbox_preview_policy p ON p.sandbox_id = s.id
WHERE s.id = $1 AND s.team_id = $2 AND s.destroyed_at IS NULL
`

type GetSandboxWithPreviewPolicyForRoutingParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

type GetSandboxWithPreviewPolicyForRoutingRow struct {
	Sandbox           Sandbox   `json:"sandbox"`
	RoutingObservedAt time.Time `json:"routing_observed_at"`
	Access            string    `json:"access"`
}

// GetSandbox plus the effective preview access, so read endpoints return
// both in one round-trip.
func (q *Queries) GetSandboxWithPreviewPolicyForRouting(ctx context.Context, arg GetSandboxWithPreviewPolicyForRoutingParams) (GetSandboxWithPreviewPolicyForRoutingRow, error) {
	row := q.db.QueryRow(ctx, getSandboxWithPreviewPolicyForRouting, arg.ID, arg.TeamID)
	var i GetSandboxWithPreviewPolicyForRoutingRow
	err := row.Scan(
		&i.Sandbox.ID,
		&i.Sandbox.TeamID,
		&i.Sandbox.Name,
		&i.Sandbox.Status,
		&i.Sandbox.VcpuCount,
		&i.Sandbox.MemoryMib,
		&i.Sandbox.HostID,
		&i.Sandbox.IpAddress,
		&i.Sandbox.Pid,
		&i.Sandbox.SnapshotID,
		&i.Sandbox.CreatedAt,
		&i.Sandbox.UpdatedAt,
		&i.Sandbox.DestroyedAt,
		&i.Sandbox.NetworkConfig,
		&i.Sandbox.TimeoutSeconds,
		&i.Sandbox.Metadata,
		&i.Sandbox.TemplateID,
		&i.Sandbox.SnapshotPath,
		&i.Sandbox.MemPath,
		&i.Sandbox.BasePath,
		&i.Sandbox.DeltaPath,
		&i.Sandbox.DiskMib,
		&i.Sandbox.AutoDeleteSeconds,
		&i.Sandbox.AutoDeleteAt,
		&i.Sandbox.FailedAt,
		&i.Sandbox.HadSecretBindings,
		&i.Sandbox.SecretEnvFingerprint,
		&i.Sandbox.SecretEnvIp,
		&i.Sandbox.SecretEnvInjectedAt,
		&i.Sandbox.SecretEnvExpiresAt,
		&i.Sandbox.PauseOpID,
		&i.Sandbox.PauseOpStartedAt,
		&i.Sandbox.PauseOpLeaseUntil,
		&i.Sandbox.PauseOpLeaseVersion,
		&i.Sandbox.PauseOpAttentionAt,
		&i.Sandbox.PauseOpTrigger,
		&i.Sandbox.PauseOpActorID,
		&i.Sandbox.RoutingVersion,
		&i.Sandbox.LegacyStorageRefs,
		&i.Sandbox.SourceSnapshotID,
		&i.RoutingObservedAt,
		&i.Access,
	)
	return i, err
}

const pruneRoutingRevocations = `-- name: PruneRoutingRevocations :exec
SELECT routing_private.prune_revocations($1::timestamptz)
`

func (q *Queries) PruneRoutingRevocations(ctx context.Context, dollar_1 time.Time) error {
	_, err := q.db.Exec(ctx, pruneRoutingRevocations, dollar_1)
	return err
}
