// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sandbox_active_intervals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeSandboxActiveInterval = `-- name: CloseSandboxActiveInterval :exec
UPDATE sandbox_active_interval
SET ended_at = now(),
    end_reason = $2
WHERE sandbox_id = $1
  AND ended_at IS NULL
`

type CloseSandboxActiveIntervalParams struct {
	SandboxID uuid.UUID `json:"sandbox_id"`
	EndReason *string   `json:"end_reason"`
}

// Closes the currently-open interval for a sandbox. The WHERE ended_at IS NULL
// filter is load-bearing: if the sandbox transitions out of 'active' twice
// without an intervening open (e.g. 'paused' followed later by 'deleted'),
// only the first call closes the row — the second is a no-op so we don't
// over-report active time.
func (q *Queries) CloseSandboxActiveInterval(ctx context.Context, arg CloseSandboxActiveIntervalParams) error {
	_, err := q.db.Exec(ctx, closeSandboxActiveInterval, arg.SandboxID, arg.EndReason)
	return err
}

const openSandboxActiveInterval = `-- name: OpenSandboxActiveInterval :exec
INSERT INTO sandbox_active_interval (sandbox_id, team_id, actor_id, started_at)
VALUES ($1, $2, $3, now())
`

type OpenSandboxActiveIntervalParams struct {
	SandboxID uuid.UUID   `json:"sandbox_id"`
	TeamID    uuid.UUID   `json:"team_id"`
	ActorID   pgtype.UUID `json:"actor_id"`
}

// Opens an interval row when a sandbox transitions into 'active' (created or
// resumed). The partial unique index sandbox_active_interval(sandbox_id) WHERE
// ended_at IS NULL guarantees at most one open row per sandbox at any time;
// in the unlikely event a prior open row was left dangling, the caller should
// treat the unique-violation as recoverable (sandbox is already considered
// running) rather than a hard error.
func (q *Queries) OpenSandboxActiveInterval(ctx context.Context, arg OpenSandboxActiveIntervalParams) error {
	_, err := q.db.Exec(ctx, openSandboxActiveInterval, arg.SandboxID, arg.TeamID, arg.ActorID)
	return err
}
