// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sandboxes.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateSandbox = `-- name: ActivateSandbox :exec
UPDATE sandbox
SET status = 'active',
    vcpu_count = $2,
    memory_mib = $3,
    ip_address = $4,
    updated_at = now()
WHERE id = $1 AND team_id = $5 AND destroyed_at IS NULL
`

type ActivateSandboxParams struct {
	ID        uuid.UUID   `json:"id"`
	VcpuCount int32       `json:"vcpu_count"`
	MemoryMib int32       `json:"memory_mib"`
	IpAddress *netip.Addr `json:"ip_address"`
	TeamID    uuid.UUID   `json:"team_id"`
}

func (q *Queries) ActivateSandbox(ctx context.Context, arg ActivateSandboxParams) error {
	_, err := q.db.Exec(ctx, activateSandbox,
		arg.ID,
		arg.VcpuCount,
		arg.MemoryMib,
		arg.IpAddress,
		arg.TeamID,
	)
	return err
}

const beginPause = `-- name: BeginPause :one
UPDATE sandbox
SET status = 'pausing', updated_at = now()
WHERE id = $1 AND team_id = $2 AND destroyed_at IS NULL AND status = 'active'
RETURNING id, team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, created_at, updated_at, destroyed_at, network_config, timeout_seconds, metadata, template_id
`

type BeginPauseParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

// Atomic ownership + state check + transition to 'pausing'. Replaces the
// GetSandbox → check status → UpdateSandboxStatus sequence on the pause
// hot path, collapsing two DB roundtrips into one. The WHERE clause
// enforces the invariant (only active, non-deleted sandboxes owned by
// this team can be paused); a 0-row result means "no such sandbox OR
// wrong team OR not currently active", and the caller disambiguates via
// a fallback GetSandbox in the rare error path.
func (q *Queries) BeginPause(ctx context.Context, arg BeginPauseParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, beginPause, arg.ID, arg.TeamID)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.VcpuCount,
		&i.MemoryMib,
		&i.HostID,
		&i.IpAddress,
		&i.Pid,
		&i.SnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestroyedAt,
		&i.NetworkConfig,
		&i.TimeoutSeconds,
		&i.Metadata,
		&i.TemplateID,
	)
	return i, err
}

const claimExpiredSandboxes = `-- name: ClaimExpiredSandboxes :many
WITH expired AS (
  SELECT id, team_id, name, snapshot_id, host_id
  FROM sandbox
  WHERE destroyed_at IS NULL
    AND timeout_seconds IS NOT NULL
    AND status = 'active'
    AND created_at + (timeout_seconds || ' seconds')::interval < now()
    AND created_at < now() - interval '60 seconds'
  ORDER BY created_at ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE sandbox
SET status = 'pausing', updated_at = now()
FROM expired
WHERE sandbox.id = expired.id
RETURNING expired.id, expired.team_id, expired.name, expired.snapshot_id, expired.host_id
`

type ClaimExpiredSandboxesRow struct {
	ID         uuid.UUID   `json:"id"`
	TeamID     uuid.UUID   `json:"team_id"`
	Name       string      `json:"name"`
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	HostID     string      `json:"host_id"`
}

// Atomically claims active sandboxes whose hard timeout has elapsed and marks
// them as 'pausing'. FOR UPDATE SKIP LOCKED lets concurrent reaper replicas
// skip rows already being processed, so multi-replica Cloud Run deployments
// do not double-process the same sandbox.
//
// Only 'active' sandboxes are claimed — paused sandboxes are already stopped,
// and transient states (starting, pausing) are skipped to avoid racing with
// in-progress operations. The 60-second grace window prevents reaping a sandbox
// that was just created with a very short timeout before it finishes starting up.
func (q *Queries) ClaimExpiredSandboxes(ctx context.Context, limit int32) ([]ClaimExpiredSandboxesRow, error) {
	rows, err := q.db.Query(ctx, claimExpiredSandboxes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimExpiredSandboxesRow{}
	for rows.Next() {
		var i ClaimExpiredSandboxesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.SnapshotID,
			&i.HostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSandbox = `-- name: CreateSandbox :one
INSERT INTO sandbox (id, team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, timeout_seconds, metadata, template_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, created_at, updated_at, destroyed_at, network_config, timeout_seconds, metadata, template_id
`

type CreateSandboxParams struct {
	ID             uuid.UUID     `json:"id"`
	TeamID         uuid.UUID     `json:"team_id"`
	Name           string        `json:"name"`
	Status         SandboxStatus `json:"status"`
	VcpuCount      int32         `json:"vcpu_count"`
	MemoryMib      int32         `json:"memory_mib"`
	HostID         string        `json:"host_id"`
	IpAddress      *netip.Addr   `json:"ip_address"`
	Pid            *int32        `json:"pid"`
	SnapshotID     pgtype.UUID   `json:"snapshot_id"`
	TimeoutSeconds *int32        `json:"timeout_seconds"`
	Metadata       []byte        `json:"metadata"`
	TemplateID     pgtype.UUID   `json:"template_id"`
}

// ID is supplied by the caller (generated in Go via uuid.New()) rather
// than defaulted in SQL, so the caller can parallelize this INSERT with
// the VMD CreateVM call — both need the same sandbox_id and generating
// it client-side lets them run concurrently instead of strictly serially.
// template_id is optional (NULL when sandbox is not derived from a template).
func (q *Queries) CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, createSandbox,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Status,
		arg.VcpuCount,
		arg.MemoryMib,
		arg.HostID,
		arg.IpAddress,
		arg.Pid,
		arg.SnapshotID,
		arg.TimeoutSeconds,
		arg.Metadata,
		arg.TemplateID,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.VcpuCount,
		&i.MemoryMib,
		&i.HostID,
		&i.IpAddress,
		&i.Pid,
		&i.SnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestroyedAt,
		&i.NetworkConfig,
		&i.TimeoutSeconds,
		&i.Metadata,
		&i.TemplateID,
	)
	return i, err
}

const deleteSnapshotRow = `-- name: DeleteSnapshotRow :execrows
DELETE FROM snapshot
WHERE id = $1 AND team_id = $2 AND saved = false
`

type DeleteSnapshotRowParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

// Remove a snapshot row. Guarded by saved=false so a future template feature
// can rely on row durability — auto-GC callers cannot accidentally nuke a
// user-saved snapshot even if they passed the wrong ID.
func (q *Queries) DeleteSnapshotRow(ctx context.Context, arg DeleteSnapshotRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSnapshotRow, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const destroySandbox = `-- name: DestroySandbox :exec
UPDATE sandbox
SET destroyed_at = now(), status = 'deleted', updated_at = now()
WHERE id = $1 AND team_id = $2 AND destroyed_at IS NULL
`

type DestroySandboxParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) DestroySandbox(ctx context.Context, arg DestroySandboxParams) error {
	_, err := q.db.Exec(ctx, destroySandbox, arg.ID, arg.TeamID)
	return err
}

const finalizePause = `-- name: FinalizePause :one
WITH target AS (
  SELECT id, team_id, snapshot_id AS prev_snapshot_id FROM sandbox
  WHERE id = $1 AND team_id = $2 AND destroyed_at IS NULL
),
new_snapshot AS (
  INSERT INTO snapshot (sandbox_id, team_id, path, mem_path, size_bytes, saved, name, trigger)
  SELECT target.id, target.team_id, $3, $4, $5, $6, $7, $8 FROM target
  RETURNING snapshot.id AS snap_id
)
UPDATE sandbox
SET snapshot_id = (SELECT snap_id FROM new_snapshot),
    status = 'paused',
    updated_at = now()
FROM new_snapshot
WHERE sandbox.id = $1 AND sandbox.team_id = $2 AND sandbox.destroyed_at IS NULL
RETURNING
  new_snapshot.snap_id::uuid AS snapshot_id,
  (SELECT prev_snapshot_id FROM target) AS prev_snapshot_id
`

type FinalizePauseParams struct {
	ID        uuid.UUID `json:"id"`
	TeamID    uuid.UUID `json:"team_id"`
	Path      string    `json:"path"`
	MemPath   *string   `json:"mem_path"`
	SizeBytes int64     `json:"size_bytes"`
	Saved     bool      `json:"saved"`
	Name      *string   `json:"name"`
	Trigger   string    `json:"trigger"`
}

type FinalizePauseRow struct {
	SnapshotID     uuid.UUID   `json:"snapshot_id"`
	PrevSnapshotID pgtype.UUID `json:"prev_snapshot_id"`
}

// Atomically insert the snapshot row, link it to the sandbox, and flip
// status from 'pausing' to 'paused'. Replaces the sequence
// CreateSnapshot → SetSandboxSnapshot → UpdateSandboxStatus, collapsing
// three DB roundtrips into one.
//
// The INSERT is gated on a `WHERE EXISTS` against a non-deleted sandbox
// in the same query. This prevents the common race where a sandbox is
// soft-deleted before FinalizePause runs — without the gate, the CTE
// INSERT would always execute (per PostgreSQL's rule that data-modifying
// CTEs run independently of the main query), producing an orphan snapshot
// row and a snapshot file on disk with no owner. A concurrent delete that
// commits BETWEEN the EXISTS check and the INSERT under READ COMMITTED
// can still race, but that window is microseconds and the resulting
// orphan is detectable/cleanable by a background job.
//
// Also captures the sandbox's previous snapshot_id (before we overwrite it)
// so the caller can garbage-collect the now-unreachable prior snapshot
// asynchronously. Returns NULL for the first pause of a sandbox.
//
// When either the sandbox is missing/deleted or the INSERT did not fire,
// the query returns 0 rows and the caller maps that to ErrSandboxGone.
func (q *Queries) FinalizePause(ctx context.Context, arg FinalizePauseParams) (FinalizePauseRow, error) {
	row := q.db.QueryRow(ctx, finalizePause,
		arg.ID,
		arg.TeamID,
		arg.Path,
		arg.MemPath,
		arg.SizeBytes,
		arg.Saved,
		arg.Name,
		arg.Trigger,
	)
	var i FinalizePauseRow
	err := row.Scan(&i.SnapshotID, &i.PrevSnapshotID)
	return i, err
}

const getSandbox = `-- name: GetSandbox :one
SELECT id, team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, created_at, updated_at, destroyed_at, network_config, timeout_seconds, metadata, template_id FROM sandbox
WHERE id = $1 AND team_id = $2 AND destroyed_at IS NULL
`

type GetSandboxParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) GetSandbox(ctx context.Context, arg GetSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandbox, arg.ID, arg.TeamID)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.VcpuCount,
		&i.MemoryMib,
		&i.HostID,
		&i.IpAddress,
		&i.Pid,
		&i.SnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestroyedAt,
		&i.NetworkConfig,
		&i.TimeoutSeconds,
		&i.Metadata,
		&i.TemplateID,
	)
	return i, err
}

const getSandboxNetworkConfig = `-- name: GetSandboxNetworkConfig :one
SELECT network_config FROM sandbox
WHERE id = $1 AND team_id = $2 AND destroyed_at IS NULL
`

type GetSandboxNetworkConfigParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) GetSandboxNetworkConfig(ctx context.Context, arg GetSandboxNetworkConfigParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSandboxNetworkConfig, arg.ID, arg.TeamID)
	var network_config []byte
	err := row.Scan(&network_config)
	return network_config, err
}

const getSnapshotForCleanup = `-- name: GetSnapshotForCleanup :one
SELECT id, team_id, path, mem_path
FROM snapshot
WHERE id = $1 AND team_id = $2 AND saved = false
`

type GetSnapshotForCleanupParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

type GetSnapshotForCleanupRow struct {
	ID      uuid.UUID `json:"id"`
	TeamID  uuid.UUID `json:"team_id"`
	Path    string    `json:"path"`
	MemPath *string   `json:"mem_path"`
}

// Fetch a snapshot's paths for garbage collection. Returns only non-saved
// snapshots — saved=true rows are reserved for the (future) user-named
// template feature and must never be auto-deleted. A 0-row result means
// the row was already gone or is a saved snapshot; either way the caller
// should skip deletion.
func (q *Queries) GetSnapshotForCleanup(ctx context.Context, arg GetSnapshotForCleanupParams) (GetSnapshotForCleanupRow, error) {
	row := q.db.QueryRow(ctx, getSnapshotForCleanup, arg.ID, arg.TeamID)
	var i GetSnapshotForCleanupRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Path,
		&i.MemPath,
	)
	return i, err
}

const listSandboxesByHost = `-- name: ListSandboxesByHost :many
SELECT id, team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, created_at, updated_at, destroyed_at, network_config, timeout_seconds, metadata, template_id FROM sandbox
WHERE host_id = $1 AND destroyed_at IS NULL
`

// Used by the VMD reconciler to find all non-deleted sandboxes scheduled on
// this host. Includes both active and paused sandboxes because the reconciler
// needs to validate both states (active → systemd unit, paused → snapshot file).
func (q *Queries) ListSandboxesByHost(ctx context.Context, hostID string) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Status,
			&i.VcpuCount,
			&i.MemoryMib,
			&i.HostID,
			&i.IpAddress,
			&i.Pid,
			&i.SnapshotID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestroyedAt,
			&i.NetworkConfig,
			&i.TimeoutSeconds,
			&i.Metadata,
			&i.TemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesByTeam = `-- name: ListSandboxesByTeam :many
SELECT id, team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, created_at, updated_at, destroyed_at, network_config, timeout_seconds, metadata, template_id FROM sandbox
WHERE team_id = $1 AND destroyed_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSandboxesByTeam(ctx context.Context, teamID uuid.UUID) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Status,
			&i.VcpuCount,
			&i.MemoryMib,
			&i.HostID,
			&i.IpAddress,
			&i.Pid,
			&i.SnapshotID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestroyedAt,
			&i.NetworkConfig,
			&i.TimeoutSeconds,
			&i.Metadata,
			&i.TemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesByTeamWithFilter = `-- name: ListSandboxesByTeamWithFilter :many
SELECT id, team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, created_at, updated_at, destroyed_at, network_config, timeout_seconds, metadata, template_id FROM sandbox
WHERE team_id = $1
  AND destroyed_at IS NULL
  AND metadata @> $2
ORDER BY created_at DESC
`

type ListSandboxesByTeamWithFilterParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	Metadata []byte    `json:"metadata"`
}

// Same as ListSandboxesByTeam but additionally filters rows whose metadata
// contains every key/value pair in $2 (jsonb @> containment). Pass an empty
// object '{}'::jsonb to match everything — but prefer ListSandboxesByTeam
// in that case so we don't pay the (still tiny) cost of the @> evaluation.
func (q *Queries) ListSandboxesByTeamWithFilter(ctx context.Context, arg ListSandboxesByTeamWithFilterParams) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByTeamWithFilter, arg.TeamID, arg.Metadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Status,
			&i.VcpuCount,
			&i.MemoryMib,
			&i.HostID,
			&i.IpAddress,
			&i.Pid,
			&i.SnapshotID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestroyedAt,
			&i.NetworkConfig,
			&i.TimeoutSeconds,
			&i.Metadata,
			&i.TemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSandboxFailed = `-- name: MarkSandboxFailed :exec
UPDATE sandbox
SET status = 'failed', updated_at = now()
WHERE id = $1 AND destroyed_at IS NULL
`

// Used by the reconciler to mark a sandbox failed when VMD detects it is
// actually gone. No team_id filter — the reconciler runs with host scope,
// not team scope.
func (q *Queries) MarkSandboxFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSandboxFailed, id)
	return err
}

const sandboxExists = `-- name: SandboxExists :one
SELECT EXISTS(SELECT 1 FROM sandbox WHERE id = $1 AND team_id = $2 AND destroyed_at IS NULL)
`

type SandboxExistsParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) SandboxExists(ctx context.Context, arg SandboxExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, sandboxExists, arg.ID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setSandboxSnapshot = `-- name: SetSandboxSnapshot :exec
UPDATE sandbox
SET snapshot_id = $2, updated_at = now()
WHERE id = $1 AND team_id = $3 AND destroyed_at IS NULL
`

type SetSandboxSnapshotParams struct {
	ID         uuid.UUID   `json:"id"`
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	TeamID     uuid.UUID   `json:"team_id"`
}

func (q *Queries) SetSandboxSnapshot(ctx context.Context, arg SetSandboxSnapshotParams) error {
	_, err := q.db.Exec(ctx, setSandboxSnapshot, arg.ID, arg.SnapshotID, arg.TeamID)
	return err
}

const updateSandboxHost = `-- name: UpdateSandboxHost :exec
UPDATE sandbox
SET host_id = $2, ip_address = $3, pid = $4, updated_at = now()
WHERE id = $1 AND team_id = $5 AND destroyed_at IS NULL
`

type UpdateSandboxHostParams struct {
	ID        uuid.UUID   `json:"id"`
	HostID    string      `json:"host_id"`
	IpAddress *netip.Addr `json:"ip_address"`
	Pid       *int32      `json:"pid"`
	TeamID    uuid.UUID   `json:"team_id"`
}

func (q *Queries) UpdateSandboxHost(ctx context.Context, arg UpdateSandboxHostParams) error {
	_, err := q.db.Exec(ctx, updateSandboxHost,
		arg.ID,
		arg.HostID,
		arg.IpAddress,
		arg.Pid,
		arg.TeamID,
	)
	return err
}

const updateSandboxMetadata = `-- name: UpdateSandboxMetadata :exec
UPDATE sandbox
SET metadata = $2, updated_at = now()
WHERE id = $1 AND team_id = $3 AND destroyed_at IS NULL
`

type UpdateSandboxMetadataParams struct {
	ID       uuid.UUID `json:"id"`
	Metadata []byte    `json:"metadata"`
	TeamID   uuid.UUID `json:"team_id"`
}

func (q *Queries) UpdateSandboxMetadata(ctx context.Context, arg UpdateSandboxMetadataParams) error {
	_, err := q.db.Exec(ctx, updateSandboxMetadata, arg.ID, arg.Metadata, arg.TeamID)
	return err
}

const updateSandboxNetworkConfig = `-- name: UpdateSandboxNetworkConfig :exec
UPDATE sandbox
SET network_config = $2, updated_at = now()
WHERE id = $1 AND team_id = $3 AND destroyed_at IS NULL
`

type UpdateSandboxNetworkConfigParams struct {
	ID            uuid.UUID `json:"id"`
	NetworkConfig []byte    `json:"network_config"`
	TeamID        uuid.UUID `json:"team_id"`
}

func (q *Queries) UpdateSandboxNetworkConfig(ctx context.Context, arg UpdateSandboxNetworkConfigParams) error {
	_, err := q.db.Exec(ctx, updateSandboxNetworkConfig, arg.ID, arg.NetworkConfig, arg.TeamID)
	return err
}

const updateSandboxStatus = `-- name: UpdateSandboxStatus :exec
UPDATE sandbox
SET status = $2, updated_at = now()
WHERE id = $1 AND team_id = $3 AND destroyed_at IS NULL
`

type UpdateSandboxStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status SandboxStatus `json:"status"`
	TeamID uuid.UUID     `json:"team_id"`
}

func (q *Queries) UpdateSandboxStatus(ctx context.Context, arg UpdateSandboxStatusParams) error {
	_, err := q.db.Exec(ctx, updateSandboxStatus, arg.ID, arg.Status, arg.TeamID)
	return err
}
