// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sandbox_snapshots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const beginSandboxSnapshotDelete = `-- name: BeginSandboxSnapshotDelete :one
UPDATE sandbox_snapshot SET status = 'deleting'
WHERE id = $1 AND team_id = $2 AND deleted_at IS NULL AND status <> 'creating'
RETURNING id, team_id, sandbox_id, template_id, kind, status, name, idempotency_key, host_id, vcpu_count, memory_mib, disk_mib, base_path, base_mem_path, snapshot_path, mem_path, overlay_path, size_bytes, timeout_seconds, network_config, secret_bindings, fc_build_sha, guest_kernel, snapshot_format, created_at, ready_at, deleted_at
`

type BeginSandboxSnapshotDeleteParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

// A row still creating is left to its capture and the sweep: deleting it
// here could leave the host holding a snapshot no row names. A row already
// deleting is driven again.
func (q *Queries) BeginSandboxSnapshotDelete(ctx context.Context, arg BeginSandboxSnapshotDeleteParams) (SandboxSnapshot, error) {
	row := q.db.QueryRow(ctx, beginSandboxSnapshotDelete, arg.ID, arg.TeamID)
	var i SandboxSnapshot
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SandboxID,
		&i.TemplateID,
		&i.Kind,
		&i.Status,
		&i.Name,
		&i.IdempotencyKey,
		&i.HostID,
		&i.VcpuCount,
		&i.MemoryMib,
		&i.DiskMib,
		&i.BasePath,
		&i.BaseMemPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.OverlayPath,
		&i.SizeBytes,
		&i.TimeoutSeconds,
		&i.NetworkConfig,
		&i.SecretBindings,
		&i.FcBuildSha,
		&i.GuestKernel,
		&i.SnapshotFormat,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.DeletedAt,
	)
	return i, err
}

const countSandboxSnapshots = `-- name: CountSandboxSnapshots :one
SELECT count(*) FROM sandbox_snapshot
WHERE team_id = $1 AND sandbox_id = $2 AND deleted_at IS NULL
`

type CountSandboxSnapshotsParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	SandboxID uuid.UUID `json:"sandbox_id"`
}

func (q *Queries) CountSandboxSnapshots(ctx context.Context, arg CountSandboxSnapshotsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSandboxSnapshots, arg.TeamID, arg.SandboxID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamSnapshotsCreating = `-- name: CountTeamSnapshotsCreating :one
SELECT count(*) FROM sandbox_snapshot
WHERE team_id = $1 AND status = 'creating' AND deleted_at IS NULL
`

func (q *Queries) CountTeamSnapshotsCreating(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamSnapshotsCreating, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSandboxSnapshot = `-- name: CreateSandboxSnapshot :one
INSERT INTO sandbox_snapshot (
    id, team_id, sandbox_id, template_id, kind, status, name, idempotency_key,
    host_id, vcpu_count, memory_mib, disk_mib, base_path,
    timeout_seconds, network_config, secret_bindings
) VALUES (
    $1, $2, $3, $4, $5, 'creating', $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15
)
RETURNING id, team_id, sandbox_id, template_id, kind, status, name, idempotency_key, host_id, vcpu_count, memory_mib, disk_mib, base_path, base_mem_path, snapshot_path, mem_path, overlay_path, size_bytes, timeout_seconds, network_config, secret_bindings, fc_build_sha, guest_kernel, snapshot_format, created_at, ready_at, deleted_at
`

type CreateSandboxSnapshotParams struct {
	ID             uuid.UUID   `json:"id"`
	TeamID         uuid.UUID   `json:"team_id"`
	SandboxID      uuid.UUID   `json:"sandbox_id"`
	TemplateID     pgtype.UUID `json:"template_id"`
	Kind           string      `json:"kind"`
	Name           *string     `json:"name"`
	IdempotencyKey *string     `json:"idempotency_key"`
	HostID         string      `json:"host_id"`
	VcpuCount      int32       `json:"vcpu_count"`
	MemoryMib      int32       `json:"memory_mib"`
	DiskMib        int32       `json:"disk_mib"`
	BasePath       string      `json:"base_path"`
	TimeoutSeconds *int32      `json:"timeout_seconds"`
	NetworkConfig  []byte      `json:"network_config"`
	SecretBindings []byte      `json:"secret_bindings"`
}

// The row exists as creating before the host is asked, under the id the
// host's capture is keyed by, so an answer lost on the way back is settled
// later from the host (see the snapshot sweep). The quota trigger counts on
// insert; a retry carrying an idempotency key already on file is refused by
// the unique index and re-read by the caller.
func (q *Queries) CreateSandboxSnapshot(ctx context.Context, arg CreateSandboxSnapshotParams) (SandboxSnapshot, error) {
	row := q.db.QueryRow(ctx, createSandboxSnapshot,
		arg.ID,
		arg.TeamID,
		arg.SandboxID,
		arg.TemplateID,
		arg.Kind,
		arg.Name,
		arg.IdempotencyKey,
		arg.HostID,
		arg.VcpuCount,
		arg.MemoryMib,
		arg.DiskMib,
		arg.BasePath,
		arg.TimeoutSeconds,
		arg.NetworkConfig,
		arg.SecretBindings,
	)
	var i SandboxSnapshot
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SandboxID,
		&i.TemplateID,
		&i.Kind,
		&i.Status,
		&i.Name,
		&i.IdempotencyKey,
		&i.HostID,
		&i.VcpuCount,
		&i.MemoryMib,
		&i.DiskMib,
		&i.BasePath,
		&i.BaseMemPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.OverlayPath,
		&i.SizeBytes,
		&i.TimeoutSeconds,
		&i.NetworkConfig,
		&i.SecretBindings,
		&i.FcBuildSha,
		&i.GuestKernel,
		&i.SnapshotFormat,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSandboxSnapshot = `-- name: GetSandboxSnapshot :one
SELECT id, team_id, sandbox_id, template_id, kind, status, name, idempotency_key, host_id, vcpu_count, memory_mib, disk_mib, base_path, base_mem_path, snapshot_path, mem_path, overlay_path, size_bytes, timeout_seconds, network_config, secret_bindings, fc_build_sha, guest_kernel, snapshot_format, created_at, ready_at, deleted_at FROM sandbox_snapshot
WHERE id = $1 AND team_id = $2 AND deleted_at IS NULL
`

type GetSandboxSnapshotParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

// Team-scoped: another team's row and a deleted row are the same 404.
func (q *Queries) GetSandboxSnapshot(ctx context.Context, arg GetSandboxSnapshotParams) (SandboxSnapshot, error) {
	row := q.db.QueryRow(ctx, getSandboxSnapshot, arg.ID, arg.TeamID)
	var i SandboxSnapshot
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SandboxID,
		&i.TemplateID,
		&i.Kind,
		&i.Status,
		&i.Name,
		&i.IdempotencyKey,
		&i.HostID,
		&i.VcpuCount,
		&i.MemoryMib,
		&i.DiskMib,
		&i.BasePath,
		&i.BaseMemPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.OverlayPath,
		&i.SizeBytes,
		&i.TimeoutSeconds,
		&i.NetworkConfig,
		&i.SecretBindings,
		&i.FcBuildSha,
		&i.GuestKernel,
		&i.SnapshotFormat,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSandboxSnapshotByIdempotencyKey = `-- name: GetSandboxSnapshotByIdempotencyKey :one
SELECT id, team_id, sandbox_id, template_id, kind, status, name, idempotency_key, host_id, vcpu_count, memory_mib, disk_mib, base_path, base_mem_path, snapshot_path, mem_path, overlay_path, size_bytes, timeout_seconds, network_config, secret_bindings, fc_build_sha, guest_kernel, snapshot_format, created_at, ready_at, deleted_at FROM sandbox_snapshot
WHERE team_id = $1 AND sandbox_id = $2 AND idempotency_key = $3 AND deleted_at IS NULL
`

type GetSandboxSnapshotByIdempotencyKeyParams struct {
	TeamID         uuid.UUID `json:"team_id"`
	SandboxID      uuid.UUID `json:"sandbox_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

func (q *Queries) GetSandboxSnapshotByIdempotencyKey(ctx context.Context, arg GetSandboxSnapshotByIdempotencyKeyParams) (SandboxSnapshot, error) {
	row := q.db.QueryRow(ctx, getSandboxSnapshotByIdempotencyKey, arg.TeamID, arg.SandboxID, arg.IdempotencyKey)
	var i SandboxSnapshot
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SandboxID,
		&i.TemplateID,
		&i.Kind,
		&i.Status,
		&i.Name,
		&i.IdempotencyKey,
		&i.HostID,
		&i.VcpuCount,
		&i.MemoryMib,
		&i.DiskMib,
		&i.BasePath,
		&i.BaseMemPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.OverlayPath,
		&i.SizeBytes,
		&i.TimeoutSeconds,
		&i.NetworkConfig,
		&i.SecretBindings,
		&i.FcBuildSha,
		&i.GuestKernel,
		&i.SnapshotFormat,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSandboxSnapshots = `-- name: ListSandboxSnapshots :many
SELECT id, team_id, sandbox_id, template_id, kind, status, name, idempotency_key, host_id, vcpu_count, memory_mib, disk_mib, base_path, base_mem_path, snapshot_path, mem_path, overlay_path, size_bytes, timeout_seconds, network_config, secret_bindings, fc_build_sha, guest_kernel, snapshot_format, created_at, ready_at, deleted_at FROM sandbox_snapshot
WHERE team_id = $1 AND sandbox_id = $2 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $4::bigint OFFSET $3::bigint
`

type ListSandboxSnapshotsParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	SandboxID uuid.UUID `json:"sandbox_id"`
	RowOffset int64     `json:"row_offset"`
	RowLimit  *int64    `json:"row_limit"`
}

func (q *Queries) ListSandboxSnapshots(ctx context.Context, arg ListSandboxSnapshotsParams) ([]SandboxSnapshot, error) {
	rows, err := q.db.Query(ctx, listSandboxSnapshots,
		arg.TeamID,
		arg.SandboxID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SandboxSnapshot{}
	for rows.Next() {
		var i SandboxSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.SandboxID,
			&i.TemplateID,
			&i.Kind,
			&i.Status,
			&i.Name,
			&i.IdempotencyKey,
			&i.HostID,
			&i.VcpuCount,
			&i.MemoryMib,
			&i.DiskMib,
			&i.BasePath,
			&i.BaseMemPath,
			&i.SnapshotPath,
			&i.MemPath,
			&i.OverlayPath,
			&i.SizeBytes,
			&i.TimeoutSeconds,
			&i.NetworkConfig,
			&i.SecretBindings,
			&i.FcBuildSha,
			&i.GuestKernel,
			&i.SnapshotFormat,
			&i.CreatedAt,
			&i.ReadyAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckSandboxSnapshots = `-- name: ListStuckSandboxSnapshots :many
SELECT id, team_id, sandbox_id, template_id, kind, status, name, idempotency_key, host_id, vcpu_count, memory_mib, disk_mib, base_path, base_mem_path, snapshot_path, mem_path, overlay_path, size_bytes, timeout_seconds, network_config, secret_bindings, fc_build_sha, guest_kernel, snapshot_format, created_at, ready_at, deleted_at FROM sandbox_snapshot
WHERE deleted_at IS NULL
  AND ((status = 'creating' AND created_at < $1) OR status = 'deleting')
ORDER BY created_at
LIMIT $2::bigint
`

type ListStuckSandboxSnapshotsParams struct {
	CreatingBefore time.Time `json:"creating_before"`
	RowLimit       int64     `json:"row_limit"`
}

// Rows a capture or a delete left behind: creating since before the time a
// capture can take, or deleting at all. Unscoped, for the sweep.
func (q *Queries) ListStuckSandboxSnapshots(ctx context.Context, arg ListStuckSandboxSnapshotsParams) ([]SandboxSnapshot, error) {
	rows, err := q.db.Query(ctx, listStuckSandboxSnapshots, arg.CreatingBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SandboxSnapshot{}
	for rows.Next() {
		var i SandboxSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.SandboxID,
			&i.TemplateID,
			&i.Kind,
			&i.Status,
			&i.Name,
			&i.IdempotencyKey,
			&i.HostID,
			&i.VcpuCount,
			&i.MemoryMib,
			&i.DiskMib,
			&i.BasePath,
			&i.BaseMemPath,
			&i.SnapshotPath,
			&i.MemPath,
			&i.OverlayPath,
			&i.SizeBytes,
			&i.TimeoutSeconds,
			&i.NetworkConfig,
			&i.SecretBindings,
			&i.FcBuildSha,
			&i.GuestKernel,
			&i.SnapshotFormat,
			&i.CreatedAt,
			&i.ReadyAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSandboxSnapshotDeleted = `-- name: MarkSandboxSnapshotDeleted :execrows
UPDATE sandbox_snapshot SET deleted_at = now()
WHERE id = $1 AND status = 'deleting' AND deleted_at IS NULL
`

func (q *Queries) MarkSandboxSnapshotDeleted(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSandboxSnapshotDeleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSandboxSnapshotFailed = `-- name: MarkSandboxSnapshotFailed :execrows
UPDATE sandbox_snapshot SET status = 'failed'
WHERE id = $1 AND status = 'creating'
`

func (q *Queries) MarkSandboxSnapshotFailed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSandboxSnapshotFailed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSandboxSnapshotReady = `-- name: MarkSandboxSnapshotReady :one
UPDATE sandbox_snapshot
SET status = 'ready', ready_at = now(),
    base_mem_path = $1, snapshot_path = $2,
    mem_path = $3, overlay_path = $4,
    size_bytes = $5, fc_build_sha = $6
WHERE id = $7 AND status = 'creating'
RETURNING id, team_id, sandbox_id, template_id, kind, status, name, idempotency_key, host_id, vcpu_count, memory_mib, disk_mib, base_path, base_mem_path, snapshot_path, mem_path, overlay_path, size_bytes, timeout_seconds, network_config, secret_bindings, fc_build_sha, guest_kernel, snapshot_format, created_at, ready_at, deleted_at
`

type MarkSandboxSnapshotReadyParams struct {
	BaseMemPath  *string   `json:"base_mem_path"`
	SnapshotPath *string   `json:"snapshot_path"`
	MemPath      *string   `json:"mem_path"`
	OverlayPath  *string   `json:"overlay_path"`
	SizeBytes    int64     `json:"size_bytes"`
	FcBuildSha   *string   `json:"fc_build_sha"`
	ID           uuid.UUID `json:"id"`
}

// Only a row still creating becomes ready: the request that started the
// capture and the sweep may both carry the host's answer.
func (q *Queries) MarkSandboxSnapshotReady(ctx context.Context, arg MarkSandboxSnapshotReadyParams) (SandboxSnapshot, error) {
	row := q.db.QueryRow(ctx, markSandboxSnapshotReady,
		arg.BaseMemPath,
		arg.SnapshotPath,
		arg.MemPath,
		arg.OverlayPath,
		arg.SizeBytes,
		arg.FcBuildSha,
		arg.ID,
	)
	var i SandboxSnapshot
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SandboxID,
		&i.TemplateID,
		&i.Kind,
		&i.Status,
		&i.Name,
		&i.IdempotencyKey,
		&i.HostID,
		&i.VcpuCount,
		&i.MemoryMib,
		&i.DiskMib,
		&i.BasePath,
		&i.BaseMemPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.OverlayPath,
		&i.SizeBytes,
		&i.TimeoutSeconds,
		&i.NetworkConfig,
		&i.SecretBindings,
		&i.FcBuildSha,
		&i.GuestKernel,
		&i.SnapshotFormat,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.DeletedAt,
	)
	return i, err
}

const renameSandboxSnapshot = `-- name: RenameSandboxSnapshot :one
UPDATE sandbox_snapshot SET name = $3
WHERE id = $1 AND team_id = $2 AND deleted_at IS NULL
RETURNING id, team_id, sandbox_id, template_id, kind, status, name, idempotency_key, host_id, vcpu_count, memory_mib, disk_mib, base_path, base_mem_path, snapshot_path, mem_path, overlay_path, size_bytes, timeout_seconds, network_config, secret_bindings, fc_build_sha, guest_kernel, snapshot_format, created_at, ready_at, deleted_at
`

type RenameSandboxSnapshotParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
	Name   *string   `json:"name"`
}

func (q *Queries) RenameSandboxSnapshot(ctx context.Context, arg RenameSandboxSnapshotParams) (SandboxSnapshot, error) {
	row := q.db.QueryRow(ctx, renameSandboxSnapshot, arg.ID, arg.TeamID, arg.Name)
	var i SandboxSnapshot
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SandboxID,
		&i.TemplateID,
		&i.Kind,
		&i.Status,
		&i.Name,
		&i.IdempotencyKey,
		&i.HostID,
		&i.VcpuCount,
		&i.MemoryMib,
		&i.DiskMib,
		&i.BasePath,
		&i.BaseMemPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.OverlayPath,
		&i.SizeBytes,
		&i.TimeoutSeconds,
		&i.NetworkConfig,
		&i.SecretBindings,
		&i.FcBuildSha,
		&i.GuestKernel,
		&i.SnapshotFormat,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.DeletedAt,
	)
	return i, err
}
