// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sandboxes.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateSandbox = `-- name: ActivateSandbox :exec
UPDATE sandbox
SET status = 'active',
    vcpu_count = $2,
    memory_mib = $3,
    ip_address = $4,
    updated_at = now()
WHERE id = $1 AND team_id = $5 AND destroyed_at IS NULL
`

type ActivateSandboxParams struct {
	ID        uuid.UUID   `json:"id"`
	VcpuCount int32       `json:"vcpu_count"`
	MemoryMib int32       `json:"memory_mib"`
	IpAddress *netip.Addr `json:"ip_address"`
	TeamID    uuid.UUID   `json:"team_id"`
}

func (q *Queries) ActivateSandbox(ctx context.Context, arg ActivateSandboxParams) error {
	_, err := q.db.Exec(ctx, activateSandbox,
		arg.ID,
		arg.VcpuCount,
		arg.MemoryMib,
		arg.IpAddress,
		arg.TeamID,
	)
	return err
}

const claimExpiredSandboxes = `-- name: ClaimExpiredSandboxes :many
WITH expired AS (
  SELECT id, team_id, name, snapshot_id, host_id
  FROM sandbox
  WHERE destroyed_at IS NULL
    AND timeout_seconds IS NOT NULL
    AND status = 'active'
    AND created_at + (timeout_seconds || ' seconds')::interval < now()
    AND created_at < now() - interval '60 seconds'
  ORDER BY created_at ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE sandbox
SET status = 'pausing', updated_at = now()
FROM expired
WHERE sandbox.id = expired.id
RETURNING expired.id, expired.team_id, expired.name, expired.snapshot_id, expired.host_id
`

type ClaimExpiredSandboxesRow struct {
	ID         uuid.UUID   `json:"id"`
	TeamID     uuid.UUID   `json:"team_id"`
	Name       string      `json:"name"`
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	HostID     string      `json:"host_id"`
}

// Atomically claims active sandboxes whose hard timeout has elapsed and marks
// them as 'pausing'. FOR UPDATE SKIP LOCKED lets concurrent reaper replicas
// skip rows already being processed, so multi-replica Cloud Run deployments
// do not double-process the same sandbox.
//
// Only 'active' sandboxes are claimed — idle sandboxes are already stopped,
// and transient states (starting, pausing) are skipped to avoid racing with
// in-progress operations. The 60-second grace window prevents reaping a sandbox
// that was just created with a very short timeout before it finishes starting up.
func (q *Queries) ClaimExpiredSandboxes(ctx context.Context, limit int32) ([]ClaimExpiredSandboxesRow, error) {
	rows, err := q.db.Query(ctx, claimExpiredSandboxes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimExpiredSandboxesRow{}
	for rows.Next() {
		var i ClaimExpiredSandboxesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.SnapshotID,
			&i.HostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSandbox = `-- name: CreateSandbox :one
INSERT INTO sandbox (team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, timeout_seconds, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, last_activity_at, created_at, updated_at, destroyed_at, network_config, timeout_seconds, metadata
`

type CreateSandboxParams struct {
	TeamID         uuid.UUID     `json:"team_id"`
	Name           string        `json:"name"`
	Status         SandboxStatus `json:"status"`
	VcpuCount      int32         `json:"vcpu_count"`
	MemoryMib      int32         `json:"memory_mib"`
	HostID         string        `json:"host_id"`
	IpAddress      *netip.Addr   `json:"ip_address"`
	Pid            *int32        `json:"pid"`
	SnapshotID     pgtype.UUID   `json:"snapshot_id"`
	TimeoutSeconds *int32        `json:"timeout_seconds"`
	Metadata       []byte        `json:"metadata"`
}

func (q *Queries) CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, createSandbox,
		arg.TeamID,
		arg.Name,
		arg.Status,
		arg.VcpuCount,
		arg.MemoryMib,
		arg.HostID,
		arg.IpAddress,
		arg.Pid,
		arg.SnapshotID,
		arg.TimeoutSeconds,
		arg.Metadata,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.VcpuCount,
		&i.MemoryMib,
		&i.HostID,
		&i.IpAddress,
		&i.Pid,
		&i.SnapshotID,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestroyedAt,
		&i.NetworkConfig,
		&i.TimeoutSeconds,
		&i.Metadata,
	)
	return i, err
}

const destroySandbox = `-- name: DestroySandbox :exec
UPDATE sandbox
SET destroyed_at = now(), status = 'deleted', updated_at = now()
WHERE id = $1 AND team_id = $2 AND destroyed_at IS NULL
`

type DestroySandboxParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) DestroySandbox(ctx context.Context, arg DestroySandboxParams) error {
	_, err := q.db.Exec(ctx, destroySandbox, arg.ID, arg.TeamID)
	return err
}

const getSandbox = `-- name: GetSandbox :one
SELECT id, team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, last_activity_at, created_at, updated_at, destroyed_at, network_config, timeout_seconds, metadata FROM sandbox
WHERE id = $1 AND team_id = $2 AND destroyed_at IS NULL
`

type GetSandboxParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) GetSandbox(ctx context.Context, arg GetSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandbox, arg.ID, arg.TeamID)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.VcpuCount,
		&i.MemoryMib,
		&i.HostID,
		&i.IpAddress,
		&i.Pid,
		&i.SnapshotID,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestroyedAt,
		&i.NetworkConfig,
		&i.TimeoutSeconds,
		&i.Metadata,
	)
	return i, err
}

const getSandboxNetworkConfig = `-- name: GetSandboxNetworkConfig :one
SELECT network_config FROM sandbox
WHERE id = $1 AND team_id = $2 AND destroyed_at IS NULL
`

type GetSandboxNetworkConfigParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) GetSandboxNetworkConfig(ctx context.Context, arg GetSandboxNetworkConfigParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSandboxNetworkConfig, arg.ID, arg.TeamID)
	var network_config []byte
	err := row.Scan(&network_config)
	return network_config, err
}

const listIdleSandboxes = `-- name: ListIdleSandboxes :many
SELECT id, team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, last_activity_at, created_at, updated_at, destroyed_at, network_config, timeout_seconds, metadata FROM sandbox
WHERE status = 'idle'
  AND destroyed_at IS NULL
  AND last_activity_at < $1
ORDER BY last_activity_at ASC
`

func (q *Queries) ListIdleSandboxes(ctx context.Context, lastActivityAt time.Time) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listIdleSandboxes, lastActivityAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Status,
			&i.VcpuCount,
			&i.MemoryMib,
			&i.HostID,
			&i.IpAddress,
			&i.Pid,
			&i.SnapshotID,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestroyedAt,
			&i.NetworkConfig,
			&i.TimeoutSeconds,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesByTeam = `-- name: ListSandboxesByTeam :many
SELECT id, team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, last_activity_at, created_at, updated_at, destroyed_at, network_config, timeout_seconds, metadata FROM sandbox
WHERE team_id = $1 AND destroyed_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSandboxesByTeam(ctx context.Context, teamID uuid.UUID) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Status,
			&i.VcpuCount,
			&i.MemoryMib,
			&i.HostID,
			&i.IpAddress,
			&i.Pid,
			&i.SnapshotID,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestroyedAt,
			&i.NetworkConfig,
			&i.TimeoutSeconds,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesByTeamWithFilter = `-- name: ListSandboxesByTeamWithFilter :many
SELECT id, team_id, name, status, vcpu_count, memory_mib, host_id, ip_address, pid, snapshot_id, last_activity_at, created_at, updated_at, destroyed_at, network_config, timeout_seconds, metadata FROM sandbox
WHERE team_id = $1
  AND destroyed_at IS NULL
  AND metadata @> $2
ORDER BY created_at DESC
`

type ListSandboxesByTeamWithFilterParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	Metadata []byte    `json:"metadata"`
}

// Same as ListSandboxesByTeam but additionally filters rows whose metadata
// contains every key/value pair in $2 (jsonb @> containment). Pass an empty
// object '{}'::jsonb to match everything — but prefer ListSandboxesByTeam
// in that case so we don't pay the (still tiny) cost of the @> evaluation.
func (q *Queries) ListSandboxesByTeamWithFilter(ctx context.Context, arg ListSandboxesByTeamWithFilterParams) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByTeamWithFilter, arg.TeamID, arg.Metadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Status,
			&i.VcpuCount,
			&i.MemoryMib,
			&i.HostID,
			&i.IpAddress,
			&i.Pid,
			&i.SnapshotID,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestroyedAt,
			&i.NetworkConfig,
			&i.TimeoutSeconds,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sandboxExists = `-- name: SandboxExists :one
SELECT EXISTS(SELECT 1 FROM sandbox WHERE id = $1 AND team_id = $2 AND destroyed_at IS NULL)
`

type SandboxExistsParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) SandboxExists(ctx context.Context, arg SandboxExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, sandboxExists, arg.ID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setSandboxSnapshot = `-- name: SetSandboxSnapshot :exec
UPDATE sandbox
SET snapshot_id = $2, updated_at = now()
WHERE id = $1 AND team_id = $3 AND destroyed_at IS NULL
`

type SetSandboxSnapshotParams struct {
	ID         uuid.UUID   `json:"id"`
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	TeamID     uuid.UUID   `json:"team_id"`
}

func (q *Queries) SetSandboxSnapshot(ctx context.Context, arg SetSandboxSnapshotParams) error {
	_, err := q.db.Exec(ctx, setSandboxSnapshot, arg.ID, arg.SnapshotID, arg.TeamID)
	return err
}

const updateSandboxHost = `-- name: UpdateSandboxHost :exec
UPDATE sandbox
SET host_id = $2, ip_address = $3, pid = $4, updated_at = now()
WHERE id = $1 AND team_id = $5 AND destroyed_at IS NULL
`

type UpdateSandboxHostParams struct {
	ID        uuid.UUID   `json:"id"`
	HostID    string      `json:"host_id"`
	IpAddress *netip.Addr `json:"ip_address"`
	Pid       *int32      `json:"pid"`
	TeamID    uuid.UUID   `json:"team_id"`
}

func (q *Queries) UpdateSandboxHost(ctx context.Context, arg UpdateSandboxHostParams) error {
	_, err := q.db.Exec(ctx, updateSandboxHost,
		arg.ID,
		arg.HostID,
		arg.IpAddress,
		arg.Pid,
		arg.TeamID,
	)
	return err
}

const updateSandboxLastActivity = `-- name: UpdateSandboxLastActivity :exec
UPDATE sandbox
SET last_activity_at = now(), updated_at = now()
WHERE id = $1 AND team_id = $2 AND destroyed_at IS NULL
`

type UpdateSandboxLastActivityParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) UpdateSandboxLastActivity(ctx context.Context, arg UpdateSandboxLastActivityParams) error {
	_, err := q.db.Exec(ctx, updateSandboxLastActivity, arg.ID, arg.TeamID)
	return err
}

const updateSandboxMetadata = `-- name: UpdateSandboxMetadata :exec
UPDATE sandbox
SET metadata = $2, updated_at = now()
WHERE id = $1 AND team_id = $3 AND destroyed_at IS NULL
`

type UpdateSandboxMetadataParams struct {
	ID       uuid.UUID `json:"id"`
	Metadata []byte    `json:"metadata"`
	TeamID   uuid.UUID `json:"team_id"`
}

func (q *Queries) UpdateSandboxMetadata(ctx context.Context, arg UpdateSandboxMetadataParams) error {
	_, err := q.db.Exec(ctx, updateSandboxMetadata, arg.ID, arg.Metadata, arg.TeamID)
	return err
}

const updateSandboxNetworkConfig = `-- name: UpdateSandboxNetworkConfig :exec
UPDATE sandbox
SET network_config = $2, updated_at = now()
WHERE id = $1 AND team_id = $3 AND destroyed_at IS NULL
`

type UpdateSandboxNetworkConfigParams struct {
	ID            uuid.UUID `json:"id"`
	NetworkConfig []byte    `json:"network_config"`
	TeamID        uuid.UUID `json:"team_id"`
}

func (q *Queries) UpdateSandboxNetworkConfig(ctx context.Context, arg UpdateSandboxNetworkConfigParams) error {
	_, err := q.db.Exec(ctx, updateSandboxNetworkConfig, arg.ID, arg.NetworkConfig, arg.TeamID)
	return err
}

const updateSandboxStatus = `-- name: UpdateSandboxStatus :exec
UPDATE sandbox
SET status = $2, updated_at = now()
WHERE id = $1 AND team_id = $3 AND destroyed_at IS NULL
`

type UpdateSandboxStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status SandboxStatus `json:"status"`
	TeamID uuid.UUID     `json:"team_id"`
}

func (q *Queries) UpdateSandboxStatus(ctx context.Context, arg UpdateSandboxStatusParams) error {
	_, err := q.db.Exec(ctx, updateSandboxStatus, arg.ID, arg.Status, arg.TeamID)
	return err
}
