// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO team (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at, build_concurrency, max_template_vcpu, max_template_memory_mib, max_template_disk_mib, max_templates, max_sandboxes
`

func (q *Queries) CreateTeam(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuildConcurrency,
		&i.MaxTemplateVcpu,
		&i.MaxTemplateMemoryMib,
		&i.MaxTemplateDiskMib,
		&i.MaxTemplates,
		&i.MaxSandboxes,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM team
WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, created_at, updated_at, build_concurrency, max_template_vcpu, max_template_memory_mib, max_template_disk_mib, max_templates, max_sandboxes FROM team
WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuildConcurrency,
		&i.MaxTemplateVcpu,
		&i.MaxTemplateMemoryMib,
		&i.MaxTemplateDiskMib,
		&i.MaxTemplates,
		&i.MaxSandboxes,
	)
	return i, err
}

const getTeamBuildConcurrency = `-- name: GetTeamBuildConcurrency :one
SELECT build_concurrency FROM team WHERE id = $1
`

// Per-team max concurrent template builds. Used by the build supervisor.
func (q *Queries) GetTeamBuildConcurrency(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getTeamBuildConcurrency, id)
	var build_concurrency int32
	err := row.Scan(&build_concurrency)
	return build_concurrency, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, name, created_at, updated_at, build_concurrency, max_template_vcpu, max_template_memory_mib, max_template_disk_mib, max_templates, max_sandboxes FROM team
WHERE name = $1
`

func (q *Queries) GetTeamByName(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuildConcurrency,
		&i.MaxTemplateVcpu,
		&i.MaxTemplateMemoryMib,
		&i.MaxTemplateDiskMib,
		&i.MaxTemplates,
		&i.MaxSandboxes,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, created_at, updated_at, build_concurrency, max_template_vcpu, max_template_memory_mib, max_template_disk_mib, max_templates, max_sandboxes FROM team
ORDER BY created_at DESC
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BuildConcurrency,
			&i.MaxTemplateVcpu,
			&i.MaxTemplateMemoryMib,
			&i.MaxTemplateDiskMib,
			&i.MaxTemplates,
			&i.MaxSandboxes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeamName = `-- name: UpdateTeamName :one
UPDATE team
SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, created_at, updated_at, build_concurrency, max_template_vcpu, max_template_memory_mib, max_template_disk_mib, max_templates, max_sandboxes
`

type UpdateTeamNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeamName, arg.ID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuildConcurrency,
		&i.MaxTemplateVcpu,
		&i.MaxTemplateMemoryMib,
		&i.MaxTemplateDiskMib,
		&i.MaxTemplates,
		&i.MaxSandboxes,
	)
	return i, err
}
