// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceBuildStatus = `-- name: AdvanceBuildStatus :exec
UPDATE template_build
SET status = $2, updated_at = now()
WHERE id = $1 AND status IN ('pending', 'building', 'snapshotting')
`

type AdvanceBuildStatusParams struct {
	ID     uuid.UUID           `json:"id"`
	Status TemplateBuildStatus `json:"status"`
}

// Used by the supervisor to walk a build through transient statuses
// (building → snapshotting). Terminal transitions go through FinalizeBuild
// or FailBuild instead.
func (q *Queries) AdvanceBuildStatus(ctx context.Context, arg AdvanceBuildStatusParams) error {
	_, err := q.db.Exec(ctx, advanceBuildStatus, arg.ID, arg.Status)
	return err
}

const attachBuildVM = `-- name: AttachBuildVM :exec
UPDATE template_build
SET vmd_build_vm_id = $2, updated_at = now()
WHERE id = $1
`

type AttachBuildVMParams struct {
	ID           uuid.UUID `json:"id"`
	VmdBuildVmID *string   `json:"vmd_build_vm_id"`
}

// Record the vmd-side build VM id once vmd.BuildTemplate has returned it.
// Lets the supervisor (and cancel path) call vmd.GetBuildStatus / CancelBuild
// by VM id rather than re-derive it.
func (q *Queries) AttachBuildVM(ctx context.Context, arg AttachBuildVMParams) error {
	_, err := q.db.Exec(ctx, attachBuildVM, arg.ID, arg.VmdBuildVmID)
	return err
}

const cancelBuild = `-- name: CancelBuild :execrows
UPDATE template_build
SET status = 'cancelled',
    finalized_at = now(),
    updated_at = now(),
    error_message = 'cancelled by user'
WHERE id = $1
  AND team_id = $2
  AND status IN ('pending', 'building', 'snapshotting')
`

type CancelBuildParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

// User-initiated cancellation of a build. Only succeeds while the build is
// still in a non-terminal state. Caller is responsible for calling
// vmd.CancelBuild before this; this just records the terminal status.
func (q *Queries) CancelBuild(ctx context.Context, arg CancelBuildParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelBuild, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimPendingBuilds = `-- name: ClaimPendingBuilds :many
WITH claimed AS (
  SELECT id FROM template_build
  WHERE status = 'pending'
  ORDER BY created_at ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE template_build
SET status = 'building',
    started_at = now(),
    updated_at = now(),
    vmd_host_id = $2
FROM claimed
WHERE template_build.id = claimed.id
RETURNING template_build.id, template_build.template_id, template_build.team_id, template_build.status, template_build.build_spec_hash, template_build.vmd_host_id, template_build.vmd_build_vm_id, template_build.error_message, template_build.started_at, template_build.finalized_at, template_build.created_at, template_build.updated_at
`

type ClaimPendingBuildsParams struct {
	Limit     int32   `json:"limit"`
	VmdHostID *string `json:"vmd_host_id"`
}

// Atomically claim pending builds for dispatch. FOR UPDATE SKIP LOCKED makes
// this safe with multiple control plane replicas — concurrent supervisors
// skip rows another replica already has. Limit caps how many we work per tick.
func (q *Queries) ClaimPendingBuilds(ctx context.Context, arg ClaimPendingBuildsParams) ([]TemplateBuild, error) {
	rows, err := q.db.Query(ctx, claimPendingBuilds, arg.Limit, arg.VmdHostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateBuild{}
	for rows.Next() {
		var i TemplateBuild
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.TeamID,
			&i.Status,
			&i.BuildSpecHash,
			&i.VmdHostID,
			&i.VmdBuildVmID,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countInFlightBuildsForTeam = `-- name: CountInFlightBuildsForTeam :one
SELECT COUNT(*) FROM template_build
WHERE team_id = $1 AND status IN ('pending', 'building', 'snapshotting')
`

// Used by the build supervisor to enforce team.build_concurrency before
// dispatching a pending build. Counts builds that are not in terminal state.
func (q *Queries) CountInFlightBuildsForTeam(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInFlightBuildsForTeam, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveSandboxesForTemplate = `-- name: CountLiveSandboxesForTemplate :one
SELECT COUNT(*) FROM sandbox
WHERE template_id = $1 AND destroyed_at IS NULL
`

// Used before SoftDeleteTemplate to enforce 409-on-in-use. Counts every
// sandbox referencing this template that has not been hard-destroyed —
// including paused and failed sandboxes, not just 'active'. A paused
// sandbox still has a snapshot bundle dependent on the template's
// rootfs/snapshot files, so deletion would orphan it. The user must
// destroy these sandboxes (DELETE /sandboxes/:id) before the template
// can be removed.
func (q *Queries) CountLiveSandboxesForTemplate(ctx context.Context, templateID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveSandboxesForTemplate, templateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO template (team_id, alias, build_spec, vcpu, memory_mib, disk_mib)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, team_id, alias, status, build_spec, vcpu, memory_mib, disk_mib, rootfs_path, snapshot_path, mem_path, size_bytes, error_message, created_at, updated_at, built_at, deleted_at
`

type CreateTemplateParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	Alias     string    `json:"alias"`
	BuildSpec []byte    `json:"build_spec"`
	Vcpu      int32     `json:"vcpu"`
	MemoryMib int32     `json:"memory_mib"`
	DiskMib   int32     `json:"disk_mib"`
}

// Insert a new template row in 'pending' status (no build attached). Kept
// for ops-side seeding that wants to stage rows without triggering builds;
// the public API uses CreateTemplateWithBuild to auto-enqueue the first
// build in a single transaction.
func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.TeamID,
		arg.Alias,
		arg.BuildSpec,
		arg.Vcpu,
		arg.MemoryMib,
		arg.DiskMib,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Alias,
		&i.Status,
		&i.BuildSpec,
		&i.Vcpu,
		&i.MemoryMib,
		&i.DiskMib,
		&i.RootfsPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuiltAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTemplateBuild = `-- name: CreateTemplateBuild :one
INSERT INTO template_build (template_id, team_id, build_spec_hash)
VALUES ($1, $2, $3)
RETURNING id, template_id, team_id, status, build_spec_hash, vmd_host_id, vmd_build_vm_id, error_message, started_at, finalized_at, created_at, updated_at
`

type CreateTemplateBuildParams struct {
	TemplateID    uuid.UUID `json:"template_id"`
	TeamID        uuid.UUID `json:"team_id"`
	BuildSpecHash string    `json:"build_spec_hash"`
}

// Insert a new build row. Will fail with a unique-violation if there is
// already an in-flight build for this (template_id, build_spec_hash) — the
// caller (handler) catches that and returns the existing build id instead,
// giving idempotent submits.
func (q *Queries) CreateTemplateBuild(ctx context.Context, arg CreateTemplateBuildParams) (TemplateBuild, error) {
	row := q.db.QueryRow(ctx, createTemplateBuild, arg.TemplateID, arg.TeamID, arg.BuildSpecHash)
	var i TemplateBuild
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.TeamID,
		&i.Status,
		&i.BuildSpecHash,
		&i.VmdHostID,
		&i.VmdBuildVmID,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplateWithBuild = `-- name: CreateTemplateWithBuild :one
WITH new_template AS (
  INSERT INTO template (team_id, alias, build_spec, vcpu, memory_mib, disk_mib, status)
  VALUES ($1, $2, $3, $4, $5, $6, 'building')
  RETURNING id, team_id, alias, status, build_spec, vcpu, memory_mib, disk_mib,
            rootfs_path, snapshot_path, mem_path, size_bytes, error_message,
            created_at, updated_at, built_at, deleted_at
),
new_build AS (
  INSERT INTO template_build (template_id, team_id, build_spec_hash)
  SELECT id, team_id, $7 FROM new_template
  RETURNING id AS build_id
)
SELECT new_template.id, new_template.team_id, new_template.alias, new_template.status, new_template.build_spec, new_template.vcpu, new_template.memory_mib, new_template.disk_mib, new_template.rootfs_path, new_template.snapshot_path, new_template.mem_path, new_template.size_bytes, new_template.error_message, new_template.created_at, new_template.updated_at, new_template.built_at, new_template.deleted_at, new_build.build_id::uuid AS build_id
FROM new_template, new_build
`

type CreateTemplateWithBuildParams struct {
	TeamID        uuid.UUID `json:"team_id"`
	Alias         string    `json:"alias"`
	BuildSpec     []byte    `json:"build_spec"`
	Vcpu          int32     `json:"vcpu"`
	MemoryMib     int32     `json:"memory_mib"`
	DiskMib       int32     `json:"disk_mib"`
	BuildSpecHash string    `json:"build_spec_hash"`
}

type CreateTemplateWithBuildRow struct {
	ID           uuid.UUID          `json:"id"`
	TeamID       uuid.UUID          `json:"team_id"`
	Alias        string             `json:"alias"`
	Status       TemplateStatus     `json:"status"`
	BuildSpec    []byte             `json:"build_spec"`
	Vcpu         int32              `json:"vcpu"`
	MemoryMib    int32              `json:"memory_mib"`
	DiskMib      int32              `json:"disk_mib"`
	RootfsPath   *string            `json:"rootfs_path"`
	SnapshotPath *string            `json:"snapshot_path"`
	MemPath      *string            `json:"mem_path"`
	SizeBytes    *int64             `json:"size_bytes"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	BuiltAt      pgtype.Timestamptz `json:"built_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	BuildID      uuid.UUID          `json:"build_id"`
}

// Atomically create a template and its first build in one round-trip.
// Used by POST /templates so users don't have to make two calls. Template
// starts at 'building' (not 'pending') because the build row is already
// queued at insert time; the supervisor picks it up within one tick.
//
// build_spec_hash is computed in Go before the call and passed in so the
// idempotency index on template_build catches duplicate submits. Returns
// the template row plus the build id so the handler can echo both.
func (q *Queries) CreateTemplateWithBuild(ctx context.Context, arg CreateTemplateWithBuildParams) (CreateTemplateWithBuildRow, error) {
	row := q.db.QueryRow(ctx, createTemplateWithBuild,
		arg.TeamID,
		arg.Alias,
		arg.BuildSpec,
		arg.Vcpu,
		arg.MemoryMib,
		arg.DiskMib,
		arg.BuildSpecHash,
	)
	var i CreateTemplateWithBuildRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Alias,
		&i.Status,
		&i.BuildSpec,
		&i.Vcpu,
		&i.MemoryMib,
		&i.DiskMib,
		&i.RootfsPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuiltAt,
		&i.DeletedAt,
		&i.BuildID,
	)
	return i, err
}

const failBuild = `-- name: FailBuild :one
WITH build_done AS (
  UPDATE template_build
  SET status = 'failed',
      finalized_at = now(),
      updated_at = now(),
      error_message = $2
  WHERE template_build.id = $1 AND status IN ('pending', 'building', 'snapshotting')
  RETURNING template_id
)
UPDATE template
SET status = 'failed',
    error_message = $2,
    updated_at = now()
FROM build_done
WHERE template.id = build_done.template_id
RETURNING template.id, template.team_id, template.alias, template.status, template.build_spec, template.vcpu, template.memory_mib, template.disk_mib, template.rootfs_path, template.snapshot_path, template.mem_path, template.size_bytes, template.error_message, template.created_at, template.updated_at, template.built_at, template.deleted_at
`

type FailBuildParams struct {
	ID           uuid.UUID `json:"id"`
	ErrorMessage *string   `json:"error_message"`
}

// Atomic terminal-failure transition. Same shape as FinalizeBuild; sets
// error_message on the template so users see a useful message.
func (q *Queries) FailBuild(ctx context.Context, arg FailBuildParams) (Template, error) {
	row := q.db.QueryRow(ctx, failBuild, arg.ID, arg.ErrorMessage)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Alias,
		&i.Status,
		&i.BuildSpec,
		&i.Vcpu,
		&i.MemoryMib,
		&i.DiskMib,
		&i.RootfsPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuiltAt,
		&i.DeletedAt,
	)
	return i, err
}

const finalizeBuild = `-- name: FinalizeBuild :one
WITH build_done AS (
  UPDATE template_build
  SET status = 'ready',
      finalized_at = now(),
      updated_at = now()
  WHERE template_build.id = $1 AND status IN ('building', 'snapshotting')
  RETURNING template_id
)
UPDATE template
SET status = 'ready',
    rootfs_path = $2,
    snapshot_path = $3,
    mem_path = $4,
    size_bytes = $5,
    built_at = now(),
    updated_at = now(),
    error_message = NULL
FROM build_done
WHERE template.id = build_done.template_id
RETURNING template.id, template.team_id, template.alias, template.status, template.build_spec, template.vcpu, template.memory_mib, template.disk_mib, template.rootfs_path, template.snapshot_path, template.mem_path, template.size_bytes, template.error_message, template.created_at, template.updated_at, template.built_at, template.deleted_at
`

type FinalizeBuildParams struct {
	ID           uuid.UUID `json:"id"`
	RootfsPath   *string   `json:"rootfs_path"`
	SnapshotPath *string   `json:"snapshot_path"`
	MemPath      *string   `json:"mem_path"`
	SizeBytes    *int64    `json:"size_bytes"`
}

// Atomically transition template_build → ready and template → ready with
// the snapshot paths populated. Mirrors the FinalizePause CTE pattern in
// sandboxes.sql: one roundtrip, no torn states. Returns the template row
// so the caller can log the outcome.
func (q *Queries) FinalizeBuild(ctx context.Context, arg FinalizeBuildParams) (Template, error) {
	row := q.db.QueryRow(ctx, finalizeBuild,
		arg.ID,
		arg.RootfsPath,
		arg.SnapshotPath,
		arg.MemPath,
		arg.SizeBytes,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Alias,
		&i.Status,
		&i.BuildSpec,
		&i.Vcpu,
		&i.MemoryMib,
		&i.DiskMib,
		&i.RootfsPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuiltAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExistingInflightBuild = `-- name: GetExistingInflightBuild :one
SELECT id, template_id, team_id, status, build_spec_hash, vmd_host_id, vmd_build_vm_id, error_message, started_at, finalized_at, created_at, updated_at FROM template_build
WHERE template_id = $1
  AND build_spec_hash = $2
  AND status IN ('pending', 'building', 'snapshotting')
`

type GetExistingInflightBuildParams struct {
	TemplateID    uuid.UUID `json:"template_id"`
	BuildSpecHash string    `json:"build_spec_hash"`
}

// Fetch the existing in-flight build for this (template_id, build_spec_hash),
// used after a unique-violation from CreateTemplateBuild to return the
// pre-existing build id to the caller.
func (q *Queries) GetExistingInflightBuild(ctx context.Context, arg GetExistingInflightBuildParams) (TemplateBuild, error) {
	row := q.db.QueryRow(ctx, getExistingInflightBuild, arg.TemplateID, arg.BuildSpecHash)
	var i TemplateBuild
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.TeamID,
		&i.Status,
		&i.BuildSpecHash,
		&i.VmdHostID,
		&i.VmdBuildVmID,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, team_id, alias, status, build_spec, vcpu, memory_mib, disk_mib, rootfs_path, snapshot_path, mem_path, size_bytes, error_message, created_at, updated_at, built_at, deleted_at FROM template
WHERE id = $1
  AND deleted_at IS NULL
  AND (team_id = $2 OR team_id = $3)
`

type GetTemplateParams struct {
	ID       uuid.UUID `json:"id"`
	TeamID   uuid.UUID `json:"team_id"`
	TeamID_2 uuid.UUID `json:"team_id_2"`
}

// Fetch a template visible to the caller: either owned by the caller's team
// or by the system team (system_team_id param — pass uuid.Nil to disable).
// Returns 0 rows if the template isn't visible, doesn't exist, or is deleted.
func (q *Queries) GetTemplate(ctx context.Context, arg GetTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, arg.ID, arg.TeamID, arg.TeamID_2)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Alias,
		&i.Status,
		&i.BuildSpec,
		&i.Vcpu,
		&i.MemoryMib,
		&i.DiskMib,
		&i.RootfsPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuiltAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTemplateBuild = `-- name: GetTemplateBuild :one
SELECT id, template_id, team_id, status, build_spec_hash, vmd_host_id, vmd_build_vm_id, error_message, started_at, finalized_at, created_at, updated_at FROM template_build
WHERE id = $1 AND team_id = $2
`

type GetTemplateBuildParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

// Fetch a build visible to the caller's team. Read-only path; team scope only.
func (q *Queries) GetTemplateBuild(ctx context.Context, arg GetTemplateBuildParams) (TemplateBuild, error) {
	row := q.db.QueryRow(ctx, getTemplateBuild, arg.ID, arg.TeamID)
	var i TemplateBuild
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.TeamID,
		&i.Status,
		&i.BuildSpecHash,
		&i.VmdHostID,
		&i.VmdBuildVmID,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByAlias = `-- name: GetTemplateByAlias :one
SELECT id, team_id, alias, status, build_spec, vcpu, memory_mib, disk_mib, rootfs_path, snapshot_path, mem_path, size_bytes, error_message, created_at, updated_at, built_at, deleted_at FROM template
WHERE alias = $1
  AND deleted_at IS NULL
  AND (team_id = $2 OR team_id = $3)
ORDER BY (team_id = $2) DESC
LIMIT 1
`

type GetTemplateByAliasParams struct {
	Alias    string    `json:"alias"`
	TeamID   uuid.UUID `json:"team_id"`
	TeamID_2 uuid.UUID `json:"team_id_2"`
}

// Resolve alias to a template visible to the caller. Aliases are unique per
// team, so the same alias can exist in both the caller's team and the system
// team — prefer the caller's own (ORDER BY) so overrides work naturally.
func (q *Queries) GetTemplateByAlias(ctx context.Context, arg GetTemplateByAliasParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByAlias, arg.Alias, arg.TeamID, arg.TeamID_2)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Alias,
		&i.Status,
		&i.BuildSpec,
		&i.Vcpu,
		&i.MemoryMib,
		&i.DiskMib,
		&i.RootfsPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuiltAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTemplateForOwner = `-- name: GetTemplateForOwner :one
SELECT id, team_id, alias, status, build_spec, vcpu, memory_mib, disk_mib, rootfs_path, snapshot_path, mem_path, size_bytes, error_message, created_at, updated_at, built_at, deleted_at FROM template
WHERE id = $1 AND team_id = $2 AND deleted_at IS NULL
`

type GetTemplateForOwnerParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

// Fetch a template owned by this team. Used for write paths (build, delete)
// where system-team visibility is irrelevant — only the owner can mutate.
func (q *Queries) GetTemplateForOwner(ctx context.Context, arg GetTemplateForOwnerParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateForOwner, arg.ID, arg.TeamID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Alias,
		&i.Status,
		&i.BuildSpec,
		&i.Vcpu,
		&i.MemoryMib,
		&i.DiskMib,
		&i.RootfsPath,
		&i.SnapshotPath,
		&i.MemPath,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuiltAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveBuilds = `-- name: ListActiveBuilds :many
SELECT id, template_id, team_id, status, build_spec_hash, vmd_host_id, vmd_build_vm_id, error_message, started_at, finalized_at, created_at, updated_at FROM template_build
WHERE status IN ('building', 'snapshotting')
ORDER BY started_at ASC NULLS LAST
`

// Read-only: builds the supervisor is currently watching. Used per tick to
// poll vmd for status. No row-level lock — these are already past 'pending'.
func (q *Queries) ListActiveBuilds(ctx context.Context) ([]TemplateBuild, error) {
	rows, err := q.db.Query(ctx, listActiveBuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateBuild{}
	for rows.Next() {
		var i TemplateBuild
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.TeamID,
			&i.Status,
			&i.BuildSpecHash,
			&i.VmdHostID,
			&i.VmdBuildVmID,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildsForTemplate = `-- name: ListBuildsForTemplate :many
SELECT id, template_id, team_id, status, build_spec_hash, vmd_host_id, vmd_build_vm_id, error_message, started_at, finalized_at, created_at, updated_at FROM template_build
WHERE template_id = $1 AND team_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListBuildsForTemplateParams struct {
	TemplateID uuid.UUID `json:"template_id"`
	TeamID     uuid.UUID `json:"team_id"`
	Limit      int32     `json:"limit"`
}

// Recent builds for a template. Used by the SDK to inspect build history.
func (q *Queries) ListBuildsForTemplate(ctx context.Context, arg ListBuildsForTemplateParams) ([]TemplateBuild, error) {
	rows, err := q.db.Query(ctx, listBuildsForTemplate, arg.TemplateID, arg.TeamID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateBuild{}
	for rows.Next() {
		var i TemplateBuild
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.TeamID,
			&i.Status,
			&i.BuildSpecHash,
			&i.VmdHostID,
			&i.VmdBuildVmID,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingBuildsOrdered = `-- name: ListPendingBuildsOrdered :many
SELECT id, template_id, team_id, status, build_spec_hash, vmd_host_id, vmd_build_vm_id, error_message, started_at, finalized_at, created_at, updated_at FROM template_build
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

// Read-only scan of pending builds in FIFO order. Used by the supervisor's
// per-tick dispatch loop to evaluate admission (host capacity + per-team
// concurrency) before transitioning any rows. Kept separate from
// ClaimPendingBuilds so the supervisor can skip individual rows (e.g. a
// team already at its concurrency limit) without locking them out of a
// later tick.
func (q *Queries) ListPendingBuildsOrdered(ctx context.Context, limit int32) ([]TemplateBuild, error) {
	rows, err := q.db.Query(ctx, listPendingBuildsOrdered, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateBuild{}
	for rows.Next() {
		var i TemplateBuild
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.TeamID,
			&i.Status,
			&i.BuildSpecHash,
			&i.VmdHostID,
			&i.VmdBuildVmID,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesForTeam = `-- name: ListTemplatesForTeam :many
SELECT id, team_id, alias, status, build_spec, vcpu, memory_mib, disk_mib, rootfs_path, snapshot_path, mem_path, size_bytes, error_message, created_at, updated_at, built_at, deleted_at FROM template
WHERE deleted_at IS NULL
  AND (team_id = $1 OR team_id = $2)
ORDER BY created_at DESC
`

type ListTemplatesForTeamParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	TeamID_2 uuid.UUID `json:"team_id_2"`
}

// Return the caller's team's templates plus all system-team templates
// (curated base set visible to everyone). Ordered by created_at desc.
func (q *Queries) ListTemplatesForTeam(ctx context.Context, arg ListTemplatesForTeamParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesForTeam, arg.TeamID, arg.TeamID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Alias,
			&i.Status,
			&i.BuildSpec,
			&i.Vcpu,
			&i.MemoryMib,
			&i.DiskMib,
			&i.RootfsPath,
			&i.SnapshotPath,
			&i.MemPath,
			&i.SizeBytes,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BuiltAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesForTeamFiltered = `-- name: ListTemplatesForTeamFiltered :many
SELECT id, team_id, alias, status, build_spec, vcpu, memory_mib, disk_mib, rootfs_path, snapshot_path, mem_path, size_bytes, error_message, created_at, updated_at, built_at, deleted_at FROM template
WHERE deleted_at IS NULL
  AND (team_id = $1 OR team_id = $2)
  AND ($3::text IS NULL
       OR alias LIKE $3 || '%')
ORDER BY created_at DESC
`

type ListTemplatesForTeamFilteredParams struct {
	TeamID      uuid.UUID `json:"team_id"`
	TeamID_2    uuid.UUID `json:"team_id_2"`
	AliasPrefix *string   `json:"alias_prefix"`
}

// Same as ListTemplatesForTeam with an optional alias prefix filter. Pass
// NULL to get the unfiltered list (but prefer the unfiltered query then).
func (q *Queries) ListTemplatesForTeamFiltered(ctx context.Context, arg ListTemplatesForTeamFilteredParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesForTeamFiltered, arg.TeamID, arg.TeamID_2, arg.AliasPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Alias,
			&i.Status,
			&i.BuildSpec,
			&i.Vcpu,
			&i.MemoryMib,
			&i.DiskMib,
			&i.RootfsPath,
			&i.SnapshotPath,
			&i.MemPath,
			&i.SizeBytes,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BuiltAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapStaleBuilds = `-- name: ReapStaleBuilds :many
WITH stale AS (
  SELECT id, vmd_host_id, vmd_build_vm_id FROM template_build
  WHERE
    (status = 'pending' AND created_at < now() - ($2::int || ' seconds')::interval)
    OR
    (status IN ('building', 'snapshotting') AND COALESCE(started_at, created_at) < now() - ($3::int || ' seconds')::interval)
  ORDER BY created_at ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE template_build
SET status = 'failed',
    finalized_at = now(),
    updated_at = now(),
    error_message = 'build timed out'
FROM stale
WHERE template_build.id = stale.id
RETURNING template_build.id, stale.vmd_host_id, stale.vmd_build_vm_id
`

type ReapStaleBuildsParams struct {
	Limit                 int32 `json:"limit"`
	PendingTimeoutSeconds int32 `json:"pending_timeout_seconds"`
	BuildTimeoutSeconds   int32 `json:"build_timeout_seconds"`
}

type ReapStaleBuildsRow struct {
	ID           uuid.UUID `json:"id"`
	VmdHostID    *string   `json:"vmd_host_id"`
	VmdBuildVmID *string   `json:"vmd_build_vm_id"`
}

// Mark builds failed if they have stayed in pending past pending_timeout, or
// in building/snapshotting past build_timeout. Returns affected rows so the
// caller can call vmd.CancelBuild for orphan VM cleanup. Same idempotent
// pattern as ClaimExpiredSandboxes.
func (q *Queries) ReapStaleBuilds(ctx context.Context, arg ReapStaleBuildsParams) ([]ReapStaleBuildsRow, error) {
	rows, err := q.db.Query(ctx, reapStaleBuilds, arg.Limit, arg.PendingTimeoutSeconds, arg.BuildTimeoutSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReapStaleBuildsRow{}
	for rows.Next() {
		var i ReapStaleBuildsRow
		if err := rows.Scan(&i.ID, &i.VmdHostID, &i.VmdBuildVmID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTemplate = `-- name: SoftDeleteTemplate :execrows
UPDATE template
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND team_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTemplateParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

// Soft-delete a template owned by this team. Returns row count so the caller
// can distinguish "not found / not yours" (0) from success (1). Does NOT
// check for active sandboxes referencing this template — that check is done
// in Go before this call (returns 409 to the user).
func (q *Queries) SoftDeleteTemplate(ctx context.Context, arg SoftDeleteTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTemplate, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryDispatchBuild = `-- name: TryDispatchBuild :execrows
UPDATE template_build
SET status = 'building',
    started_at = now(),
    updated_at = now(),
    vmd_host_id = $2
WHERE id = $1 AND status = 'pending'
`

type TryDispatchBuildParams struct {
	ID        uuid.UUID `json:"id"`
	VmdHostID *string   `json:"vmd_host_id"`
}

// Atomic status transition from 'pending' to 'building', stamping the host
// and start timestamp. Returns rows affected — 1 if we successfully claimed
// the row, 0 if another supervisor tick (or another replica) already took
// it. Callers on the 0 path skip; callers on the 1 path dispatch to vmd.
func (q *Queries) TryDispatchBuild(ctx context.Context, arg TryDispatchBuildParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryDispatchBuild, arg.ID, arg.VmdHostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
