// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vms.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVM = `-- name: CreateVM :one
INSERT INTO vms (name, status, vcpu_count, mem_size_mib, ip_address, host_id, parent_vm_id, forked_from_checkpoint_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, status, vcpu_count, mem_size_mib, ip_address, host_id, parent_vm_id, forked_from_checkpoint_id, created_at, updated_at, deleted_at, metadata, snapshot_path, mem_file_path, disk_size_mib
`

type CreateVMParams struct {
	Name                   string      `json:"name"`
	Status                 VmStatus    `json:"status"`
	VcpuCount              int32       `json:"vcpu_count"`
	MemSizeMib             int32       `json:"mem_size_mib"`
	IpAddress              *netip.Addr `json:"ip_address"`
	HostID                 *string     `json:"host_id"`
	ParentVmID             pgtype.UUID `json:"parent_vm_id"`
	ForkedFromCheckpointID pgtype.UUID `json:"forked_from_checkpoint_id"`
	Metadata               []byte      `json:"metadata"`
}

func (q *Queries) CreateVM(ctx context.Context, arg CreateVMParams) (Vm, error) {
	row := q.db.QueryRow(ctx, createVM,
		arg.Name,
		arg.Status,
		arg.VcpuCount,
		arg.MemSizeMib,
		arg.IpAddress,
		arg.HostID,
		arg.ParentVmID,
		arg.ForkedFromCheckpointID,
		arg.Metadata,
	)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.VcpuCount,
		&i.MemSizeMib,
		&i.IpAddress,
		&i.HostID,
		&i.ParentVmID,
		&i.ForkedFromCheckpointID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Metadata,
		&i.SnapshotPath,
		&i.MemFilePath,
		&i.DiskSizeMib,
	)
	return i, err
}

const getVM = `-- name: GetVM :one
SELECT id, name, status, vcpu_count, mem_size_mib, ip_address, host_id, parent_vm_id, forked_from_checkpoint_id, created_at, updated_at, deleted_at, metadata, snapshot_path, mem_file_path, disk_size_mib FROM vms
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVM(ctx context.Context, id uuid.UUID) (Vm, error) {
	row := q.db.QueryRow(ctx, getVM, id)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.VcpuCount,
		&i.MemSizeMib,
		&i.IpAddress,
		&i.HostID,
		&i.ParentVmID,
		&i.ForkedFromCheckpointID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Metadata,
		&i.SnapshotPath,
		&i.MemFilePath,
		&i.DiskSizeMib,
	)
	return i, err
}

const getVMPauseState = `-- name: GetVMPauseState :one
SELECT snapshot_path, mem_file_path FROM vms
WHERE id = $1 AND deleted_at IS NULL
`

type GetVMPauseStateRow struct {
	SnapshotPath *string `json:"snapshot_path"`
	MemFilePath  *string `json:"mem_file_path"`
}

func (q *Queries) GetVMPauseState(ctx context.Context, id uuid.UUID) (GetVMPauseStateRow, error) {
	row := q.db.QueryRow(ctx, getVMPauseState, id)
	var i GetVMPauseStateRow
	err := row.Scan(&i.SnapshotPath, &i.MemFilePath)
	return i, err
}

const getVMStatus = `-- name: GetVMStatus :one
SELECT status FROM vms
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVMStatus(ctx context.Context, id uuid.UUID) (VmStatus, error) {
	row := q.db.QueryRow(ctx, getVMStatus, id)
	var status VmStatus
	err := row.Scan(&status)
	return status, err
}

const getVMsByParent = `-- name: GetVMsByParent :many
SELECT id, name, status, vcpu_count, mem_size_mib, ip_address, host_id, parent_vm_id, forked_from_checkpoint_id, created_at, updated_at, deleted_at, metadata, snapshot_path, mem_file_path, disk_size_mib FROM vms
WHERE parent_vm_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetVMsByParent(ctx context.Context, parentVmID pgtype.UUID) ([]Vm, error) {
	rows, err := q.db.Query(ctx, getVMsByParent, parentVmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vm{}
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.VcpuCount,
			&i.MemSizeMib,
			&i.IpAddress,
			&i.HostID,
			&i.ParentVmID,
			&i.ForkedFromCheckpointID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Metadata,
			&i.SnapshotPath,
			&i.MemFilePath,
			&i.DiskSizeMib,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMs = `-- name: ListVMs :many
SELECT id, name, status, vcpu_count, mem_size_mib, ip_address, host_id, parent_vm_id, forked_from_checkpoint_id, created_at, updated_at, deleted_at, metadata, snapshot_path, mem_file_path, disk_size_mib FROM vms
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListVMs(ctx context.Context) ([]Vm, error) {
	rows, err := q.db.Query(ctx, listVMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vm{}
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.VcpuCount,
			&i.MemSizeMib,
			&i.IpAddress,
			&i.HostID,
			&i.ParentVmID,
			&i.ForkedFromCheckpointID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Metadata,
			&i.SnapshotPath,
			&i.MemFilePath,
			&i.DiskSizeMib,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMsByStatus = `-- name: ListVMsByStatus :many
SELECT id, name, status, vcpu_count, mem_size_mib, ip_address, host_id, parent_vm_id, forked_from_checkpoint_id, created_at, updated_at, deleted_at, metadata, snapshot_path, mem_file_path, disk_size_mib FROM vms
WHERE status = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListVMsByStatus(ctx context.Context, status VmStatus) ([]Vm, error) {
	rows, err := q.db.Query(ctx, listVMsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vm{}
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.VcpuCount,
			&i.MemSizeMib,
			&i.IpAddress,
			&i.HostID,
			&i.ParentVmID,
			&i.ForkedFromCheckpointID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Metadata,
			&i.SnapshotPath,
			&i.MemFilePath,
			&i.DiskSizeMib,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseVM = `-- name: PauseVM :exec
UPDATE vms
SET status = 'paused', snapshot_path = $2, mem_file_path = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type PauseVMParams struct {
	ID           uuid.UUID `json:"id"`
	SnapshotPath *string   `json:"snapshot_path"`
	MemFilePath  *string   `json:"mem_file_path"`
}

func (q *Queries) PauseVM(ctx context.Context, arg PauseVMParams) error {
	_, err := q.db.Exec(ctx, pauseVM, arg.ID, arg.SnapshotPath, arg.MemFilePath)
	return err
}

const resumeVM = `-- name: ResumeVM :exec
UPDATE vms
SET status = 'running', ip_address = $2, snapshot_path = NULL, mem_file_path = NULL, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type ResumeVMParams struct {
	ID        uuid.UUID   `json:"id"`
	IpAddress *netip.Addr `json:"ip_address"`
}

func (q *Queries) ResumeVM(ctx context.Context, arg ResumeVMParams) error {
	_, err := q.db.Exec(ctx, resumeVM, arg.ID, arg.IpAddress)
	return err
}

const softDeleteVM = `-- name: SoftDeleteVM :exec
UPDATE vms
SET deleted_at = now(), status = 'dead', updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteVM(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteVM, id)
	return err
}

const updateVMIP = `-- name: UpdateVMIP :exec
UPDATE vms
SET ip_address = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateVMIPParams struct {
	ID        uuid.UUID   `json:"id"`
	IpAddress *netip.Addr `json:"ip_address"`
}

func (q *Queries) UpdateVMIP(ctx context.Context, arg UpdateVMIPParams) error {
	_, err := q.db.Exec(ctx, updateVMIP, arg.ID, arg.IpAddress)
	return err
}

const updateVMStatus = `-- name: UpdateVMStatus :exec
UPDATE vms
SET status = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateVMStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status VmStatus  `json:"status"`
}

func (q *Queries) UpdateVMStatus(ctx context.Context, arg UpdateVMStatusParams) error {
	_, err := q.db.Exec(ctx, updateVMStatus, arg.ID, arg.Status)
	return err
}

const updateVMStatusAndIP = `-- name: UpdateVMStatusAndIP :exec
UPDATE vms
SET status = $2, ip_address = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateVMStatusAndIPParams struct {
	ID        uuid.UUID   `json:"id"`
	Status    VmStatus    `json:"status"`
	IpAddress *netip.Addr `json:"ip_address"`
}

func (q *Queries) UpdateVMStatusAndIP(ctx context.Context, arg UpdateVMStatusAndIPParams) error {
	_, err := q.db.Exec(ctx, updateVMStatusAndIP, arg.ID, arg.Status, arg.IpAddress)
	return err
}

const vMExists = `-- name: VMExists :one
SELECT EXISTS(SELECT 1 FROM vms WHERE id = $1 AND deleted_at IS NULL)
`

func (q *Queries) VMExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, vMExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
